!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of flux_num_dnc5_nowall_nodiss_2d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDead
!Instrs with!StaticTaping):
!   variations   of useful results: residu
!   with respect to varying inputs: w
!   RW status of diff variables: w:in residu:out
! This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed w
!ith this file, You can obtain one at https://mozilla.org/MPL/2.0/
! =============================================================================
!          consistent fluxes for DNC5 2D
! =============================================================================
!
SUBROUTINE FLUX_NUM_DNC5_NOWALL_NODISS_2D_D(residu, residud, w, wd, x0, &
& y0, nx, ny, xc, yc, vol, volf, gh, cp, cv, prandtl, gam, rgaz, cs, &
& muref, tref, s_suth, k2, k4, im, jm)
  IMPLICIT NONE
! variables for dimension -----------------------------------------
  INTEGER :: im, jm, gh
! required arguments ----------------------------------------------
! thermo
  REAL*8, INTENT(IN) :: cp, cv, prandtl, gam, rgaz
! dissipation
  REAL*8, INTENT(IN) :: k2, k4
! viscosity
  REAL*8, INTENT(IN) :: cs, muref, tref, s_suth
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: x0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: y0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: nx
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: ny
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: xc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: yc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: vol
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2), INTENT(IN) :: volf
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: w
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: wd
! Returned objects ------------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residud
! Non-required arguments -------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hn
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hnd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: f, g
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: fd, gd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velx
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: vely
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velyd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velz
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tloc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: p
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mud
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradu, gradv, gradw, &
& gradmu
  REAL*8, DIMENSION(5) :: deltar, deltal, t
  INTEGER :: i, j, h
  REAL*8 :: nx_n, nx_s, nx_e, nx_o, volm1, ux, vx, wx, tx
  REAL*8 :: uxd, vxd, wxd, txd
  REAL*8 :: ny_n, ny_s, ny_e, ny_o, uy, vy, wy, ty
  REAL*8 :: uyd, vyd, wyd, tyd
  REAL*8 :: val_n, val_s, val_e, val_o
  REAL*8 :: val_nd, val_sd, val_ed, val_od
  REAL*8 :: fxro1, fxro2, fxrou1, fxrou2, fxrov1, fxrov2, fxrow1, fxrow2&
& , fxroe1, fxroe2
  REAL*8 :: fxro1d, fxro2d, fxrou1d, fxrou2d, fxrov1d, fxrov2d, fxrow1d&
& , fxrow2d, fxroe1d, fxroe2d
  REAL*8 :: fvro1, fvro2, fvrou1, fvrou2, fvrov1, fvrov2, fvrow1, fvrow2&
& , fvroe1, fvroe2
  REAL*8 :: fvrou1d, fvrou2d, fvrov1d, fvrov2d, fvrow1d, fvrow2d, &
& fvroe1d, fvroe2d
  REAL*8 :: gvro1, gvro2, gvrou1, gvrou2, gvrov1, gvrov2, gvrow1, gvrow2&
& , gvroe1, gvroe2
  REAL*8 :: gvrou1d, gvrou2d, gvrov1d, gvrov2d, gvrow1d, gvrow2d, &
& gvroe1d, gvroe2d
  REAL*8 :: dissro1, dissro2, dissrou1, dissrou2, dissrov1, dissrov2, &
& dissrow1, dissrow2, dissroe1, dissroe2
  REAL*8 :: cpprandtl, mmu, lambda, uu, vv, ww, ro, rom1, htot, eloc, ec
  REAL*8 :: mmud, lambdad, uud, vvd, wwd, rod, rom1d, htotd, elocd, ecd
  REAL*8 :: predro1, predrou1, predrov1, predrow1, predroe1, eps2, eps4
  REAL*8 :: predro2, predrou2, predrov2, predrow2, predroe2, rspec
  REAL*8 :: divu, divu2, vort2, dx, dy, dxm1, dym1, dxm2, dym2
  REAL*8 :: nxloc, nyloc, sn, invsn, sc1, sc2
  REAL*8 :: gui, gvi, gwi, gmui
  REAL*8 :: guj, gvj, gwj, gmuj
  REAL*8 :: rhom, rhomr, rhoml, rhom1l, c2l, c2r, rr, r, u, ur, ul, vr, &
& vl, wr, wl, c2x, nx2, ny2
  REAL*8 :: ab, sq, ducros1, ducros2, k_sensor1, k_sensor2
  REAL*8 :: b1, b2, b3, b4, b5, c1, c2, c3, c4, c5, d1, d2, d3, wiggle, &
& denom, betas
  REAL*8 :: omrr, coef, test, diffro, diffrou, diffrov, diffrow, diffroe&
& , v
  REAL*8 :: half, one, zero, two, twothird, fourth, twelfth, cvm1
  REAL*8 :: twentyfourth, ccross
  REAL*8 :: mach2, alpha, vn2, cprim
  INTRINSIC SQRT
  REAL*8 :: result1
  REAL*8 :: result1d
  REAL*8 :: arg1
  REAL*8 :: temp
! -----------------------------------------------------------------
!
  half = 0.5d0
  one = 1.d0
  two = 2.d0
  twothird = 2.d0/3.d0
  twelfth = 0.25d0/3.d0
  cpprandtl = cp/prandtl
  cvm1 = one/cv
  twentyfourth = one/24.d0
  ccross = twelfth*0.0625d0
! k2 = 1.d0
! k4 = 1.d0/60d0 already in coef for predictor
! Coef for grad o6
  denom = 1.d0/60.d0
!expression for FV
! c3 = b3
! c2 = c3 + b2
! c1 = c2 + b1
  c1 = 37.d0*denom
  c2 = -(8.d0*denom)
  c3 = denom
!predictor
! for Sutherland
  result1 = SQRT(tref)
  betas = muref*(tref+cs)/(result1*tref)
  fd = 0.0_8
  gd = 0.0_8
  pd = 0.0_8
  velxd = 0.0_8
  velyd = 0.0_8
  velzd = 0.0_8
  tlocd = 0.0_8
  mud = 0.0_8
! Primitives
  DO j=1-gh,jm+gh
!DIR$ IVDEP
    DO i=1-gh,im+gh
      rod = wd(i, j, 1)
      ro = w(i, j, 1)
      rom1d = -(one*rod/ro**2)
      rom1 = one/ro
      velxd(i, j) = rom1*wd(i, j, 2) + w(i, j, 2)*rom1d
      velx(i, j) = w(i, j, 2)*rom1
      velyd(i, j) = rom1*wd(i, j, 3) + w(i, j, 3)*rom1d
      vely(i, j) = w(i, j, 3)*rom1
      velzd(i, j) = rom1*wd(i, j, 4) + w(i, j, 4)*rom1d
      velz(i, j) = w(i, j, 4)*rom1
!
      ecd = half*(2*velx(i, j)*velxd(i, j)+2*vely(i, j)*velyd(i, j)+2*&
&       velz(i, j)*velzd(i, j))
      ec = half*(velx(i, j)*velx(i, j)+vely(i, j)*vely(i, j)+velz(i, j)*&
&       velz(i, j))
! ec  = HALF*( velx(i,j)*velx(i,j) &
!            + vely(i,j)*vely(i,j))
!
      temp = w(i, j, 5) - ec*ro
      elocd = rom1*(wd(i, j, 5)-ro*ecd-ec*rod) + temp*rom1d
      eloc = temp*rom1
!
      tlocd(i, j) = cvm1*elocd
      tloc(i, j) = eloc*cvm1
!
      pd(i, j) = (gam-one)*(eloc*rod+ro*elocd)
      p(i, j) = (gam-one)*ro*eloc
!  p(i,j)  = ro*rgaz*tloc(i,j)
      temp = w(i, j, 5) + p(i, j)
      htotd = rom1*(wd(i, j, 5)+pd(i, j)) + temp*rom1d
      htot = temp*rom1
      fd(i, j, 1) = wd(i, j, 2)
      fd(i, j, 2) = velx(i, j)*wd(i, j, 2) + w(i, j, 2)*velxd(i, j) + pd&
&       (i, j)
      fd(i, j, 3) = vely(i, j)*wd(i, j, 2) + w(i, j, 2)*velyd(i, j)
      fd(i, j, 4) = velz(i, j)*wd(i, j, 2) + w(i, j, 2)*velzd(i, j)
      fd(i, j, 5) = htot*wd(i, j, 2) + w(i, j, 2)*htotd
      gd(i, j, 1) = wd(i, j, 3)
      gd(i, j, 2) = velx(i, j)*wd(i, j, 3) + w(i, j, 3)*velxd(i, j)
      gd(i, j, 3) = vely(i, j)*wd(i, j, 3) + w(i, j, 3)*velyd(i, j) + pd&
&       (i, j)
      gd(i, j, 4) = velz(i, j)*wd(i, j, 3) + w(i, j, 3)*velzd(i, j)
      gd(i, j, 5) = htot*wd(i, j, 3) + w(i, j, 3)*htotd
!h(i,j,1)  = w(i,j,4)
!h(i,j,2)  = w(i,j,4) * velx(i,j)
!h(i,j,3)  = w(i,j,4) * vely(i,j)
!h(i,j,4)  = w(i,j,4) * velz(i,j) + p(i,j)
!h(i,j,5)  = w(i,j,4) * htot
      temp = SQRT(tloc(i, j))
      IF (tloc(i, j) .EQ. 0.0) THEN
        result1d = 0.0_8
      ELSE
        result1d = tlocd(i, j)/(2.0*temp)
      END IF
      result1 = temp
      temp = result1*tloc(i, j)/(s_suth+tloc(i, j))
      mud(i, j) = betas*(tloc(i, j)*result1d+(result1-temp)*tlocd(i, j))&
&       /(s_suth+tloc(i, j))
      mu(i, j) = betas*temp
    END DO
  END DO
  hnd = 0.0_8
  DO j=1,jm+1
!DIR$ IVDEP
    DO i=1,im+1
!
      fxro1d = nx(i, j, 1)*(c1*(fd(i, j, 1)+fd(i-1, j, 1))+c2*(fd(i+1, j&
&       , 1)+fd(i-2, j, 1))+c3*(fd(i+2, j, 1)+fd(i-3, j, 1))) + ny(i, j&
&       , 1)*(c1*(gd(i, j, 1)+gd(i-1, j, 1))+c2*(gd(i+1, j, 1)+gd(i-2, j&
&       , 1))+c3*(gd(i+2, j, 1)+gd(i-3, j, 1)))
      fxrou1d = nx(i, j, 1)*(c1*(fd(i, j, 2)+fd(i-1, j, 2))+c2*(fd(i+1, &
&       j, 2)+fd(i-2, j, 2))+c3*(fd(i+2, j, 2)+fd(i-3, j, 2))) + ny(i, j&
&       , 1)*(c1*(gd(i, j, 2)+gd(i-1, j, 2))+c2*(gd(i+1, j, 2)+gd(i-2, j&
&       , 2))+c3*(gd(i+2, j, 2)+gd(i-3, j, 2)))
      fxrov1d = nx(i, j, 1)*(c1*(fd(i, j, 3)+fd(i-1, j, 3))+c2*(fd(i+1, &
&       j, 3)+fd(i-2, j, 3))+c3*(fd(i+2, j, 3)+fd(i-3, j, 3))) + ny(i, j&
&       , 1)*(c1*(gd(i, j, 3)+gd(i-1, j, 3))+c2*(gd(i+1, j, 3)+gd(i-2, j&
&       , 3))+c3*(gd(i+2, j, 3)+gd(i-3, j, 3)))
      fxrow1d = nx(i, j, 1)*(c1*(fd(i, j, 4)+fd(i-1, j, 4))+c2*(fd(i+1, &
&       j, 4)+fd(i-2, j, 4))+c3*(fd(i+2, j, 4)+fd(i-3, j, 4))) + ny(i, j&
&       , 1)*(c1*(gd(i, j, 4)+gd(i-1, j, 4))+c2*(gd(i+1, j, 4)+gd(i-2, j&
&       , 4))+c3*(gd(i+2, j, 4)+gd(i-3, j, 4)))
      fxroe1d = nx(i, j, 1)*(c1*(fd(i, j, 5)+fd(i-1, j, 5))+c2*(fd(i+1, &
&       j, 5)+fd(i-2, j, 5))+c3*(fd(i+2, j, 5)+fd(i-3, j, 5))) + ny(i, j&
&       , 1)*(c1*(gd(i, j, 5)+gd(i-1, j, 5))+c2*(gd(i+1, j, 5)+gd(i-2, j&
&       , 5))+c3*(gd(i+2, j, 5)+gd(i-3, j, 5)))
      fxro2d = nx(i, j, 2)*(c1*(fd(i, j, 1)+fd(i, j-1, 1))+c2*(fd(i, j+1&
&       , 1)+fd(i, j-2, 1))+c3*(fd(i, j+2, 1)+fd(i, j-3, 1))) + ny(i, j&
&       , 2)*(c1*(gd(i, j, 1)+gd(i, j-1, 1))+c2*(gd(i, j+1, 1)+gd(i, j-2&
&       , 1))+c3*(gd(i, j+2, 1)+gd(i, j-3, 1)))
      fxrou2d = nx(i, j, 2)*(c1*(fd(i, j, 2)+fd(i, j-1, 2))+c2*(fd(i, j+&
&       1, 2)+fd(i, j-2, 2))+c3*(fd(i, j+2, 2)+fd(i, j-3, 2))) + ny(i, j&
&       , 2)*(c1*(gd(i, j, 2)+gd(i, j-1, 2))+c2*(gd(i, j+1, 2)+gd(i, j-2&
&       , 2))+c3*(gd(i, j+2, 2)+gd(i, j-3, 2)))
      fxrov2d = nx(i, j, 2)*(c1*(fd(i, j, 3)+fd(i, j-1, 3))+c2*(fd(i, j+&
&       1, 3)+fd(i, j-2, 3))+c3*(fd(i, j+2, 3)+fd(i, j-3, 3))) + ny(i, j&
&       , 2)*(c1*(gd(i, j, 3)+gd(i, j-1, 3))+c2*(gd(i, j+1, 3)+gd(i, j-2&
&       , 3))+c3*(gd(i, j+2, 3)+gd(i, j-3, 3)))
      fxrow2d = nx(i, j, 2)*(c1*(fd(i, j, 4)+fd(i, j-1, 4))+c2*(fd(i, j+&
&       1, 4)+fd(i, j-2, 4))+c3*(fd(i, j+2, 4)+fd(i, j-3, 4))) + ny(i, j&
&       , 2)*(c1*(gd(i, j, 4)+gd(i, j-1, 4))+c2*(gd(i, j+1, 4)+gd(i, j-2&
&       , 4))+c3*(gd(i, j+2, 4)+gd(i, j-3, 4)))
      fxroe2d = nx(i, j, 2)*(c1*(fd(i, j, 5)+fd(i, j-1, 5))+c2*(fd(i, j+&
&       1, 5)+fd(i, j-2, 5))+c3*(fd(i, j+2, 5)+fd(i, j-3, 5))) + ny(i, j&
&       , 2)*(c1*(gd(i, j, 5)+gd(i, j-1, 5))+c2*(gd(i, j+1, 5)+gd(i, j-2&
&       , 5))+c3*(gd(i, j+2, 5)+gd(i, j-3, 5)))
! grad for viscous fluxes o4 - 5p
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccros = TWELFTH*0.0625d0
      volm1 = volf(i, j, 1)
      nx_n = half*(nx(i+1, j, 1)+nx(i, j, 1))
      nx_s = -(half*(nx(i-1, j, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i-1, j+1, 2)+nx(i, j+1, 2))
      nx_e = -(half*(nx(i-1, j, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j, 1)+ny(i, j, 1))
      ny_s = -(half*(ny(i-1, j, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i-1, j+1, 2)+ny(i, j+1, 2))
      ny_e = -(half*(ny(i-1, j, 2)+ny(i, j, 2)))
      val_nd = twentyfourth*(26.d0*velxd(i, j)-velxd(i+1, j)-velxd(i-1, &
&       j))
      val_n = twentyfourth*(-velx(i+1, j)+26.d0*velx(i, j)-velx(i-1, j))
      val_sd = twentyfourth*(26.d0*velxd(i-1, j)-velxd(i, j)-velxd(i-2, &
&       j))
      val_s = twentyfourth*(-velx(i, j)+26.d0*velx(i-1, j)-velx(i-2, j))
      val_ed = ccross*(velxd(i-2, j-2)-9.d0*velxd(i-1, j-2)-9.d0*velxd(i&
&       , j-2)+velxd(i+1, j-2)+7.d0*(9.d0*velxd(i-1, j-1)-velxd(i-2, j-1&
&       )+9.d0*velxd(i, j-1)-velxd(i+1, j-1))+7.d0*(9.d0*velxd(i-1, j)-&
&       velxd(i-2, j)+9.d0*velxd(i, j)-velxd(i+1, j))+velxd(i-2, j+1)-&
&       9.d0*velxd(i-1, j+1)+velxd(i+1, j+1)-9.d0*velxd(i, j+1))
      val_e = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-1, j-2)+9.d0*velx(i&
&       , j-2)-velx(i+1, j-2))+7.d0*(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)&
&       +9.d0*velx(i, j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx&
&       (i-1, j)+9.d0*velx(i, j)-velx(i+1, j))-(-velx(i-2, j+1)+9.d0*&
&       velx(i-1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1)))
      val_od = ccross*(velxd(i-2, j-1)-9.d0*velxd(i-1, j-1)-9.d0*velxd(i&
&       , j-1)+velxd(i+1, j-1)+7.d0*(9.d0*velxd(i-1, j)-velxd(i-2, j)+&
&       9.d0*velxd(i, j)-velxd(i+1, j))+7.d0*(9.d0*velxd(i-1, j+1)-velxd&
&       (i-2, j+1)+9.d0*velxd(i, j+1)-velxd(i+1, j+1))+velxd(i-2, j+2)-&
&       9.d0*velxd(i-1, j+2)+velxd(i+1, j+2)-9.d0*velxd(i, j+2))
      val_o = ccross*(-(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)+9.d0*velx(i&
&       , j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+&
&       9.d0*velx(i, j)-velx(i+1, j))+7.d0*(-velx(i-2, j+1)+9.d0*velx(i-&
&       1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1))-(-velx(i-2, j+2)+9.d0*&
&       velx(i-1, j+2)+9.d0*velx(i, j+2)-velx(i+1, j+2)))
      uxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_nd = twentyfourth*(26.d0*velyd(i, j)-velyd(i+1, j)-velyd(i-1, &
&       j))
      val_n = twentyfourth*(-vely(i+1, j)+26.d0*vely(i, j)-vely(i-1, j))
      val_sd = twentyfourth*(26.d0*velyd(i-1, j)-velyd(i, j)-velyd(i-2, &
&       j))
      val_s = twentyfourth*(-vely(i, j)+26.d0*vely(i-1, j)-vely(i-2, j))
      val_ed = ccross*(velyd(i-2, j-2)-9.d0*velyd(i-1, j-2)-9.d0*velyd(i&
&       , j-2)+velyd(i+1, j-2)+7.d0*(9.d0*velyd(i-1, j-1)-velyd(i-2, j-1&
&       )+9.d0*velyd(i, j-1)-velyd(i+1, j-1))+7.d0*(9.d0*velyd(i-1, j)-&
&       velyd(i-2, j)+9.d0*velyd(i, j)-velyd(i+1, j))+velyd(i-2, j+1)-&
&       9.d0*velyd(i-1, j+1)+velyd(i+1, j+1)-9.d0*velyd(i, j+1))
      val_e = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-1, j-2)+9.d0*vely(i&
&       , j-2)-vely(i+1, j-2))+7.d0*(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)&
&       +9.d0*vely(i, j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely&
&       (i-1, j)+9.d0*vely(i, j)-vely(i+1, j))-(-vely(i-2, j+1)+9.d0*&
&       vely(i-1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1)))
      val_od = ccross*(velyd(i-2, j-1)-9.d0*velyd(i-1, j-1)-9.d0*velyd(i&
&       , j-1)+velyd(i+1, j-1)+7.d0*(9.d0*velyd(i-1, j)-velyd(i-2, j)+&
&       9.d0*velyd(i, j)-velyd(i+1, j))+7.d0*(9.d0*velyd(i-1, j+1)-velyd&
&       (i-2, j+1)+9.d0*velyd(i, j+1)-velyd(i+1, j+1))+velyd(i-2, j+2)-&
&       9.d0*velyd(i-1, j+2)+velyd(i+1, j+2)-9.d0*velyd(i, j+2))
      val_o = ccross*(-(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)+9.d0*vely(i&
&       , j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+&
&       9.d0*vely(i, j)-vely(i+1, j))+7.d0*(-vely(i-2, j+1)+9.d0*vely(i-&
&       1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1))-(-vely(i-2, j+2)+9.d0*&
&       vely(i-1, j+2)+9.d0*vely(i, j+2)-vely(i+1, j+2)))
      vxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_nd = twentyfourth*(26.d0*velzd(i, j)-velzd(i+1, j)-velzd(i-1, &
&       j))
      val_n = twentyfourth*(-velz(i+1, j)+26.d0*velz(i, j)-velz(i-1, j))
      val_sd = twentyfourth*(26.d0*velzd(i-1, j)-velzd(i, j)-velzd(i-2, &
&       j))
      val_s = twentyfourth*(-velz(i, j)+26.d0*velz(i-1, j)-velz(i-2, j))
      val_ed = ccross*(velzd(i-2, j-2)-9.d0*velzd(i-1, j-2)-9.d0*velzd(i&
&       , j-2)+velzd(i+1, j-2)+7.d0*(9.d0*velzd(i-1, j-1)-velzd(i-2, j-1&
&       )+9.d0*velzd(i, j-1)-velzd(i+1, j-1))+7.d0*(9.d0*velzd(i-1, j)-&
&       velzd(i-2, j)+9.d0*velzd(i, j)-velzd(i+1, j))+velzd(i-2, j+1)-&
&       9.d0*velzd(i-1, j+1)+velzd(i+1, j+1)-9.d0*velzd(i, j+1))
      val_e = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-1, j-2)+9.d0*velz(i&
&       , j-2)-velz(i+1, j-2))+7.d0*(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)&
&       +9.d0*velz(i, j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz&
&       (i-1, j)+9.d0*velz(i, j)-velz(i+1, j))-(-velz(i-2, j+1)+9.d0*&
&       velz(i-1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1)))
      val_od = ccross*(velzd(i-2, j-1)-9.d0*velzd(i-1, j-1)-9.d0*velzd(i&
&       , j-1)+velzd(i+1, j-1)+7.d0*(9.d0*velzd(i-1, j)-velzd(i-2, j)+&
&       9.d0*velzd(i, j)-velzd(i+1, j))+7.d0*(9.d0*velzd(i-1, j+1)-velzd&
&       (i-2, j+1)+9.d0*velzd(i, j+1)-velzd(i+1, j+1))+velzd(i-2, j+2)-&
&       9.d0*velzd(i-1, j+2)+velzd(i+1, j+2)-9.d0*velzd(i, j+2))
      val_o = ccross*(-(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)+9.d0*velz(i&
&       , j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+&
&       9.d0*velz(i, j)-velz(i+1, j))+7.d0*(-velz(i-2, j+1)+9.d0*velz(i-&
&       1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1))-(-velz(i-2, j+2)+9.d0*&
&       velz(i-1, j+2)+9.d0*velz(i, j+2)-velz(i+1, j+2)))
      wxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_nd = twentyfourth*(26.d0*tlocd(i, j)-tlocd(i+1, j)-tlocd(i-1, &
&       j))
      val_n = twentyfourth*(-tloc(i+1, j)+26.d0*tloc(i, j)-tloc(i-1, j))
      val_sd = twentyfourth*(26.d0*tlocd(i-1, j)-tlocd(i, j)-tlocd(i-2, &
&       j))
      val_s = twentyfourth*(-tloc(i, j)+26.d0*tloc(i-1, j)-tloc(i-2, j))
      val_ed = ccross*(tlocd(i-2, j-2)-9.d0*tlocd(i-1, j-2)-9.d0*tlocd(i&
&       , j-2)+tlocd(i+1, j-2)+7.d0*(9.d0*tlocd(i-1, j-1)-tlocd(i-2, j-1&
&       )+9.d0*tlocd(i, j-1)-tlocd(i+1, j-1))+7.d0*(9.d0*tlocd(i-1, j)-&
&       tlocd(i-2, j)+9.d0*tlocd(i, j)-tlocd(i+1, j))+tlocd(i-2, j+1)-&
&       9.d0*tlocd(i-1, j+1)+tlocd(i+1, j+1)-9.d0*tlocd(i, j+1))
      val_e = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-1, j-2)+9.d0*tloc(i&
&       , j-2)-tloc(i+1, j-2))+7.d0*(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)&
&       +9.d0*tloc(i, j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc&
&       (i-1, j)+9.d0*tloc(i, j)-tloc(i+1, j))-(-tloc(i-2, j+1)+9.d0*&
&       tloc(i-1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1)))
      val_od = ccross*(tlocd(i-2, j-1)-9.d0*tlocd(i-1, j-1)-9.d0*tlocd(i&
&       , j-1)+tlocd(i+1, j-1)+7.d0*(9.d0*tlocd(i-1, j)-tlocd(i-2, j)+&
&       9.d0*tlocd(i, j)-tlocd(i+1, j))+7.d0*(9.d0*tlocd(i-1, j+1)-tlocd&
&       (i-2, j+1)+9.d0*tlocd(i, j+1)-tlocd(i+1, j+1))+tlocd(i-2, j+2)-&
&       9.d0*tlocd(i-1, j+2)+tlocd(i+1, j+2)-9.d0*tlocd(i, j+2))
      val_o = ccross*(-(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i&
&       , j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc(i-1, j)+&
&       9.d0*tloc(i, j)-tloc(i+1, j))+7.d0*(-tloc(i-2, j+1)+9.d0*tloc(i-&
&       1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1))-(-tloc(i-2, j+2)+9.d0*&
&       tloc(i-1, j+2)+9.d0*tloc(i, j+2)-tloc(i+1, j+2)))
      txd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      tyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
!
! Computation of viscous fluxes
!
      uud = 0.0625d0*(9.d0*velxd(i-1, j)-velxd(i-2, j)+9.d0*velxd(i, j)-&
&       velxd(i+1, j))
      uu = 0.0625d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+9.d0*velx(i, j)-&
&       velx(i+1, j))
      vvd = 0.0625d0*(9.d0*velyd(i-1, j)-velyd(i-2, j)+9.d0*velyd(i, j)-&
&       velyd(i+1, j))
      vv = 0.0625d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+9.d0*vely(i, j)-&
&       vely(i+1, j))
      wwd = 0.0625d0*(9.d0*velzd(i-1, j)-velzd(i-2, j)+9.d0*velzd(i, j)-&
&       velzd(i+1, j))
      ww = 0.0625d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+9.d0*velz(i, j)-&
&       velz(i+1, j))
!
      mmud = 0.0625d0*(9.d0*mud(i-1, j)-mud(i-2, j)+9.d0*mud(i, j)-mud(i&
&       +1, j))
      mmu = 0.0625d0*(-mu(i-2, j)+9.d0*mu(i-1, j)+9.d0*mu(i, j)-mu(i+1, &
&       j))
      lambdad = cpprandtl*mmud
      lambda = mmu*cpprandtl
!
      fvrou1d = twothird*((two*ux-vy)*mmud+mmu*(two*uxd-vyd))
      fvrou1 = twothird*mmu*(two*ux-vy)
      fvrov1d = (uy+vx)*mmud + mmu*(uyd+vxd)
      fvrov1 = mmu*(uy+vx)
      fvrow1d = wx*mmud + mmu*wxd
      fvrow1 = mmu*wx
      fvroe1d = tx*lambdad + lambda*txd + fvrou1*uud + uu*fvrou1d + &
&       fvrov1*vvd + vv*fvrov1d + fvrow1*wwd + ww*fvrow1d
!
      gvrou1d = (uy+vx)*mmud + mmu*(uyd+vxd)
      gvrou1 = mmu*(uy+vx)
      gvrov1d = twothird*((two*vy-ux)*mmud+mmu*(two*vyd-uxd))
      gvrov1 = twothird*mmu*(-ux+two*vy)
      gvrow1d = wy*mmud + mmu*wyd
      gvrow1 = mmu*wy
      gvroe1d = ty*lambdad + lambda*tyd + gvrou1*uud + uu*gvrou1d + &
&       gvrov1*vvd + vv*gvrov1d + gvrow1*wwd + ww*gvrow1d
!!  fvrou1 = TWOTHIRD*mmu*( TWO*ux -     vy  -   wz  )
!!  fvrov1 =          mmu*(     uy +     vx          )
!!  fvrow1 =          mmu*(     uz           +   wx  )
!!  fvroe1 = lambda*tx + uu*fvrou1 + vv*fvrov1 + ww * fvrow1
!!  !
!!  gvrou1 =          mmu*(     uy +     vx          )
!!  gvrov1 = TWOTHIRD*mmu*(    -ux + TWO*vy   -  wz  )
!!  gvrow1 =          mmu*(              vz   +  wy  )
!!  gvroe1 = lambda*ty + uu*gvrou1 + vv*gvrov1 + ww * gvrow1
! grad for viscous fluxes o4 - 5p
!
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccross = TWELFTH*0.0625d0
      volm1 = volf(i, j, 2)
      nx_n = half*(nx(i+1, j-1, 1)+nx(i+1, j, 1))
      nx_s = -(half*(nx(i, j-1, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i, j+1, 2)+nx(i, j, 2))
      nx_e = -(half*(nx(i, j-1, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j-1, 1)+ny(i+1, j, 1))
      ny_s = -(half*(ny(i, j-1, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i, j+1, 2)+ny(i, j, 2))
      ny_e = -(half*(ny(i, j-1, 2)+ny(i, j, 2)))
      val_nd = ccross*(velxd(i-1, j-2)-9.d0*velxd(i-1, j-1)-9.d0*velxd(i&
&       -1, j)+velxd(i-1, j+1)+7.d0*(9.d0*velxd(i, j-1)-velxd(i, j-2)+&
&       9.d0*velxd(i, j)-velxd(i, j+1))+7.d0*(9.d0*velxd(i+1, j-1)-velxd&
&       (i+1, j-2)+9.d0*velxd(i+1, j)-velxd(i+1, j+1))+velxd(i+2, j-2)-&
&       9.d0*velxd(i+2, j-1)+velxd(i+2, j+1)-9.d0*velxd(i+2, j))
      val_n = ccross*(-(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+9.d0*velx(i-&
&       1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0&
&       *velx(i, j)-velx(i, j+1))+7.d0*(-velx(i+1, j-2)+9.d0*velx(i+1, j&
&       -1)+9.d0*velx(i+1, j)-velx(i+1, j+1))-(-velx(i+2, j-2)+9.d0*velx&
&       (i+2, j-1)+9.d0*velx(i+2, j)-velx(i+2, j+1)))
      val_sd = ccross*(velxd(i-2, j-2)-9.d0*velxd(i-2, j-1)-9.d0*velxd(i&
&       -2, j)+velxd(i-2, j+1)+7.d0*(9.d0*velxd(i-1, j-1)-velxd(i-1, j-2&
&       )+9.d0*velxd(i-1, j)-velxd(i-1, j+1))+7.d0*(9.d0*velxd(i, j-1)-&
&       velxd(i, j-2)+9.d0*velxd(i, j)-velxd(i, j+1))+velxd(i+1, j-2)-&
&       9.d0*velxd(i+1, j-1)+velxd(i+1, j+1)-9.d0*velxd(i+1, j))
      val_s = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-2, j-1)+9.d0*velx(i-&
&       2, j)-velx(i-2, j+1))+7.d0*(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+&
&       9.d0*velx(i-1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(&
&       i, j-1)+9.d0*velx(i, j)-velx(i, j+1))-(-velx(i+1, j-2)+9.d0*velx&
&       (i+1, j-1)+9.d0*velx(i+1, j)-velx(i+1, j+1)))
      val_ed = twentyfourth*(26.d0*velxd(i, j-1)-velxd(i, j)-velxd(i, j-&
&       2))
      val_e = twentyfourth*(-velx(i, j)+26.d0*velx(i, j-1)-velx(i, j-2))
      val_od = twentyfourth*(26.d0*velxd(i, j)-velxd(i, j+1)-velxd(i, j-&
&       1))
      val_o = twentyfourth*(-velx(i, j+1)+26.d0*velx(i, j)-velx(i, j-1))
      uxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_nd = ccross*(velyd(i-1, j-2)-9.d0*velyd(i-1, j-1)-9.d0*velyd(i&
&       -1, j)+velyd(i-1, j+1)+7.d0*(9.d0*velyd(i, j-1)-velyd(i, j-2)+&
&       9.d0*velyd(i, j)-velyd(i, j+1))+7.d0*(9.d0*velyd(i+1, j-1)-velyd&
&       (i+1, j-2)+9.d0*velyd(i+1, j)-velyd(i+1, j+1))+velyd(i+2, j-2)-&
&       9.d0*velyd(i+2, j-1)+velyd(i+2, j+1)-9.d0*velyd(i+2, j))
      val_n = ccross*(-(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+9.d0*vely(i-&
&       1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0&
&       *vely(i, j)-vely(i, j+1))+7.d0*(-vely(i+1, j-2)+9.d0*vely(i+1, j&
&       -1)+9.d0*vely(i+1, j)-vely(i+1, j+1))-(-vely(i+2, j-2)+9.d0*vely&
&       (i+2, j-1)+9.d0*vely(i+2, j)-vely(i+2, j+1)))
      val_sd = ccross*(velyd(i-2, j-2)-9.d0*velyd(i-2, j-1)-9.d0*velyd(i&
&       -2, j)+velyd(i-2, j+1)+7.d0*(9.d0*velyd(i-1, j-1)-velyd(i-1, j-2&
&       )+9.d0*velyd(i-1, j)-velyd(i-1, j+1))+7.d0*(9.d0*velyd(i, j-1)-&
&       velyd(i, j-2)+9.d0*velyd(i, j)-velyd(i, j+1))+velyd(i+1, j-2)-&
&       9.d0*velyd(i+1, j-1)+velyd(i+1, j+1)-9.d0*velyd(i+1, j))
      val_s = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-2, j-1)+9.d0*vely(i-&
&       2, j)-vely(i-2, j+1))+7.d0*(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+&
&       9.d0*vely(i-1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(&
&       i, j-1)+9.d0*vely(i, j)-vely(i, j+1))-(-vely(i+1, j-2)+9.d0*vely&
&       (i+1, j-1)+9.d0*vely(i+1, j)-vely(i+1, j+1)))
      val_ed = twentyfourth*(26.d0*velyd(i, j-1)-velyd(i, j)-velyd(i, j-&
&       2))
      val_e = twentyfourth*(-vely(i, j)+26.d0*vely(i, j-1)-vely(i, j-2))
      val_od = twentyfourth*(26.d0*velyd(i, j)-velyd(i, j+1)-velyd(i, j-&
&       1))
      val_o = twentyfourth*(-vely(i, j+1)+26.d0*vely(i, j)-vely(i, j-1))
      vxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_nd = ccross*(velzd(i-1, j-2)-9.d0*velzd(i-1, j-1)-9.d0*velzd(i&
&       -1, j)+velzd(i-1, j+1)+7.d0*(9.d0*velzd(i, j-1)-velzd(i, j-2)+&
&       9.d0*velzd(i, j)-velzd(i, j+1))+7.d0*(9.d0*velzd(i+1, j-1)-velzd&
&       (i+1, j-2)+9.d0*velzd(i+1, j)-velzd(i+1, j+1))+velzd(i+2, j-2)-&
&       9.d0*velzd(i+2, j-1)+velzd(i+2, j+1)-9.d0*velzd(i+2, j))
      val_n = ccross*(-(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+9.d0*velz(i-&
&       1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0&
&       *velz(i, j)-velz(i, j+1))+7.d0*(-velz(i+1, j-2)+9.d0*velz(i+1, j&
&       -1)+9.d0*velz(i+1, j)-velz(i+1, j+1))-(-velz(i+2, j-2)+9.d0*velz&
&       (i+2, j-1)+9.d0*velz(i+2, j)-velz(i+2, j+1)))
      val_sd = ccross*(velzd(i-2, j-2)-9.d0*velzd(i-2, j-1)-9.d0*velzd(i&
&       -2, j)+velzd(i-2, j+1)+7.d0*(9.d0*velzd(i-1, j-1)-velzd(i-1, j-2&
&       )+9.d0*velzd(i-1, j)-velzd(i-1, j+1))+7.d0*(9.d0*velzd(i, j-1)-&
&       velzd(i, j-2)+9.d0*velzd(i, j)-velzd(i, j+1))+velzd(i+1, j-2)-&
&       9.d0*velzd(i+1, j-1)+velzd(i+1, j+1)-9.d0*velzd(i+1, j))
      val_s = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-2, j-1)+9.d0*velz(i-&
&       2, j)-velz(i-2, j+1))+7.d0*(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+&
&       9.d0*velz(i-1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(&
&       i, j-1)+9.d0*velz(i, j)-velz(i, j+1))-(-velz(i+1, j-2)+9.d0*velz&
&       (i+1, j-1)+9.d0*velz(i+1, j)-velz(i+1, j+1)))
      val_ed = twentyfourth*(26.d0*velzd(i, j-1)-velzd(i, j)-velzd(i, j-&
&       2))
      val_e = twentyfourth*(-velz(i, j)+26.d0*velz(i, j-1)-velz(i, j-2))
      val_od = twentyfourth*(26.d0*velzd(i, j)-velzd(i, j+1)-velzd(i, j-&
&       1))
      val_o = twentyfourth*(-velz(i, j+1)+26.d0*velz(i, j)-velz(i, j-1))
      wxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_nd = ccross*(tlocd(i-1, j-2)-9.d0*tlocd(i-1, j-1)-9.d0*tlocd(i&
&       -1, j)+tlocd(i-1, j+1)+7.d0*(9.d0*tlocd(i, j-1)-tlocd(i, j-2)+&
&       9.d0*tlocd(i, j)-tlocd(i, j+1))+7.d0*(9.d0*tlocd(i+1, j-1)-tlocd&
&       (i+1, j-2)+9.d0*tlocd(i+1, j)-tlocd(i+1, j+1))+tlocd(i+2, j-2)-&
&       9.d0*tlocd(i+2, j-1)+tlocd(i+2, j+1)-9.d0*tlocd(i+2, j))
      val_n = ccross*(-(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i-&
&       1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(i, j-1)+9.d0&
&       *tloc(i, j)-tloc(i, j+1))+7.d0*(-tloc(i+1, j-2)+9.d0*tloc(i+1, j&
&       -1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1))-(-tloc(i+2, j-2)+9.d0*tloc&
&       (i+2, j-1)+9.d0*tloc(i+2, j)-tloc(i+2, j+1)))
      val_sd = ccross*(tlocd(i-2, j-2)-9.d0*tlocd(i-2, j-1)-9.d0*tlocd(i&
&       -2, j)+tlocd(i-2, j+1)+7.d0*(9.d0*tlocd(i-1, j-1)-tlocd(i-1, j-2&
&       )+9.d0*tlocd(i-1, j)-tlocd(i-1, j+1))+7.d0*(9.d0*tlocd(i, j-1)-&
&       tlocd(i, j-2)+9.d0*tlocd(i, j)-tlocd(i, j+1))+tlocd(i+1, j-2)-&
&       9.d0*tlocd(i+1, j-1)+tlocd(i+1, j+1)-9.d0*tlocd(i+1, j))
      val_s = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-2, j-1)+9.d0*tloc(i-&
&       2, j)-tloc(i-2, j+1))+7.d0*(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+&
&       9.d0*tloc(i-1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(&
&       i, j-1)+9.d0*tloc(i, j)-tloc(i, j+1))-(-tloc(i+1, j-2)+9.d0*tloc&
&       (i+1, j-1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1)))
      val_ed = twentyfourth*(26.d0*tlocd(i, j-1)-tlocd(i, j)-tlocd(i, j-&
&       2))
      val_e = twentyfourth*(-tloc(i, j)+26.d0*tloc(i, j-1)-tloc(i, j-2))
      val_od = twentyfourth*(26.d0*tlocd(i, j)-tlocd(i, j+1)-tlocd(i, j-&
&       1))
      val_o = twentyfourth*(-tloc(i, j+1)+26.d0*tloc(i, j)-tloc(i, j-1))
      txd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      tyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      uud = 0.0625d0*(9.d0*velxd(i, j-1)-velxd(i, j-2)+9.d0*velxd(i, j)-&
&       velxd(i, j+1))
      uu = 0.0625d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0*velx(i, j)-&
&       velx(i, j+1))
      vvd = 0.0625d0*(9.d0*velyd(i, j-1)-velyd(i, j-2)+9.d0*velyd(i, j)-&
&       velyd(i, j+1))
      vv = 0.0625d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0*vely(i, j)-&
&       vely(i, j+1))
      wwd = 0.0625d0*(9.d0*velzd(i, j-1)-velzd(i, j-2)+9.d0*velzd(i, j)-&
&       velzd(i, j+1))
      ww = 0.0625d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0*velz(i, j)-&
&       velz(i, j+1))
!
      mmud = 0.0625d0*(9.d0*mud(i, j-1)-mud(i, j-2)+9.d0*mud(i, j)-mud(i&
&       , j+1))
      mmu = 0.0625d0*(-mu(i, j-2)+9.d0*mu(i, j-1)+9.d0*mu(i, j)-mu(i, j+&
&       1))
      lambdad = cpprandtl*mmud
      lambda = mmu*cpprandtl
!
      fvrou2d = twothird*((two*ux-vy)*mmud+mmu*(two*uxd-vyd))
      fvrou2 = twothird*mmu*(two*ux-vy)
      fvrov2d = (uy+vx)*mmud + mmu*(uyd+vxd)
      fvrov2 = mmu*(uy+vx)
      fvrow2d = wx*mmud + mmu*wxd
      fvrow2 = mmu*wx
      fvroe2d = tx*lambdad + lambda*txd + fvrou2*uud + uu*fvrou2d + &
&       fvrov2*vvd + vv*fvrov2d + fvrow2*wwd + ww*fvrow2d
      gvrou2d = (uy+vx)*mmud + mmu*(uyd+vxd)
      gvrou2 = mmu*(uy+vx)
      gvrov2d = twothird*((two*vy-ux)*mmud+mmu*(two*vyd-uxd))
      gvrov2 = twothird*mmu*(-ux+two*vy)
      gvrow2d = wy*mmud + mmu*wyd
      gvrow2 = mmu*wy
      gvroe2d = ty*lambdad + lambda*tyd + gvrou2*uud + uu*gvrou2d + &
&       gvrov2*vvd + vv*gvrov2d + gvrow2*wwd + ww*gvrow2d
!!  fvrou2 = TWOTHIRD*mmu*( TWO*ux -     vy  -  wz  )
!!  fvrov2 =          mmu*(     uy +     vx         )
!!  fvrow2 =          mmu*(     uz           +  wx  )
!!  fvroe2 = (lambda*tx + uu*fvrou2 + vv*fvrov2 + ww * fvrow2)
!!
!!  gvrou2 =          mmu*(     uy +     vx       )
!!  gvrov2 = TWOTHIRD*mmu*(    -ux + TWO*vy -  wz )
!!  gvrow2 =          mmu*(              vz +  wy )
!!  gvroe2 = (lambda*ty + uu*gvrou2 + vv*gvrov2 + ww*gvrow2)
      sc1 = nx(i, j, 1)
      sc2 = ny(i, j, 1)
      arg1 = sc1*sc1 + sc2*sc2
      sn = SQRT(arg1)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
      hnd(i, j, 1, 1) = fxro1d
!
      hnd(i, j, 2, 1) = fxrou1d - sn*(nxloc*fvrou1d+nyloc*gvrou1d)
!
      hnd(i, j, 3, 1) = fxrov1d - sn*(nxloc*fvrov1d+nyloc*gvrov1d)
!
      hnd(i, j, 4, 1) = fxrow1d - sn*(nxloc*fvrow1d+nyloc*gvrow1d)
!
      hnd(i, j, 5, 1) = fxroe1d - sn*(nxloc*fvroe1d+nyloc*gvroe1d)
      sc1 = nx(i, j, 2)
      sc2 = ny(i, j, 2)
      arg1 = sc1*sc1 + sc2*sc2
      sn = SQRT(arg1)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
      hnd(i, j, 1, 2) = fxro2d
!
      hnd(i, j, 2, 2) = fxrou2d - sn*(nxloc*fvrou2d+nyloc*gvrou2d)
!
      hnd(i, j, 3, 2) = fxrov2d - sn*(nxloc*fvrov2d+nyloc*gvrov2d)
!
      hnd(i, j, 4, 2) = fxrow2d - sn*(nxloc*fvrow2d+nyloc*gvrow2d)
!
      hnd(i, j, 5, 2) = fxroe2d - sn*(nxloc*fvroe2d+nyloc*gvroe2d)
    END DO
  END DO
  residud = 0.0_8
!
! fluxes balance
  DO j=1,jm
!DIR$ IVDEP
    DO i=1,im
      residud(i, j, 1) = hnd(i, j, 1, 1) - hnd(i+1, j, 1, 1) + hnd(i, j&
&       , 1, 2) - hnd(i, j+1, 1, 2)
      residud(i, j, 2) = hnd(i, j, 2, 1) - hnd(i+1, j, 2, 1) + hnd(i, j&
&       , 2, 2) - hnd(i, j+1, 2, 2)
      residud(i, j, 3) = hnd(i, j, 3, 1) - hnd(i+1, j, 3, 1) + hnd(i, j&
&       , 3, 2) - hnd(i, j+1, 3, 2)
      residud(i, j, 4) = hnd(i, j, 4, 1) - hnd(i+1, j, 4, 1) + hnd(i, j&
&       , 4, 2) - hnd(i, j+1, 4, 2)
      residud(i, j, 5) = hnd(i, j, 5, 1) - hnd(i+1, j, 5, 1) + hnd(i, j&
&       , 5, 2) - hnd(i, j+1, 5, 2)
    END DO
  END DO
END SUBROUTINE FLUX_NUM_DNC5_NOWALL_NODISS_2D_D
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

