! This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of bordersfromcenters_2d_d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDeadInstrs 
!with!StaticTaping):
!   variations   of useful results: x0d y0d
!   with respect to varying inputs: x0d ycd y0d xcd
!   RW status of diff variables: x0d:in-out ycd:in y0d:in-out xcd:in
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of bordersfromcenters_2d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDeadInstrs wi
!th!StaticTaping):
!   variations   of useful results: x0 y0
!   with respect to varying inputs: xc yc x0 y0
!   RW status of diff variables: xc:in yc:in x0:in-out y0:in-out
SUBROUTINE BORDERSFROMCENTERS_2D_D_D(x0, x0d, x0dd, y0, y0d, y0dd, xc, &
& xcd, xcdd, yc, ycd, ycdd, im, jm)
  IMPLICIT NONE
! variables for dimension -----------------------------------------
  INTEGER :: im, jm, gh
! required arguments ----------------------------------------------
! Returned objects ------------------------------------------------
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: x0
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: x0d
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: x0dd
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: y0
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: y0d
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: y0dd
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: xc
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: xcd
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: xcdd
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: yc
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: ycd
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: ycdd
! Non-required arguments -------------------------------------------
  INTEGER :: i, j, g, dummy
! ------------------------------------------------------------------
  REAL*8 :: two, half, fourth
  fourth = 0.25d0
  DO j=2,jm
!DIR$ IVDEP
    DO i=2,im
      x0dd(i, j) = fourth*(xcdd(i-1, j-1)+xcdd(i, j-1)+xcdd(i-1, j)+xcdd&
&       (i, j))
      y0dd(i, j) = fourth*(ycdd(i-1, j-1)+ycdd(i, j-1)+ycdd(i-1, j)+ycdd&
&       (i, j))
    END DO
  END DO
  DO j=2,jm
    x0dd(im+1, j) = xcdd(im, j) + xcdd(im, j-1) - x0dd(im, j)
    y0dd(im+1, j) = ycdd(im, j) + ycdd(im, j-1) - y0dd(im, j)
    x0dd(1, j) = xcdd(1, j) + xcdd(1, j-1) - x0dd(2, j)
    y0dd(1, j) = ycdd(1, j) + ycdd(1, j-1) - y0dd(2, j)
  END DO
  DO i=2,im
    x0dd(i, jm+1) = xcdd(i, jm) + xcdd(i-1, jm) - x0dd(i, jm)
    y0dd(i, jm+1) = ycdd(i, jm) + ycdd(i-1, jm) - y0dd(i, jm)
    x0dd(i, 1) = xcdd(i, 1) + xcdd(i-1, 1) - x0dd(i, 2)
    y0dd(i, 1) = ycdd(i, 1) + ycdd(i-1, 1) - y0dd(i, 2)
  END DO
  x0dd(im+1, jm+1) = x0dd(im, jm+1) + x0dd(im+1, jm) - x0dd(im, jm)
  y0dd(im+1, jm+1) = y0dd(im, jm+1) + y0dd(im+1, jm) - y0dd(im, jm)
  x0dd(1, jm+1) = x0dd(1, jm) + x0dd(2, jm+1) - x0dd(2, jm)
  y0dd(1, jm+1) = y0dd(1, jm) + y0dd(2, jm+1) - y0dd(2, jm)
  x0dd(im+1, 1) = x0dd(im, 1) + x0dd(im+1, 2) - x0dd(im, 2)
  y0dd(im+1, 1) = y0dd(im, 1) + y0dd(im+1, 2) - y0dd(im, 2)
  x0dd(1, 1) = x0dd(1, 2) + x0dd(2, 1) - x0dd(2, 2)
  y0dd(1, 1) = y0dd(1, 2) + y0dd(2, 1) - y0dd(2, 2)
END SUBROUTINE BORDERSFROMCENTERS_2D_D_D

