!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of flux_num_dnc5_maxsc_2d_d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDeadInstrs
! with!StaticTaping):
!   variations   of useful results: residud
!   with respect to varying inputs: w
!   RW status of diff variables: w:in residud:out
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of flux_num_dnc5_maxsc_2d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDeadInstrs w
!ith!StaticTaping):
!   variations   of useful results: residu
!   with respect to varying inputs: w
!   RW status of diff variables: w:in residu:out
! This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed w
!ith this file, You can obtain one at https://mozilla.org/MPL/2.0/
! =============================================================================
!          consistent fluxes for DNC5 2D
! =============================================================================
!
SUBROUTINE FLUX_NUM_DNC5_MAXSC_2D_D_D(residu, residud, residudd, w, wd0&
& , wd, x0, y0, nx, ny, xc, yc, vol, volf, gh, cp, cv, prandtl, gam, &
& rgaz, cs, muref, tref, s_suth, k2, k4, im, jm)
  IMPLICIT NONE
! variables for dimension -----------------------------------------
  INTEGER :: im, jm, gh
! required arguments ----------------------------------------------
! thermo
  REAL*8, INTENT(IN) :: cp, cv, prandtl, gam, rgaz
! dissipation
  REAL*8, INTENT(IN) :: k2, k4
! viscosity
  REAL*8, INTENT(IN) :: cs, muref, tref, s_suth
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: x0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: y0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: nx
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: ny
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: xc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: yc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: vol
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2), INTENT(IN) :: volf
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: w
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: wd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: wd
! Returned objects ------------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residud
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: &
& residudd
! Non-required arguments -------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hn
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hnd
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hndd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: f, g
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: fd, gd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: fdd, gdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velx
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: vely
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velyd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velyd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velydd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velz
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tloc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: p
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mud0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mud
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mudd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradu, gradv, gradw, &
& gradmu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradud0, gradvd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradud, gradvd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradudd, gradvdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: eps2arra
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: eps2arrad0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: eps2arrad
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: eps2arradd
  REAL*8, DIMENSION(5) :: deltar, deltal, t
  INTEGER :: i, j, h, k, l
  REAL*8 :: nx_n, nx_s, nx_e, nx_o, volm1, ux, vx, wx, tx
  REAL*8 :: uxd0, vxd0, wxd0, txd0
  REAL*8 :: uxd, vxd, wxd, txd
  REAL*8 :: uxdd, vxdd, wxdd, txdd
  REAL*8 :: ny_n, ny_s, ny_e, ny_o, uy, vy, wy, ty
  REAL*8 :: uyd0, vyd0, wyd0, tyd0
  REAL*8 :: uyd, vyd, wyd, tyd
  REAL*8 :: uydd, vydd, wydd, tydd
  REAL*8 :: val_n, val_s, val_e, val_o
  REAL*8 :: val_nd0, val_sd0, val_ed0, val_od0
  REAL*8 :: val_nd, val_sd, val_ed, val_od
  REAL*8 :: val_ndd, val_sdd, val_edd, val_odd
  REAL*8 :: fxro1, fxro2, fxrou1, fxrou2, fxrov1, fxrov2, fxrow1, fxrow2&
& , fxroe1, fxroe2
  REAL*8 :: fxro1d, fxro2d, fxrou1d, fxrou2d, fxrov1d, fxrov2d, fxrow1d&
& , fxrow2d, fxroe1d, fxroe2d
  REAL*8 :: fxro1dd, fxro2dd, fxrou1dd, fxrou2dd, fxrov1dd, fxrov2dd, &
& fxrow1dd, fxrow2dd, fxroe1dd, fxroe2dd
  REAL*8 :: fvro1, fvro2, fvrou1, fvrou2, fvrov1, fvrov2, fvrow1, fvrow2&
& , fvroe1, fvroe2
  REAL*8 :: fvrou1d0, fvrou2d0, fvrov1d0, fvrov2d0, fvrow1d0, fvrow2d0
  REAL*8 :: fvrou1d, fvrou2d, fvrov1d, fvrov2d, fvrow1d, fvrow2d, &
& fvroe1d, fvroe2d
  REAL*8 :: fvrou1dd, fvrou2dd, fvrov1dd, fvrov2dd, fvrow1dd, fvrow2dd, &
& fvroe1dd, fvroe2dd
  REAL*8 :: gvro1, gvro2, gvrou1, gvrou2, gvrov1, gvrov2, gvrow1, gvrow2&
& , gvroe1, gvroe2
  REAL*8 :: gvrou1d0, gvrou2d0, gvrov1d0, gvrov2d0, gvrow1d0, gvrow2d0
  REAL*8 :: gvrou1d, gvrou2d, gvrov1d, gvrov2d, gvrow1d, gvrow2d, &
& gvroe1d, gvroe2d
  REAL*8 :: gvrou1dd, gvrou2dd, gvrov1dd, gvrov2dd, gvrow1dd, gvrow2dd, &
& gvroe1dd, gvroe2dd
  REAL*8 :: dissro1, dissro2, dissrou1, dissrou2, dissrov1, dissrov2, &
& dissrow1, dissrow2, dissroe1, dissroe2
  REAL*8 :: dissro1d, dissro2d, dissrou1d, dissrou2d, dissrov1d, &
& dissrov2d, dissrow1d, dissrow2d, dissroe1d, dissroe2d
  REAL*8 :: dissro1dd, dissro2dd, dissrou1dd, dissrou2dd, dissrov1dd, &
& dissrov2dd, dissrow1dd, dissrow2dd, dissroe1dd, dissroe2dd
  REAL*8 :: cpprandtl, mmu, lambda, uu, vv, ww, ro, rom1, htot, eloc, ec
  REAL*8 :: mmud0, lambdad0, uud0, vvd0, wwd0, rod0, rom1d0, htotd0, &
& elocd0, ecd0
  REAL*8 :: mmud, lambdad, uud, vvd, wwd, rod, rom1d, htotd, elocd, ecd
  REAL*8 :: mmudd, lambdadd, uudd, vvdd, wwdd, rom1dd, htotdd, elocdd, &
& ecdd
  REAL*8 :: predro1, predrou1, predrov1, predrow1, predroe1, eps2, eps4
  REAL*8 :: predro1d0, predrou1d0, predrov1d0, predrow1d0, predroe1d0, &
& eps2d0, eps4d0
  REAL*8 :: predro1d, predrou1d, predrov1d, predrow1d, predroe1d, eps2d&
& , eps4d
  REAL*8 :: eps2dd, eps4dd
  REAL*8 :: predro2, predrou2, predrov2, predrow2, predroe2, rspec, &
& rspecbis
  REAL*8 :: predro2d0, predrou2d0, predrov2d0, predrow2d0, predroe2d0, &
& rspecd0, rspecbisd0
  REAL*8 :: predro2d, predrou2d, predrov2d, predrow2d, predroe2d, rspecd&
& , rspecbisd
  REAL*8 :: rspecdd, rspecbisdd
  REAL*8 :: divu2, vort2, dx, dy, dxm1, dym1, dxm2, dym2
  REAL*8 :: divu2d0, vort2d0, dxm1d0
  REAL*8 :: divu2d, vort2d, dxm1d
  REAL*8 :: divu2dd, vort2dd, dxm1dd
  REAL*8 :: nxloc, nyloc, sn, invsn, sc1, sc2
  REAL*8 :: gui, gvi, gwi, gmui
  REAL*8 :: guid0, gvid0
  REAL*8 :: guid, gvid
  REAL*8 :: guidd, gvidd
  REAL*8 :: guj, gvj, gwj, gmuj
  REAL*8 :: gujd0, gvjd0
  REAL*8 :: gujd, gvjd
  REAL*8 :: gujdd, gvjdd
  REAL*8 :: rhom, rhomr, rhoml, rhom1l, c2l, c2r, rr, r, u, ur, ul, vr, &
& vl, wr, wl, c2x, nx2, ny2
  REAL*8 :: rhomrd0, rhomld0, c2ld0, c2rd0, rrd0, rd0, ud0, urd0, uld0, &
& vrd0, vld0, c2xd0
  REAL*8 :: rhomrd, rhomld, c2ld, c2rd, rrd, rd, ud, urd, uld, vrd, vld&
& , c2xd
  REAL*8 :: c2ldd, c2rdd, rrdd, rdd, udd, urdd, uldd, vrdd, vldd, c2xdd
  REAL*8 :: ab, sq, ducros1, ducros2, k_sensor1, k_sensor2, sqbis
  REAL*8 :: abd0, sqd0, ducros1d0, k_sensor1d0, sqbisd0
  REAL*8 :: abd, sqd, ducros1d, k_sensor1d, sqbisd
  REAL*8 :: abdd, sqdd, ducros1dd, k_sensor1dd, sqbisdd
  REAL*8 :: b1, b2, b3, b4, b5, c1, c2, c3, c4, c5, d1, d2, d3, wiggle, &
& denom, betas
  REAL*8 :: c5d0, c5d1, c5d2, c5d3, c5d4, c5d5
  REAL*8 :: c3d0, c3d1, c3d2, c3d3, c3d4, c3d5
  REAL*8 :: pw, ct0, ct1, ct2, omrr, coef, test, diffro, diffrou, &
& diffrov, diffrow, diffroe, v
  REAL*8 :: omrrd0, coefd0, diffrod0, diffroud0, diffrovd0, diffrowd0, &
& diffroed0, vd0
  REAL*8 :: omrrd, coefd, diffrod, diffroud, diffrovd, diffrowd, &
& diffroed, vd
  REAL*8 :: omrrdd, coefdd, vdd
  REAL*8 :: half, one, zero, two, twothird, fourth, twelfth, cvm1, &
& twelve
  REAL*8 :: twentyfourth, ccross
  INTRINSIC SQRT
  INTRINSIC ABS
  INTRINSIC MAX
  INTRINSIC TANH
  REAL*8 :: x1
  REAL*8 :: x2
  REAL*8 :: x2d0
  REAL*8 :: x2d
  REAL*8 :: x2dd
  REAL*8 :: y1
  REAL*8 :: y1d0
  REAL*8 :: y1d
  REAL*8 :: y1dd
  REAL*8 :: x3
  REAL*8 :: x3d0
  REAL*8 :: x3d
  REAL*8 :: x3dd
  REAL*8 :: y2
  REAL*8 :: y2d0
  REAL*8 :: y2d
  REAL*8 :: y2dd
  REAL*8 :: y3
  REAL*8 :: y3d0
  REAL*8 :: y3d
  REAL*8 :: y3dd
  REAL*8 :: y4
  REAL*8 :: y4d0
  REAL*8 :: y4d
  REAL*8 :: y4dd
  REAL*8 :: y5
  REAL*8 :: y5d0
  REAL*8 :: y5d
  REAL*8 :: y5dd
  REAL*8 :: y6
  REAL*8 :: y6d0
  REAL*8 :: y6d
  REAL*8 :: y6dd
  REAL*8 :: y7
  REAL*8 :: y7d0
  REAL*8 :: y7d
  REAL*8 :: y7dd
  REAL*8 :: y8
  REAL*8 :: y8d0
  REAL*8 :: y8d
  REAL*8 :: y8dd
  REAL*8 :: y9
  REAL*8 :: y9d0
  REAL*8 :: y9d
  REAL*8 :: y9dd
  REAL*8 :: y10
  REAL*8 :: y10d0
  REAL*8 :: y10d
  REAL*8 :: y10dd
  REAL*8 :: y11
  REAL*8 :: y11d0
  REAL*8 :: y11d
  REAL*8 :: y11dd
  REAL*8 :: y12
  REAL*8 :: y12d0
  REAL*8 :: y12d
  REAL*8 :: y12dd
  REAL*8 :: y13
  REAL*8 :: y13d0
  REAL*8 :: y13d
  REAL*8 :: y13dd
  REAL*8 :: abs0
  REAL*8 :: abs0d0
  REAL*8 :: abs0d
  REAL*8 :: abs0dd
  REAL*8 :: abs1
  REAL*8 :: abs1d0
  REAL*8 :: abs1d
  REAL*8 :: abs1dd
  REAL*8 :: result1
  REAL*8 :: result1d0
  REAL*8 :: result1d
  REAL*8 :: result1dd
  REAL*8 :: arg1
  REAL*8 :: arg1d0
  REAL*8 :: arg1d
  REAL*8 :: arg1dd
  REAL*8 :: temp
  REAL*8 :: tempd
  REAL*8 :: temp0
  REAL*8 :: temp0d
  REAL*8 :: temp1
  REAL*8 :: temp2
  REAL*8 :: temp3
! -----------------------------------------------------------------
!
  half = 0.5d0
  one = 1.d0
  zero = 0.d0
  two = 2.d0
  twothird = 2.d0/3.d0
  twelfth = 0.25d0/3.d0
  cpprandtl = cp/prandtl
  cvm1 = one/cv
  twentyfourth = one/24.d0
  ccross = twelfth*0.0625d0
! k2 = 1.d0
! k4 = 1.d0/60d0 already in coef for predictor
! Coef for grad o4
  denom = 1.d0/12.d0
  b1 = 8.d0*denom
  b2 = -denom
! Coef for grad o6
  denom = 1.d0/60.d0
! b1 =  45.d0 * denom
! b2 = - 9.d0 * denom
! b3 =          denom
!expression for FV
! c3 = b3
! c2 = c3 + b2
! c1 = c2 + b1
  c1 = 37.d0*denom
  c2 = -(8.d0*denom)
  c3 = denom
!predictor
  d1 = 10.d0*denom
  d2 = 5.d0*denom
  d3 = denom
! for Sutherland
  result1 = SQRT(tref)
  betas = muref*(tref+cs)/(result1*tref)
  pd = 0.0_8
  velxd = 0.0_8
  velyd = 0.0_8
  velzd = 0.0_8
  tlocd = 0.0_8
  mud = 0.0_8
  tlocdd = 0.0_8
  velydd = 0.0_8
  pd0 = 0.0_8
  velzdd = 0.0_8
  fdd = 0.0_8
  velxd0 = 0.0_8
  velyd0 = 0.0_8
  velzd0 = 0.0_8
  pdd = 0.0_8
  mudd = 0.0_8
  velxdd = 0.0_8
  tlocd0 = 0.0_8
  gdd = 0.0_8
  mud0 = 0.0_8
! Primitives
  DO j=1-gh,jm+gh
!DIR$ IVDEP
    DO i=1-gh,im+gh
      rod = wd(i, j, 1)
      rod0 = wd0(i, j, 1)
      ro = w(i, j, 1)
      temp1 = one*rod/(ro*ro)
      rom1dd = temp1*2*rod0/ro
      rom1d = -temp1
      rom1d0 = -(one*rod0/ro**2)
      rom1 = one/ro
      velxdd(i, j) = wd(i, j, 2)*rom1d0 + rom1d*wd0(i, j, 2) + w(i, j, 2&
&       )*rom1dd
      velxd(i, j) = rom1*wd(i, j, 2) + w(i, j, 2)*rom1d
      velxd0(i, j) = rom1*wd0(i, j, 2) + w(i, j, 2)*rom1d0
      velx(i, j) = w(i, j, 2)*rom1
      velydd(i, j) = wd(i, j, 3)*rom1d0 + rom1d*wd0(i, j, 3) + w(i, j, 3&
&       )*rom1dd
      velyd(i, j) = rom1*wd(i, j, 3) + w(i, j, 3)*rom1d
      velyd0(i, j) = rom1*wd0(i, j, 3) + w(i, j, 3)*rom1d0
      vely(i, j) = w(i, j, 3)*rom1
      velzdd(i, j) = wd(i, j, 4)*rom1d0 + rom1d*wd0(i, j, 4) + w(i, j, 4&
&       )*rom1dd
      velzd(i, j) = rom1*wd(i, j, 4) + w(i, j, 4)*rom1d
      velzd0(i, j) = rom1*wd0(i, j, 4) + w(i, j, 4)*rom1d0
      velz(i, j) = w(i, j, 4)*rom1
!
      temp1 = 2*velx(i, j)
      temp2 = 2*vely(i, j)
      temp3 = 2*velz(i, j)
      ecdd = half*(velxd(i, j)*2*velxd0(i, j)+temp1*velxdd(i, j)+velyd(i&
&       , j)*2*velyd0(i, j)+temp2*velydd(i, j)+velzd(i, j)*2*velzd0(i, j&
&       )+temp3*velzdd(i, j))
      ecd = half*(temp1*velxd(i, j)+temp2*velyd(i, j)+temp3*velzd(i, j))
      ecd0 = half*(2*velx(i, j)*velxd0(i, j)+2*vely(i, j)*velyd0(i, j)+2&
&       *velz(i, j)*velzd0(i, j))
      ec = half*(velx(i, j)*velx(i, j)+vely(i, j)*vely(i, j)+velz(i, j)*&
&       velz(i, j))
! ec  = HALF*( velx(i,j)*velx(i,j) &
!            + vely(i,j)*vely(i,j))
!
      tempd = wd0(i, j, 5) - ro*ecd0 - ec*rod0
      temp = w(i, j, 5) - ec*ro
      temp3 = wd(i, j, 5) - ro*ecd - rod*ec
      elocdd = temp3*rom1d0 + rom1*(-(ecd*rod0)-ro*ecdd-rod*ecd0) + &
&       rom1d*tempd + temp*rom1dd
      elocd = rom1*temp3 + temp*rom1d
      elocd0 = rom1*tempd + temp*rom1d0
      eloc = temp*rom1
!
      tlocdd(i, j) = cvm1*elocdd
      tlocd(i, j) = cvm1*elocd
      tlocd0(i, j) = cvm1*elocd0
      tloc(i, j) = eloc*cvm1
!
      pdd(i, j) = (gam-one)*(rod*elocd0+elocd*rod0+ro*elocdd)
      pd(i, j) = (gam-one)*(eloc*rod+ro*elocd)
      pd0(i, j) = (gam-one)*(eloc*rod0+ro*elocd0)
      p(i, j) = (gam-one)*ro*eloc
!  p(i,j)  = ro*rgaz*tloc(i,j)
      tempd = wd0(i, j, 5) + pd0(i, j)
      temp = w(i, j, 5) + p(i, j)
      temp3 = wd(i, j, 5) + pd(i, j)
      htotdd = temp3*rom1d0 + rom1*pdd(i, j) + rom1d*tempd + temp*rom1dd
      htotd = rom1*temp3 + temp*rom1d
      htotd0 = rom1*tempd + temp*rom1d0
      fdd(i, j, 1) = 0.0_8
      fdd(i, j, 2) = wd(i, j, 2)*velxd0(i, j) + velxd(i, j)*wd0(i, j, 2)&
&       + w(i, j, 2)*velxdd(i, j) + pdd(i, j)
      fdd(i, j, 3) = wd(i, j, 2)*velyd0(i, j) + velyd(i, j)*wd0(i, j, 2)&
&       + w(i, j, 2)*velydd(i, j)
      fdd(i, j, 4) = wd(i, j, 2)*velzd0(i, j) + velzd(i, j)*wd0(i, j, 2)&
&       + w(i, j, 2)*velzdd(i, j)
      fdd(i, j, 5) = wd(i, j, 2)*htotd0 + htotd*wd0(i, j, 2) + w(i, j, 2&
&       )*htotdd
      gdd(i, j, 1) = 0.0_8
      gdd(i, j, 2) = wd(i, j, 3)*velxd0(i, j) + velxd(i, j)*wd0(i, j, 3)&
&       + w(i, j, 3)*velxdd(i, j)
      gdd(i, j, 3) = wd(i, j, 3)*velyd0(i, j) + velyd(i, j)*wd0(i, j, 3)&
&       + w(i, j, 3)*velydd(i, j) + pdd(i, j)
      gdd(i, j, 4) = wd(i, j, 3)*velzd0(i, j) + velzd(i, j)*wd0(i, j, 3)&
&       + w(i, j, 3)*velzdd(i, j)
      gdd(i, j, 5) = wd(i, j, 3)*htotd0 + htotd*wd0(i, j, 3) + w(i, j, 3&
&       )*htotdd
!h(i,j,1)  = w(i,j,4)
!h(i,j,2)  = w(i,j,4) * velx(i,j)
!h(i,j,3)  = w(i,j,4) * vely(i,j)
!h(i,j,4)  = w(i,j,4) * velz(i,j) + p(i,j)
!h(i,j,5)  = w(i,j,4) * htot
      temp3 = SQRT(tloc(i, j))
      IF (tloc(i, j) .EQ. 0.0) THEN
        tempd = 0.0_8
      ELSE
        tempd = tlocd0(i, j)/(2.0*temp3)
      END IF
      temp = temp3
      IF (tloc(i, j) .EQ. 0.0) THEN
        result1d = 0.0_8
        result1dd = 0.0_8
      ELSE
        temp3 = tlocd(i, j)/(2.0*temp)
        result1dd = (tlocdd(i, j)-temp3*2.0*tempd)/(2.0*temp)
        result1d = temp3
      END IF
      result1d0 = tempd
      result1 = temp
      temp3 = result1*tloc(i, j)/(s_suth+tloc(i, j))
      tempd = (tloc(i, j)*result1d0+(result1-temp3)*tlocd0(i, j))/(&
&       s_suth+tloc(i, j))
      temp = temp3
      temp3 = (tloc(i, j)*result1d+(result1-temp)*tlocd(i, j))/(s_suth+&
&       tloc(i, j))
      mudd(i, j) = betas*((result1d-temp3)*tlocd0(i, j)+tloc(i, j)*&
&       result1dd+tlocd(i, j)*(result1d0-tempd)+(result1-temp)*tlocdd(i&
&       , j))/(s_suth+tloc(i, j))
      mud(i, j) = betas*temp3
      mud0(i, j) = betas*tempd
      mu(i, j) = betas*temp
    END DO
  END DO
  gradud = 0.0_8
  gradvd = 0.0_8
  gradudd = 0.0_8
  gradvdd = 0.0_8
  gradud0 = 0.0_8
  gradvd0 = 0.0_8
  DO j=1,jm
!DIR$ IVDEP
    DO i=1,im
! #include "rhs/gradop_7pi.F"
! #include "rhs/gradop_7pj.F"
!idir
      guidd = b1*(velxdd(i+1, j)-velxdd(i-1, j)) + b2*(velxdd(i+2, j)-&
&       velxdd(i-2, j))
      guid = b1*(velxd(i+1, j)-velxd(i-1, j)) + b2*(velxd(i+2, j)-velxd(&
&       i-2, j))
      guid0 = b1*(velxd0(i+1, j)-velxd0(i-1, j)) + b2*(velxd0(i+2, j)-&
&       velxd0(i-2, j))
      gui = b1*(velx(i+1, j)-velx(i-1, j)) + b2*(velx(i+2, j)-velx(i-2, &
&       j))
      gvidd = b1*(velydd(i+1, j)-velydd(i-1, j)) + b2*(velydd(i+2, j)-&
&       velydd(i-2, j))
      gvid = b1*(velyd(i+1, j)-velyd(i-1, j)) + b2*(velyd(i+2, j)-velyd(&
&       i-2, j))
      gvid0 = b1*(velyd0(i+1, j)-velyd0(i-1, j)) + b2*(velyd0(i+2, j)-&
&       velyd0(i-2, j))
      gvi = b1*(vely(i+1, j)-vely(i-1, j)) + b2*(vely(i+2, j)-vely(i-2, &
&       j))
!jdir
      gujdd = b1*(velxdd(i, j+1)-velxdd(i, j-1)) + b2*(velxdd(i, j+2)-&
&       velxdd(i, j-2))
      gujd = b1*(velxd(i, j+1)-velxd(i, j-1)) + b2*(velxd(i, j+2)-velxd(&
&       i, j-2))
      gujd0 = b1*(velxd0(i, j+1)-velxd0(i, j-1)) + b2*(velxd0(i, j+2)-&
&       velxd0(i, j-2))
      guj = b1*(velx(i, j+1)-velx(i, j-1)) + b2*(velx(i, j+2)-velx(i, j-&
&       2))
      gvjdd = b1*(velydd(i, j+1)-velydd(i, j-1)) + b2*(velydd(i, j+2)-&
&       velydd(i, j-2))
      gvjd = b1*(velyd(i, j+1)-velyd(i, j-1)) + b2*(velyd(i, j+2)-velyd(&
&       i, j-2))
      gvjd0 = b1*(velyd0(i, j+1)-velyd0(i, j-1)) + b2*(velyd0(i, j+2)-&
&       velyd0(i, j-2))
      gvj = b1*(vely(i, j+1)-vely(i, j-1)) + b2*(vely(i, j+2)-vely(i, j-&
&       2))
      volm1 = one/vol(i, j)
      dxm1 = half*(nx(i, j, 1)+nx(i+1, j, 1))*volm1
      dxm2 = half*(nx(i, j, 2)+nx(i, j+1, 2))*volm1
      dym1 = half*(ny(i, j, 1)+ny(i+1, j, 1))*volm1
      dym2 = half*(ny(i, j, 2)+ny(i, j+1, 2))*volm1
      gradudd(i, j, 1) = dxm1*guidd + dxm2*gujdd
      gradud(i, j, 1) = dxm1*guid + dxm2*gujd
      gradud0(i, j, 1) = dxm1*guid0 + dxm2*gujd0
      gradu(i, j, 1) = dxm1*gui + dxm2*guj
      gradvdd(i, j, 1) = dxm1*gvidd + dxm2*gvjdd
      gradvd(i, j, 1) = dxm1*gvid + dxm2*gvjd
      gradvd0(i, j, 1) = dxm1*gvid0 + dxm2*gvjd0
      gradv(i, j, 1) = dxm1*gvi + dxm2*gvj
      gradudd(i, j, 2) = dym1*guidd + dym2*gujdd
      gradud(i, j, 2) = dym1*guid + dym2*gujd
      gradud0(i, j, 2) = dym1*guid0 + dym2*gujd0
      gradu(i, j, 2) = dym1*gui + dym2*guj
      gradvdd(i, j, 2) = dym1*gvidd + dym2*gvjdd
      gradvd(i, j, 2) = dym1*gvid + dym2*gvjd
      gradvd0(i, j, 2) = dym1*gvid0 + dym2*gvjd0
      gradv(i, j, 2) = dym1*gvi + dym2*gvj
    END DO
  END DO
!
! trick for ducros in dissipation
  DO i=1,2
    DO h=1,gh
      gradudd(:, 1-h, :) = two*gradudd(:, 2-h, :) - gradudd(:, 3-h, :)
      gradud(:, 1-h, :) = two*gradud(:, 2-h, :) - gradud(:, 3-h, :)
      gradud0(:, 1-h, :) = two*gradud0(:, 2-h, :) - gradud0(:, 3-h, :)
      gradu(:, 1-h, :) = two*gradu(:, 2-h, :) - gradu(:, 3-h, :)
      gradvdd(:, 1-h, :) = two*gradvdd(:, 2-h, :) - gradvdd(:, 3-h, :)
      gradvd(:, 1-h, :) = two*gradvd(:, 2-h, :) - gradvd(:, 3-h, :)
      gradvd0(:, 1-h, :) = two*gradvd0(:, 2-h, :) - gradvd0(:, 3-h, :)
      gradv(:, 1-h, :) = two*gradv(:, 2-h, :) - gradv(:, 3-h, :)
      gradudd(:, jm+h, :) = two*gradudd(:, jm-1+h, :) - gradudd(:, jm-2+&
&       h, :)
      gradud(:, jm+h, :) = two*gradud(:, jm-1+h, :) - gradud(:, jm-2+h, &
&       :)
      gradud0(:, jm+h, :) = two*gradud0(:, jm-1+h, :) - gradud0(:, jm-2+&
&       h, :)
      gradu(:, jm+h, :) = two*gradu(:, jm-1+h, :) - gradu(:, jm-2+h, :)
      gradvdd(:, jm+h, :) = two*gradvdd(:, jm-1+h, :) - gradvdd(:, jm-2+&
&       h, :)
      gradvd(:, jm+h, :) = two*gradvd(:, jm-1+h, :) - gradvd(:, jm-2+h, &
&       :)
      gradvd0(:, jm+h, :) = two*gradvd0(:, jm-1+h, :) - gradvd0(:, jm-2+&
&       h, :)
      gradv(:, jm+h, :) = two*gradv(:, jm-1+h, :) - gradv(:, jm-2+h, :)
      gradudd(1-h, :, :) = two*gradudd(2-h, :, :) - gradudd(3-h, :, :)
      gradud(1-h, :, :) = two*gradud(2-h, :, :) - gradud(3-h, :, :)
      gradud0(1-h, :, :) = two*gradud0(2-h, :, :) - gradud0(3-h, :, :)
      gradu(1-h, :, :) = two*gradu(2-h, :, :) - gradu(3-h, :, :)
      gradvdd(1-h, :, :) = two*gradvdd(2-h, :, :) - gradvdd(3-h, :, :)
      gradvd(1-h, :, :) = two*gradvd(2-h, :, :) - gradvd(3-h, :, :)
      gradvd0(1-h, :, :) = two*gradvd0(2-h, :, :) - gradvd0(3-h, :, :)
      gradv(1-h, :, :) = two*gradv(2-h, :, :) - gradv(3-h, :, :)
      gradudd(im+h, :, :) = two*gradudd(im-1+h, :, :) - gradudd(im-2+h, &
&       :, :)
      gradud(im+h, :, :) = two*gradud(im-1+h, :, :) - gradud(im-2+h, :, &
&       :)
      gradud0(im+h, :, :) = two*gradud0(im-1+h, :, :) - gradud0(im-2+h, &
&       :, :)
      gradu(im+h, :, :) = two*gradu(im-1+h, :, :) - gradu(im-2+h, :, :)
      gradvdd(im+h, :, :) = two*gradvdd(im-1+h, :, :) - gradvdd(im-2+h, &
&       :, :)
      gradvd(im+h, :, :) = two*gradvd(im-1+h, :, :) - gradvd(im-2+h, :, &
&       :)
      gradvd0(im+h, :, :) = two*gradvd0(im-1+h, :, :) - gradvd0(im-2+h, &
&       :, :)
      gradv(im+h, :, :) = two*gradv(im-1+h, :, :) - gradv(im-2+h, :, :)
    END DO
  END DO
  eps2arrad = 0.0_8
  eps2arradd = 0.0_8
  hndd = 0.0_8
  eps2arrad0 = 0.0_8
  DO j=1,jm+1
!DIR$ IVDEP
    DO i=1,im+1
!
      fxro1dd = nx(i, j, 1)*(c1*(fdd(i, j, 1)+fdd(i-1, j, 1))+c2*(fdd(i+&
&       1, j, 1)+fdd(i-2, j, 1))+c3*(fdd(i+2, j, 1)+fdd(i-3, j, 1))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 1)+gdd(i-1, j, 1))+c2*(gdd(i+1, j, 1)&
&       +gdd(i-2, j, 1))+c3*(gdd(i+2, j, 1)+gdd(i-3, j, 1)))
      fxrou1dd = nx(i, j, 1)*(c1*(fdd(i, j, 2)+fdd(i-1, j, 2))+c2*(fdd(i&
&       +1, j, 2)+fdd(i-2, j, 2))+c3*(fdd(i+2, j, 2)+fdd(i-3, j, 2))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 2)+gdd(i-1, j, 2))+c2*(gdd(i+1, j, 2)&
&       +gdd(i-2, j, 2))+c3*(gdd(i+2, j, 2)+gdd(i-3, j, 2)))
      fxrov1dd = nx(i, j, 1)*(c1*(fdd(i, j, 3)+fdd(i-1, j, 3))+c2*(fdd(i&
&       +1, j, 3)+fdd(i-2, j, 3))+c3*(fdd(i+2, j, 3)+fdd(i-3, j, 3))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 3)+gdd(i-1, j, 3))+c2*(gdd(i+1, j, 3)&
&       +gdd(i-2, j, 3))+c3*(gdd(i+2, j, 3)+gdd(i-3, j, 3)))
      fxrow1dd = nx(i, j, 1)*(c1*(fdd(i, j, 4)+fdd(i-1, j, 4))+c2*(fdd(i&
&       +1, j, 4)+fdd(i-2, j, 4))+c3*(fdd(i+2, j, 4)+fdd(i-3, j, 4))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 4)+gdd(i-1, j, 4))+c2*(gdd(i+1, j, 4)&
&       +gdd(i-2, j, 4))+c3*(gdd(i+2, j, 4)+gdd(i-3, j, 4)))
      fxroe1dd = nx(i, j, 1)*(c1*(fdd(i, j, 5)+fdd(i-1, j, 5))+c2*(fdd(i&
&       +1, j, 5)+fdd(i-2, j, 5))+c3*(fdd(i+2, j, 5)+fdd(i-3, j, 5))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 5)+gdd(i-1, j, 5))+c2*(gdd(i+1, j, 5)&
&       +gdd(i-2, j, 5))+c3*(gdd(i+2, j, 5)+gdd(i-3, j, 5)))
      fxro2dd = nx(i, j, 2)*(c1*(fdd(i, j, 1)+fdd(i, j-1, 1))+c2*(fdd(i&
&       , j+1, 1)+fdd(i, j-2, 1))+c3*(fdd(i, j+2, 1)+fdd(i, j-3, 1))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 1)+gdd(i, j-1, 1))+c2*(gdd(i, j+1, 1)&
&       +gdd(i, j-2, 1))+c3*(gdd(i, j+2, 1)+gdd(i, j-3, 1)))
      fxrou2dd = nx(i, j, 2)*(c1*(fdd(i, j, 2)+fdd(i, j-1, 2))+c2*(fdd(i&
&       , j+1, 2)+fdd(i, j-2, 2))+c3*(fdd(i, j+2, 2)+fdd(i, j-3, 2))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 2)+gdd(i, j-1, 2))+c2*(gdd(i, j+1, 2)&
&       +gdd(i, j-2, 2))+c3*(gdd(i, j+2, 2)+gdd(i, j-3, 2)))
      fxrov2dd = nx(i, j, 2)*(c1*(fdd(i, j, 3)+fdd(i, j-1, 3))+c2*(fdd(i&
&       , j+1, 3)+fdd(i, j-2, 3))+c3*(fdd(i, j+2, 3)+fdd(i, j-3, 3))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 3)+gdd(i, j-1, 3))+c2*(gdd(i, j+1, 3)&
&       +gdd(i, j-2, 3))+c3*(gdd(i, j+2, 3)+gdd(i, j-3, 3)))
      fxrow2dd = nx(i, j, 2)*(c1*(fdd(i, j, 4)+fdd(i, j-1, 4))+c2*(fdd(i&
&       , j+1, 4)+fdd(i, j-2, 4))+c3*(fdd(i, j+2, 4)+fdd(i, j-3, 4))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 4)+gdd(i, j-1, 4))+c2*(gdd(i, j+1, 4)&
&       +gdd(i, j-2, 4))+c3*(gdd(i, j+2, 4)+gdd(i, j-3, 4)))
      fxroe2dd = nx(i, j, 2)*(c1*(fdd(i, j, 5)+fdd(i, j-1, 5))+c2*(fdd(i&
&       , j+1, 5)+fdd(i, j-2, 5))+c3*(fdd(i, j+2, 5)+fdd(i, j-3, 5))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 5)+gdd(i, j-1, 5))+c2*(gdd(i, j+1, 5)&
&       +gdd(i, j-2, 5))+c3*(gdd(i, j+2, 5)+gdd(i, j-3, 5)))
      predro1d = d2*wd(i-2, j, 1) - d3*wd(i-3, j, 1) - d1*wd(i-1, j, 1) &
&       + d1*wd(i, j, 1) - d2*wd(i+1, j, 1) + d3*wd(i+2, j, 1)
      predro1d0 = d2*wd0(i-2, j, 1) - d3*wd0(i-3, j, 1) - d1*wd0(i-1, j&
&       , 1) + d1*wd0(i, j, 1) - d2*wd0(i+1, j, 1) + d3*wd0(i+2, j, 1)
      predro1 = -(d3*w(i-3, j, 1)) + d2*w(i-2, j, 1) - d1*w(i-1, j, 1) +&
&       d1*w(i, j, 1) - d2*w(i+1, j, 1) + d3*w(i+2, j, 1)
      predrou1d = d2*wd(i-2, j, 2) - d3*wd(i-3, j, 2) - d1*wd(i-1, j, 2)&
&       + d1*wd(i, j, 2) - d2*wd(i+1, j, 2) + d3*wd(i+2, j, 2)
      predrou1d0 = d2*wd0(i-2, j, 2) - d3*wd0(i-3, j, 2) - d1*wd0(i-1, j&
&       , 2) + d1*wd0(i, j, 2) - d2*wd0(i+1, j, 2) + d3*wd0(i+2, j, 2)
      predrou1 = -(d3*w(i-3, j, 2)) + d2*w(i-2, j, 2) - d1*w(i-1, j, 2) &
&       + d1*w(i, j, 2) - d2*w(i+1, j, 2) + d3*w(i+2, j, 2)
      predrov1d = d2*wd(i-2, j, 3) - d3*wd(i-3, j, 3) - d1*wd(i-1, j, 3)&
&       + d1*wd(i, j, 3) - d2*wd(i+1, j, 3) + d3*wd(i+2, j, 3)
      predrov1d0 = d2*wd0(i-2, j, 3) - d3*wd0(i-3, j, 3) - d1*wd0(i-1, j&
&       , 3) + d1*wd0(i, j, 3) - d2*wd0(i+1, j, 3) + d3*wd0(i+2, j, 3)
      predrov1 = -(d3*w(i-3, j, 3)) + d2*w(i-2, j, 3) - d1*w(i-1, j, 3) &
&       + d1*w(i, j, 3) - d2*w(i+1, j, 3) + d3*w(i+2, j, 3)
      predrow1d = d2*wd(i-2, j, 4) - d3*wd(i-3, j, 4) - d1*wd(i-1, j, 4)&
&       + d1*wd(i, j, 4) - d2*wd(i+1, j, 4) + d3*wd(i+2, j, 4)
      predrow1d0 = d2*wd0(i-2, j, 4) - d3*wd0(i-3, j, 4) - d1*wd0(i-1, j&
&       , 4) + d1*wd0(i, j, 4) - d2*wd0(i+1, j, 4) + d3*wd0(i+2, j, 4)
      predrow1 = -(d3*w(i-3, j, 4)) + d2*w(i-2, j, 4) - d1*w(i-1, j, 4) &
&       + d1*w(i, j, 4) - d2*w(i+1, j, 4) + d3*w(i+2, j, 4)
      predroe1d = d2*wd(i-2, j, 5) - d3*wd(i-3, j, 5) - d1*wd(i-1, j, 5)&
&       + d1*wd(i, j, 5) - d2*wd(i+1, j, 5) + d3*wd(i+2, j, 5)
      predroe1d0 = d2*wd0(i-2, j, 5) - d3*wd0(i-3, j, 5) - d1*wd0(i-1, j&
&       , 5) + d1*wd0(i, j, 5) - d2*wd0(i+1, j, 5) + d3*wd0(i+2, j, 5)
      predroe1 = -(d3*w(i-3, j, 5)) + d2*w(i-2, j, 5) - d1*w(i-1, j, 5) &
&       + d1*w(i, j, 5) - d2*w(i+1, j, 5) + d3*w(i+2, j, 5)
      predro2d = d2*wd(i, j-2, 1) - d3*wd(i, j-3, 1) - d1*wd(i, j-1, 1) &
&       + d1*wd(i, j, 1) - d2*wd(i, j+1, 1) + d3*wd(i, j+2, 1)
      predro2d0 = d2*wd0(i, j-2, 1) - d3*wd0(i, j-3, 1) - d1*wd0(i, j-1&
&       , 1) + d1*wd0(i, j, 1) - d2*wd0(i, j+1, 1) + d3*wd0(i, j+2, 1)
      predro2 = -(d3*w(i, j-3, 1)) + d2*w(i, j-2, 1) - d1*w(i, j-1, 1) +&
&       d1*w(i, j, 1) - d2*w(i, j+1, 1) + d3*w(i, j+2, 1)
      predrou2d = d2*wd(i, j-2, 2) - d3*wd(i, j-3, 2) - d1*wd(i, j-1, 2)&
&       + d1*wd(i, j, 2) - d2*wd(i, j+1, 2) + d3*wd(i, j+2, 2)
      predrou2d0 = d2*wd0(i, j-2, 2) - d3*wd0(i, j-3, 2) - d1*wd0(i, j-1&
&       , 2) + d1*wd0(i, j, 2) - d2*wd0(i, j+1, 2) + d3*wd0(i, j+2, 2)
      predrou2 = -(d3*w(i, j-3, 2)) + d2*w(i, j-2, 2) - d1*w(i, j-1, 2) &
&       + d1*w(i, j, 2) - d2*w(i, j+1, 2) + d3*w(i, j+2, 2)
      predrov2d = d2*wd(i, j-2, 3) - d3*wd(i, j-3, 3) - d1*wd(i, j-1, 3)&
&       + d1*wd(i, j, 3) - d2*wd(i, j+1, 3) + d3*wd(i, j+2, 3)
      predrov2d0 = d2*wd0(i, j-2, 3) - d3*wd0(i, j-3, 3) - d1*wd0(i, j-1&
&       , 3) + d1*wd0(i, j, 3) - d2*wd0(i, j+1, 3) + d3*wd0(i, j+2, 3)
      predrov2 = -(d3*w(i, j-3, 3)) + d2*w(i, j-2, 3) - d1*w(i, j-1, 3) &
&       + d1*w(i, j, 3) - d2*w(i, j+1, 3) + d3*w(i, j+2, 3)
      predrow2d = d2*wd(i, j-2, 4) - d3*wd(i, j-3, 4) - d1*wd(i, j-1, 4)&
&       + d1*wd(i, j, 4) - d2*wd(i, j+1, 4) + d3*wd(i, j+2, 4)
      predrow2d0 = d2*wd0(i, j-2, 4) - d3*wd0(i, j-3, 4) - d1*wd0(i, j-1&
&       , 4) + d1*wd0(i, j, 4) - d2*wd0(i, j+1, 4) + d3*wd0(i, j+2, 4)
      predrow2 = -(d3*w(i, j-3, 4)) + d2*w(i, j-2, 4) - d1*w(i, j-1, 4) &
&       + d1*w(i, j, 4) - d2*w(i, j+1, 4) + d3*w(i, j+2, 4)
      predroe2d = d2*wd(i, j-2, 5) - d3*wd(i, j-3, 5) - d1*wd(i, j-1, 5)&
&       + d1*wd(i, j, 5) - d2*wd(i, j+1, 5) + d3*wd(i, j+2, 5)
      predroe2d0 = d2*wd0(i, j-2, 5) - d3*wd0(i, j-3, 5) - d1*wd0(i, j-1&
&       , 5) + d1*wd0(i, j, 5) - d2*wd0(i, j+1, 5) + d3*wd0(i, j+2, 5)
      predroe2 = -(d3*w(i, j-3, 5)) + d2*w(i, j-2, 5) - d1*w(i, j-1, 5) &
&       + d1*w(i, j, 5) - d2*w(i, j+1, 5) + d3*w(i, j+2, 5)
! grad for viscous fluxes o4 - 5p
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccros = TWELFTH*0.0625d0
      volm1 = volf(i, j, 1)
      nx_n = half*(nx(i+1, j, 1)+nx(i, j, 1))
      nx_s = -(half*(nx(i-1, j, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i-1, j+1, 2)+nx(i, j+1, 2))
      nx_e = -(half*(nx(i-1, j, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j, 1)+ny(i, j, 1))
      ny_s = -(half*(ny(i-1, j, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i-1, j+1, 2)+ny(i, j+1, 2))
      ny_e = -(half*(ny(i-1, j, 2)+ny(i, j, 2)))
      val_ndd = twentyfourth*(26.d0*velxdd(i, j)-velxdd(i+1, j)-velxdd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*velxd(i, j)-velxd(i+1, j)-velxd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*velxd0(i, j)-velxd0(i+1, j)-velxd0(i&
&       -1, j))
      val_n = twentyfourth*(-velx(i+1, j)+26.d0*velx(i, j)-velx(i-1, j))
      val_sdd = twentyfourth*(26.d0*velxdd(i-1, j)-velxdd(i, j)-velxdd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*velxd(i-1, j)-velxd(i, j)-velxd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*velxd0(i-1, j)-velxd0(i, j)-velxd0(i&
&       -2, j))
      val_s = twentyfourth*(-velx(i, j)+26.d0*velx(i-1, j)-velx(i-2, j))
      val_edd = ccross*(velxdd(i-2, j-2)-9.d0*velxdd(i-1, j-2)-9.d0*&
&       velxdd(i, j-2)+velxdd(i+1, j-2)+7.d0*(9.d0*velxdd(i-1, j-1)-&
&       velxdd(i-2, j-1)+9.d0*velxdd(i, j-1)-velxdd(i+1, j-1))+7.d0*(&
&       9.d0*velxdd(i-1, j)-velxdd(i-2, j)+9.d0*velxdd(i, j)-velxdd(i+1&
&       , j))+velxdd(i-2, j+1)-9.d0*velxdd(i-1, j+1)+velxdd(i+1, j+1)-&
&       9.d0*velxdd(i, j+1))
      val_ed = ccross*(velxd(i-2, j-2)-9.d0*velxd(i-1, j-2)-9.d0*velxd(i&
&       , j-2)+velxd(i+1, j-2)+7.d0*(9.d0*velxd(i-1, j-1)-velxd(i-2, j-1&
&       )+9.d0*velxd(i, j-1)-velxd(i+1, j-1))+7.d0*(9.d0*velxd(i-1, j)-&
&       velxd(i-2, j)+9.d0*velxd(i, j)-velxd(i+1, j))+velxd(i-2, j+1)-&
&       9.d0*velxd(i-1, j+1)+velxd(i+1, j+1)-9.d0*velxd(i, j+1))
      val_ed0 = ccross*(velxd0(i-2, j-2)-9.d0*velxd0(i-1, j-2)-9.d0*&
&       velxd0(i, j-2)+velxd0(i+1, j-2)+7.d0*(9.d0*velxd0(i-1, j-1)-&
&       velxd0(i-2, j-1)+9.d0*velxd0(i, j-1)-velxd0(i+1, j-1))+7.d0*(&
&       9.d0*velxd0(i-1, j)-velxd0(i-2, j)+9.d0*velxd0(i, j)-velxd0(i+1&
&       , j))+velxd0(i-2, j+1)-9.d0*velxd0(i-1, j+1)+velxd0(i+1, j+1)-&
&       9.d0*velxd0(i, j+1))
      val_e = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-1, j-2)+9.d0*velx(i&
&       , j-2)-velx(i+1, j-2))+7.d0*(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)&
&       +9.d0*velx(i, j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx&
&       (i-1, j)+9.d0*velx(i, j)-velx(i+1, j))-(-velx(i-2, j+1)+9.d0*&
&       velx(i-1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1)))
      val_odd = ccross*(velxdd(i-2, j-1)-9.d0*velxdd(i-1, j-1)-9.d0*&
&       velxdd(i, j-1)+velxdd(i+1, j-1)+7.d0*(9.d0*velxdd(i-1, j)-velxdd&
&       (i-2, j)+9.d0*velxdd(i, j)-velxdd(i+1, j))+7.d0*(9.d0*velxdd(i-1&
&       , j+1)-velxdd(i-2, j+1)+9.d0*velxdd(i, j+1)-velxdd(i+1, j+1))+&
&       velxdd(i-2, j+2)-9.d0*velxdd(i-1, j+2)+velxdd(i+1, j+2)-9.d0*&
&       velxdd(i, j+2))
      val_od = ccross*(velxd(i-2, j-1)-9.d0*velxd(i-1, j-1)-9.d0*velxd(i&
&       , j-1)+velxd(i+1, j-1)+7.d0*(9.d0*velxd(i-1, j)-velxd(i-2, j)+&
&       9.d0*velxd(i, j)-velxd(i+1, j))+7.d0*(9.d0*velxd(i-1, j+1)-velxd&
&       (i-2, j+1)+9.d0*velxd(i, j+1)-velxd(i+1, j+1))+velxd(i-2, j+2)-&
&       9.d0*velxd(i-1, j+2)+velxd(i+1, j+2)-9.d0*velxd(i, j+2))
      val_od0 = ccross*(velxd0(i-2, j-1)-9.d0*velxd0(i-1, j-1)-9.d0*&
&       velxd0(i, j-1)+velxd0(i+1, j-1)+7.d0*(9.d0*velxd0(i-1, j)-velxd0&
&       (i-2, j)+9.d0*velxd0(i, j)-velxd0(i+1, j))+7.d0*(9.d0*velxd0(i-1&
&       , j+1)-velxd0(i-2, j+1)+9.d0*velxd0(i, j+1)-velxd0(i+1, j+1))+&
&       velxd0(i-2, j+2)-9.d0*velxd0(i-1, j+2)+velxd0(i+1, j+2)-9.d0*&
&       velxd0(i, j+2))
      val_o = ccross*(-(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)+9.d0*velx(i&
&       , j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+&
&       9.d0*velx(i, j)-velx(i+1, j))+7.d0*(-velx(i-2, j+1)+9.d0*velx(i-&
&       1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1))-(-velx(i-2, j+2)+9.d0*&
&       velx(i-1, j+2)+9.d0*velx(i, j+2)-velx(i+1, j+2)))
      uxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      uxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      uxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      uyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      uyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = twentyfourth*(26.d0*velydd(i, j)-velydd(i+1, j)-velydd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*velyd(i, j)-velyd(i+1, j)-velyd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*velyd0(i, j)-velyd0(i+1, j)-velyd0(i&
&       -1, j))
      val_n = twentyfourth*(-vely(i+1, j)+26.d0*vely(i, j)-vely(i-1, j))
      val_sdd = twentyfourth*(26.d0*velydd(i-1, j)-velydd(i, j)-velydd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*velyd(i-1, j)-velyd(i, j)-velyd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*velyd0(i-1, j)-velyd0(i, j)-velyd0(i&
&       -2, j))
      val_s = twentyfourth*(-vely(i, j)+26.d0*vely(i-1, j)-vely(i-2, j))
      val_edd = ccross*(velydd(i-2, j-2)-9.d0*velydd(i-1, j-2)-9.d0*&
&       velydd(i, j-2)+velydd(i+1, j-2)+7.d0*(9.d0*velydd(i-1, j-1)-&
&       velydd(i-2, j-1)+9.d0*velydd(i, j-1)-velydd(i+1, j-1))+7.d0*(&
&       9.d0*velydd(i-1, j)-velydd(i-2, j)+9.d0*velydd(i, j)-velydd(i+1&
&       , j))+velydd(i-2, j+1)-9.d0*velydd(i-1, j+1)+velydd(i+1, j+1)-&
&       9.d0*velydd(i, j+1))
      val_ed = ccross*(velyd(i-2, j-2)-9.d0*velyd(i-1, j-2)-9.d0*velyd(i&
&       , j-2)+velyd(i+1, j-2)+7.d0*(9.d0*velyd(i-1, j-1)-velyd(i-2, j-1&
&       )+9.d0*velyd(i, j-1)-velyd(i+1, j-1))+7.d0*(9.d0*velyd(i-1, j)-&
&       velyd(i-2, j)+9.d0*velyd(i, j)-velyd(i+1, j))+velyd(i-2, j+1)-&
&       9.d0*velyd(i-1, j+1)+velyd(i+1, j+1)-9.d0*velyd(i, j+1))
      val_ed0 = ccross*(velyd0(i-2, j-2)-9.d0*velyd0(i-1, j-2)-9.d0*&
&       velyd0(i, j-2)+velyd0(i+1, j-2)+7.d0*(9.d0*velyd0(i-1, j-1)-&
&       velyd0(i-2, j-1)+9.d0*velyd0(i, j-1)-velyd0(i+1, j-1))+7.d0*(&
&       9.d0*velyd0(i-1, j)-velyd0(i-2, j)+9.d0*velyd0(i, j)-velyd0(i+1&
&       , j))+velyd0(i-2, j+1)-9.d0*velyd0(i-1, j+1)+velyd0(i+1, j+1)-&
&       9.d0*velyd0(i, j+1))
      val_e = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-1, j-2)+9.d0*vely(i&
&       , j-2)-vely(i+1, j-2))+7.d0*(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)&
&       +9.d0*vely(i, j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely&
&       (i-1, j)+9.d0*vely(i, j)-vely(i+1, j))-(-vely(i-2, j+1)+9.d0*&
&       vely(i-1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1)))
      val_odd = ccross*(velydd(i-2, j-1)-9.d0*velydd(i-1, j-1)-9.d0*&
&       velydd(i, j-1)+velydd(i+1, j-1)+7.d0*(9.d0*velydd(i-1, j)-velydd&
&       (i-2, j)+9.d0*velydd(i, j)-velydd(i+1, j))+7.d0*(9.d0*velydd(i-1&
&       , j+1)-velydd(i-2, j+1)+9.d0*velydd(i, j+1)-velydd(i+1, j+1))+&
&       velydd(i-2, j+2)-9.d0*velydd(i-1, j+2)+velydd(i+1, j+2)-9.d0*&
&       velydd(i, j+2))
      val_od = ccross*(velyd(i-2, j-1)-9.d0*velyd(i-1, j-1)-9.d0*velyd(i&
&       , j-1)+velyd(i+1, j-1)+7.d0*(9.d0*velyd(i-1, j)-velyd(i-2, j)+&
&       9.d0*velyd(i, j)-velyd(i+1, j))+7.d0*(9.d0*velyd(i-1, j+1)-velyd&
&       (i-2, j+1)+9.d0*velyd(i, j+1)-velyd(i+1, j+1))+velyd(i-2, j+2)-&
&       9.d0*velyd(i-1, j+2)+velyd(i+1, j+2)-9.d0*velyd(i, j+2))
      val_od0 = ccross*(velyd0(i-2, j-1)-9.d0*velyd0(i-1, j-1)-9.d0*&
&       velyd0(i, j-1)+velyd0(i+1, j-1)+7.d0*(9.d0*velyd0(i-1, j)-velyd0&
&       (i-2, j)+9.d0*velyd0(i, j)-velyd0(i+1, j))+7.d0*(9.d0*velyd0(i-1&
&       , j+1)-velyd0(i-2, j+1)+9.d0*velyd0(i, j+1)-velyd0(i+1, j+1))+&
&       velyd0(i-2, j+2)-9.d0*velyd0(i-1, j+2)+velyd0(i+1, j+2)-9.d0*&
&       velyd0(i, j+2))
      val_o = ccross*(-(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)+9.d0*vely(i&
&       , j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+&
&       9.d0*vely(i, j)-vely(i+1, j))+7.d0*(-vely(i-2, j+1)+9.d0*vely(i-&
&       1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1))-(-vely(i-2, j+2)+9.d0*&
&       vely(i-1, j+2)+9.d0*vely(i, j+2)-vely(i+1, j+2)))
      vxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      vxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      vxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      vyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      vyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = twentyfourth*(26.d0*velzdd(i, j)-velzdd(i+1, j)-velzdd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*velzd(i, j)-velzd(i+1, j)-velzd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*velzd0(i, j)-velzd0(i+1, j)-velzd0(i&
&       -1, j))
      val_n = twentyfourth*(-velz(i+1, j)+26.d0*velz(i, j)-velz(i-1, j))
      val_sdd = twentyfourth*(26.d0*velzdd(i-1, j)-velzdd(i, j)-velzdd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*velzd(i-1, j)-velzd(i, j)-velzd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*velzd0(i-1, j)-velzd0(i, j)-velzd0(i&
&       -2, j))
      val_s = twentyfourth*(-velz(i, j)+26.d0*velz(i-1, j)-velz(i-2, j))
      val_edd = ccross*(velzdd(i-2, j-2)-9.d0*velzdd(i-1, j-2)-9.d0*&
&       velzdd(i, j-2)+velzdd(i+1, j-2)+7.d0*(9.d0*velzdd(i-1, j-1)-&
&       velzdd(i-2, j-1)+9.d0*velzdd(i, j-1)-velzdd(i+1, j-1))+7.d0*(&
&       9.d0*velzdd(i-1, j)-velzdd(i-2, j)+9.d0*velzdd(i, j)-velzdd(i+1&
&       , j))+velzdd(i-2, j+1)-9.d0*velzdd(i-1, j+1)+velzdd(i+1, j+1)-&
&       9.d0*velzdd(i, j+1))
      val_ed = ccross*(velzd(i-2, j-2)-9.d0*velzd(i-1, j-2)-9.d0*velzd(i&
&       , j-2)+velzd(i+1, j-2)+7.d0*(9.d0*velzd(i-1, j-1)-velzd(i-2, j-1&
&       )+9.d0*velzd(i, j-1)-velzd(i+1, j-1))+7.d0*(9.d0*velzd(i-1, j)-&
&       velzd(i-2, j)+9.d0*velzd(i, j)-velzd(i+1, j))+velzd(i-2, j+1)-&
&       9.d0*velzd(i-1, j+1)+velzd(i+1, j+1)-9.d0*velzd(i, j+1))
      val_ed0 = ccross*(velzd0(i-2, j-2)-9.d0*velzd0(i-1, j-2)-9.d0*&
&       velzd0(i, j-2)+velzd0(i+1, j-2)+7.d0*(9.d0*velzd0(i-1, j-1)-&
&       velzd0(i-2, j-1)+9.d0*velzd0(i, j-1)-velzd0(i+1, j-1))+7.d0*(&
&       9.d0*velzd0(i-1, j)-velzd0(i-2, j)+9.d0*velzd0(i, j)-velzd0(i+1&
&       , j))+velzd0(i-2, j+1)-9.d0*velzd0(i-1, j+1)+velzd0(i+1, j+1)-&
&       9.d0*velzd0(i, j+1))
      val_e = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-1, j-2)+9.d0*velz(i&
&       , j-2)-velz(i+1, j-2))+7.d0*(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)&
&       +9.d0*velz(i, j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz&
&       (i-1, j)+9.d0*velz(i, j)-velz(i+1, j))-(-velz(i-2, j+1)+9.d0*&
&       velz(i-1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1)))
      val_odd = ccross*(velzdd(i-2, j-1)-9.d0*velzdd(i-1, j-1)-9.d0*&
&       velzdd(i, j-1)+velzdd(i+1, j-1)+7.d0*(9.d0*velzdd(i-1, j)-velzdd&
&       (i-2, j)+9.d0*velzdd(i, j)-velzdd(i+1, j))+7.d0*(9.d0*velzdd(i-1&
&       , j+1)-velzdd(i-2, j+1)+9.d0*velzdd(i, j+1)-velzdd(i+1, j+1))+&
&       velzdd(i-2, j+2)-9.d0*velzdd(i-1, j+2)+velzdd(i+1, j+2)-9.d0*&
&       velzdd(i, j+2))
      val_od = ccross*(velzd(i-2, j-1)-9.d0*velzd(i-1, j-1)-9.d0*velzd(i&
&       , j-1)+velzd(i+1, j-1)+7.d0*(9.d0*velzd(i-1, j)-velzd(i-2, j)+&
&       9.d0*velzd(i, j)-velzd(i+1, j))+7.d0*(9.d0*velzd(i-1, j+1)-velzd&
&       (i-2, j+1)+9.d0*velzd(i, j+1)-velzd(i+1, j+1))+velzd(i-2, j+2)-&
&       9.d0*velzd(i-1, j+2)+velzd(i+1, j+2)-9.d0*velzd(i, j+2))
      val_od0 = ccross*(velzd0(i-2, j-1)-9.d0*velzd0(i-1, j-1)-9.d0*&
&       velzd0(i, j-1)+velzd0(i+1, j-1)+7.d0*(9.d0*velzd0(i-1, j)-velzd0&
&       (i-2, j)+9.d0*velzd0(i, j)-velzd0(i+1, j))+7.d0*(9.d0*velzd0(i-1&
&       , j+1)-velzd0(i-2, j+1)+9.d0*velzd0(i, j+1)-velzd0(i+1, j+1))+&
&       velzd0(i-2, j+2)-9.d0*velzd0(i-1, j+2)+velzd0(i+1, j+2)-9.d0*&
&       velzd0(i, j+2))
      val_o = ccross*(-(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)+9.d0*velz(i&
&       , j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+&
&       9.d0*velz(i, j)-velz(i+1, j))+7.d0*(-velz(i-2, j+1)+9.d0*velz(i-&
&       1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1))-(-velz(i-2, j+2)+9.d0*&
&       velz(i-1, j+2)+9.d0*velz(i, j+2)-velz(i+1, j+2)))
      wxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      wxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      wxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      wyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      wyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = twentyfourth*(26.d0*tlocdd(i, j)-tlocdd(i+1, j)-tlocdd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*tlocd(i, j)-tlocd(i+1, j)-tlocd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*tlocd0(i, j)-tlocd0(i+1, j)-tlocd0(i&
&       -1, j))
      val_n = twentyfourth*(-tloc(i+1, j)+26.d0*tloc(i, j)-tloc(i-1, j))
      val_sdd = twentyfourth*(26.d0*tlocdd(i-1, j)-tlocdd(i, j)-tlocdd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*tlocd(i-1, j)-tlocd(i, j)-tlocd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*tlocd0(i-1, j)-tlocd0(i, j)-tlocd0(i&
&       -2, j))
      val_s = twentyfourth*(-tloc(i, j)+26.d0*tloc(i-1, j)-tloc(i-2, j))
      val_edd = ccross*(tlocdd(i-2, j-2)-9.d0*tlocdd(i-1, j-2)-9.d0*&
&       tlocdd(i, j-2)+tlocdd(i+1, j-2)+7.d0*(9.d0*tlocdd(i-1, j-1)-&
&       tlocdd(i-2, j-1)+9.d0*tlocdd(i, j-1)-tlocdd(i+1, j-1))+7.d0*(&
&       9.d0*tlocdd(i-1, j)-tlocdd(i-2, j)+9.d0*tlocdd(i, j)-tlocdd(i+1&
&       , j))+tlocdd(i-2, j+1)-9.d0*tlocdd(i-1, j+1)+tlocdd(i+1, j+1)-&
&       9.d0*tlocdd(i, j+1))
      val_ed = ccross*(tlocd(i-2, j-2)-9.d0*tlocd(i-1, j-2)-9.d0*tlocd(i&
&       , j-2)+tlocd(i+1, j-2)+7.d0*(9.d0*tlocd(i-1, j-1)-tlocd(i-2, j-1&
&       )+9.d0*tlocd(i, j-1)-tlocd(i+1, j-1))+7.d0*(9.d0*tlocd(i-1, j)-&
&       tlocd(i-2, j)+9.d0*tlocd(i, j)-tlocd(i+1, j))+tlocd(i-2, j+1)-&
&       9.d0*tlocd(i-1, j+1)+tlocd(i+1, j+1)-9.d0*tlocd(i, j+1))
      val_ed0 = ccross*(tlocd0(i-2, j-2)-9.d0*tlocd0(i-1, j-2)-9.d0*&
&       tlocd0(i, j-2)+tlocd0(i+1, j-2)+7.d0*(9.d0*tlocd0(i-1, j-1)-&
&       tlocd0(i-2, j-1)+9.d0*tlocd0(i, j-1)-tlocd0(i+1, j-1))+7.d0*(&
&       9.d0*tlocd0(i-1, j)-tlocd0(i-2, j)+9.d0*tlocd0(i, j)-tlocd0(i+1&
&       , j))+tlocd0(i-2, j+1)-9.d0*tlocd0(i-1, j+1)+tlocd0(i+1, j+1)-&
&       9.d0*tlocd0(i, j+1))
      val_e = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-1, j-2)+9.d0*tloc(i&
&       , j-2)-tloc(i+1, j-2))+7.d0*(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)&
&       +9.d0*tloc(i, j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc&
&       (i-1, j)+9.d0*tloc(i, j)-tloc(i+1, j))-(-tloc(i-2, j+1)+9.d0*&
&       tloc(i-1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1)))
      val_odd = ccross*(tlocdd(i-2, j-1)-9.d0*tlocdd(i-1, j-1)-9.d0*&
&       tlocdd(i, j-1)+tlocdd(i+1, j-1)+7.d0*(9.d0*tlocdd(i-1, j)-tlocdd&
&       (i-2, j)+9.d0*tlocdd(i, j)-tlocdd(i+1, j))+7.d0*(9.d0*tlocdd(i-1&
&       , j+1)-tlocdd(i-2, j+1)+9.d0*tlocdd(i, j+1)-tlocdd(i+1, j+1))+&
&       tlocdd(i-2, j+2)-9.d0*tlocdd(i-1, j+2)+tlocdd(i+1, j+2)-9.d0*&
&       tlocdd(i, j+2))
      val_od = ccross*(tlocd(i-2, j-1)-9.d0*tlocd(i-1, j-1)-9.d0*tlocd(i&
&       , j-1)+tlocd(i+1, j-1)+7.d0*(9.d0*tlocd(i-1, j)-tlocd(i-2, j)+&
&       9.d0*tlocd(i, j)-tlocd(i+1, j))+7.d0*(9.d0*tlocd(i-1, j+1)-tlocd&
&       (i-2, j+1)+9.d0*tlocd(i, j+1)-tlocd(i+1, j+1))+tlocd(i-2, j+2)-&
&       9.d0*tlocd(i-1, j+2)+tlocd(i+1, j+2)-9.d0*tlocd(i, j+2))
      val_od0 = ccross*(tlocd0(i-2, j-1)-9.d0*tlocd0(i-1, j-1)-9.d0*&
&       tlocd0(i, j-1)+tlocd0(i+1, j-1)+7.d0*(9.d0*tlocd0(i-1, j)-tlocd0&
&       (i-2, j)+9.d0*tlocd0(i, j)-tlocd0(i+1, j))+7.d0*(9.d0*tlocd0(i-1&
&       , j+1)-tlocd0(i-2, j+1)+9.d0*tlocd0(i, j+1)-tlocd0(i+1, j+1))+&
&       tlocd0(i-2, j+2)-9.d0*tlocd0(i-1, j+2)+tlocd0(i+1, j+2)-9.d0*&
&       tlocd0(i, j+2))
      val_o = ccross*(-(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i&
&       , j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc(i-1, j)+&
&       9.d0*tloc(i, j)-tloc(i+1, j))+7.d0*(-tloc(i-2, j+1)+9.d0*tloc(i-&
&       1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1))-(-tloc(i-2, j+2)+9.d0*&
&       tloc(i-1, j+2)+9.d0*tloc(i, j+2)-tloc(i+1, j+2)))
      txdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      txd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      txd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      tydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      tyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      tyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
!
! Computation of viscous fluxes
!
      uudd = 0.0625d0*(9.d0*velxdd(i-1, j)-velxdd(i-2, j)+9.d0*velxdd(i&
&       , j)-velxdd(i+1, j))
      uud = 0.0625d0*(9.d0*velxd(i-1, j)-velxd(i-2, j)+9.d0*velxd(i, j)-&
&       velxd(i+1, j))
      uud0 = 0.0625d0*(9.d0*velxd0(i-1, j)-velxd0(i-2, j)+9.d0*velxd0(i&
&       , j)-velxd0(i+1, j))
      uu = 0.0625d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+9.d0*velx(i, j)-&
&       velx(i+1, j))
      vvdd = 0.0625d0*(9.d0*velydd(i-1, j)-velydd(i-2, j)+9.d0*velydd(i&
&       , j)-velydd(i+1, j))
      vvd = 0.0625d0*(9.d0*velyd(i-1, j)-velyd(i-2, j)+9.d0*velyd(i, j)-&
&       velyd(i+1, j))
      vvd0 = 0.0625d0*(9.d0*velyd0(i-1, j)-velyd0(i-2, j)+9.d0*velyd0(i&
&       , j)-velyd0(i+1, j))
      vv = 0.0625d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+9.d0*vely(i, j)-&
&       vely(i+1, j))
      wwdd = 0.0625d0*(9.d0*velzdd(i-1, j)-velzdd(i-2, j)+9.d0*velzdd(i&
&       , j)-velzdd(i+1, j))
      wwd = 0.0625d0*(9.d0*velzd(i-1, j)-velzd(i-2, j)+9.d0*velzd(i, j)-&
&       velzd(i+1, j))
      wwd0 = 0.0625d0*(9.d0*velzd0(i-1, j)-velzd0(i-2, j)+9.d0*velzd0(i&
&       , j)-velzd0(i+1, j))
      ww = 0.0625d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+9.d0*velz(i, j)-&
&       velz(i+1, j))
!
      mmudd = 0.0625d0*(9.d0*mudd(i-1, j)-mudd(i-2, j)+9.d0*mudd(i, j)-&
&       mudd(i+1, j))
      mmud = 0.0625d0*(9.d0*mud(i-1, j)-mud(i-2, j)+9.d0*mud(i, j)-mud(i&
&       +1, j))
      mmud0 = 0.0625d0*(9.d0*mud0(i-1, j)-mud0(i-2, j)+9.d0*mud0(i, j)-&
&       mud0(i+1, j))
      mmu = 0.0625d0*(-mu(i-2, j)+9.d0*mu(i-1, j)+9.d0*mu(i, j)-mu(i+1, &
&       j))
      lambdadd = cpprandtl*mmudd
      lambdad = cpprandtl*mmud
      lambdad0 = cpprandtl*mmud0
      lambda = mmu*cpprandtl
!
      fvrou1dd = twothird*(mmud*(two*uxd0-vyd0)+(two*ux-vy)*mmudd+(two*&
&       uxd-vyd)*mmud0+mmu*(two*uxdd-vydd))
      fvrou1d = twothird*((two*ux-vy)*mmud+mmu*(two*uxd-vyd))
      fvrou1d0 = twothird*((two*ux-vy)*mmud0+mmu*(two*uxd0-vyd0))
      fvrou1 = twothird*mmu*(two*ux-vy)
      fvrov1dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      fvrov1d = (uy+vx)*mmud + mmu*(uyd+vxd)
      fvrov1d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      fvrov1 = mmu*(uy+vx)
      fvrow1dd = mmud*wxd0 + wx*mmudd + wxd*mmud0 + mmu*wxdd
      fvrow1d = wx*mmud + mmu*wxd
      fvrow1d0 = wx*mmud0 + mmu*wxd0
      fvrow1 = mmu*wx
      fvroe1dd = lambdad*txd0 + tx*lambdadd + txd*lambdad0 + lambda*txdd&
&       + uud*fvrou1d0 + fvrou1*uudd + fvrou1d*uud0 + uu*fvrou1dd + vvd*&
&       fvrov1d0 + fvrov1*vvdd + fvrov1d*vvd0 + vv*fvrov1dd + wwd*&
&       fvrow1d0 + fvrow1*wwdd + fvrow1d*wwd0 + ww*fvrow1dd
!
      gvrou1dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      gvrou1d = (uy+vx)*mmud + mmu*(uyd+vxd)
      gvrou1d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      gvrou1 = mmu*(uy+vx)
      gvrov1dd = twothird*(mmud*(two*vyd0-uxd0)+(two*vy-ux)*mmudd+(two*&
&       vyd-uxd)*mmud0+mmu*(two*vydd-uxdd))
      gvrov1d = twothird*((two*vy-ux)*mmud+mmu*(two*vyd-uxd))
      gvrov1d0 = twothird*((two*vy-ux)*mmud0+mmu*(two*vyd0-uxd0))
      gvrov1 = twothird*mmu*(-ux+two*vy)
      gvrow1dd = mmud*wyd0 + wy*mmudd + wyd*mmud0 + mmu*wydd
      gvrow1d = wy*mmud + mmu*wyd
      gvrow1d0 = wy*mmud0 + mmu*wyd0
      gvrow1 = mmu*wy
      gvroe1dd = lambdad*tyd0 + ty*lambdadd + tyd*lambdad0 + lambda*tydd&
&       + uud*gvrou1d0 + gvrou1*uudd + gvrou1d*uud0 + uu*gvrou1dd + vvd*&
&       gvrov1d0 + gvrov1*vvdd + gvrov1d*vvd0 + vv*gvrov1dd + wwd*&
&       gvrow1d0 + gvrow1*wwdd + gvrow1d*wwd0 + ww*gvrow1dd
!!  fvrou1 = TWOTHIRD*mmu*( TWO*ux -     vy  -   wz  )
!!  fvrov1 =          mmu*(     uy +     vx          )
!!  fvrow1 =          mmu*(     uz           +   wx  )
!!  fvroe1 = lambda*tx + uu*fvrou1 + vv*fvrov1 + ww * fvrow1
!!  !
!!  gvrou1 =          mmu*(     uy +     vx          )
!!  gvrov1 = TWOTHIRD*mmu*(    -ux + TWO*vy   -  wz  )
!!  gvrow1 =          mmu*(              vz   +  wy  )
!!  gvroe1 = lambda*ty + uu*gvrou1 + vv*gvrov1 + ww * gvrow1
! grad for viscous fluxes o4 - 5p
!
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccross = TWELFTH*0.0625d0
      volm1 = volf(i, j, 2)
      nx_n = half*(nx(i+1, j-1, 1)+nx(i+1, j, 1))
      nx_s = -(half*(nx(i, j-1, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i, j+1, 2)+nx(i, j, 2))
      nx_e = -(half*(nx(i, j-1, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j-1, 1)+ny(i+1, j, 1))
      ny_s = -(half*(ny(i, j-1, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i, j+1, 2)+ny(i, j, 2))
      ny_e = -(half*(ny(i, j-1, 2)+ny(i, j, 2)))
      val_ndd = ccross*(velxdd(i-1, j-2)-9.d0*velxdd(i-1, j-1)-9.d0*&
&       velxdd(i-1, j)+velxdd(i-1, j+1)+7.d0*(9.d0*velxdd(i, j-1)-velxdd&
&       (i, j-2)+9.d0*velxdd(i, j)-velxdd(i, j+1))+7.d0*(9.d0*velxdd(i+1&
&       , j-1)-velxdd(i+1, j-2)+9.d0*velxdd(i+1, j)-velxdd(i+1, j+1))+&
&       velxdd(i+2, j-2)-9.d0*velxdd(i+2, j-1)+velxdd(i+2, j+1)-9.d0*&
&       velxdd(i+2, j))
      val_nd = ccross*(velxd(i-1, j-2)-9.d0*velxd(i-1, j-1)-9.d0*velxd(i&
&       -1, j)+velxd(i-1, j+1)+7.d0*(9.d0*velxd(i, j-1)-velxd(i, j-2)+&
&       9.d0*velxd(i, j)-velxd(i, j+1))+7.d0*(9.d0*velxd(i+1, j-1)-velxd&
&       (i+1, j-2)+9.d0*velxd(i+1, j)-velxd(i+1, j+1))+velxd(i+2, j-2)-&
&       9.d0*velxd(i+2, j-1)+velxd(i+2, j+1)-9.d0*velxd(i+2, j))
      val_nd0 = ccross*(velxd0(i-1, j-2)-9.d0*velxd0(i-1, j-1)-9.d0*&
&       velxd0(i-1, j)+velxd0(i-1, j+1)+7.d0*(9.d0*velxd0(i, j-1)-velxd0&
&       (i, j-2)+9.d0*velxd0(i, j)-velxd0(i, j+1))+7.d0*(9.d0*velxd0(i+1&
&       , j-1)-velxd0(i+1, j-2)+9.d0*velxd0(i+1, j)-velxd0(i+1, j+1))+&
&       velxd0(i+2, j-2)-9.d0*velxd0(i+2, j-1)+velxd0(i+2, j+1)-9.d0*&
&       velxd0(i+2, j))
      val_n = ccross*(-(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+9.d0*velx(i-&
&       1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0&
&       *velx(i, j)-velx(i, j+1))+7.d0*(-velx(i+1, j-2)+9.d0*velx(i+1, j&
&       -1)+9.d0*velx(i+1, j)-velx(i+1, j+1))-(-velx(i+2, j-2)+9.d0*velx&
&       (i+2, j-1)+9.d0*velx(i+2, j)-velx(i+2, j+1)))
      val_sdd = ccross*(velxdd(i-2, j-2)-9.d0*velxdd(i-2, j-1)-9.d0*&
&       velxdd(i-2, j)+velxdd(i-2, j+1)+7.d0*(9.d0*velxdd(i-1, j-1)-&
&       velxdd(i-1, j-2)+9.d0*velxdd(i-1, j)-velxdd(i-1, j+1))+7.d0*(&
&       9.d0*velxdd(i, j-1)-velxdd(i, j-2)+9.d0*velxdd(i, j)-velxdd(i, j&
&       +1))+velxdd(i+1, j-2)-9.d0*velxdd(i+1, j-1)+velxdd(i+1, j+1)-&
&       9.d0*velxdd(i+1, j))
      val_sd = ccross*(velxd(i-2, j-2)-9.d0*velxd(i-2, j-1)-9.d0*velxd(i&
&       -2, j)+velxd(i-2, j+1)+7.d0*(9.d0*velxd(i-1, j-1)-velxd(i-1, j-2&
&       )+9.d0*velxd(i-1, j)-velxd(i-1, j+1))+7.d0*(9.d0*velxd(i, j-1)-&
&       velxd(i, j-2)+9.d0*velxd(i, j)-velxd(i, j+1))+velxd(i+1, j-2)-&
&       9.d0*velxd(i+1, j-1)+velxd(i+1, j+1)-9.d0*velxd(i+1, j))
      val_sd0 = ccross*(velxd0(i-2, j-2)-9.d0*velxd0(i-2, j-1)-9.d0*&
&       velxd0(i-2, j)+velxd0(i-2, j+1)+7.d0*(9.d0*velxd0(i-1, j-1)-&
&       velxd0(i-1, j-2)+9.d0*velxd0(i-1, j)-velxd0(i-1, j+1))+7.d0*(&
&       9.d0*velxd0(i, j-1)-velxd0(i, j-2)+9.d0*velxd0(i, j)-velxd0(i, j&
&       +1))+velxd0(i+1, j-2)-9.d0*velxd0(i+1, j-1)+velxd0(i+1, j+1)-&
&       9.d0*velxd0(i+1, j))
      val_s = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-2, j-1)+9.d0*velx(i-&
&       2, j)-velx(i-2, j+1))+7.d0*(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+&
&       9.d0*velx(i-1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(&
&       i, j-1)+9.d0*velx(i, j)-velx(i, j+1))-(-velx(i+1, j-2)+9.d0*velx&
&       (i+1, j-1)+9.d0*velx(i+1, j)-velx(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*velxdd(i, j-1)-velxdd(i, j)-velxdd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*velxd(i, j-1)-velxd(i, j)-velxd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*velxd0(i, j-1)-velxd0(i, j)-velxd0(i&
&       , j-2))
      val_e = twentyfourth*(-velx(i, j)+26.d0*velx(i, j-1)-velx(i, j-2))
      val_odd = twentyfourth*(26.d0*velxdd(i, j)-velxdd(i, j+1)-velxdd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*velxd(i, j)-velxd(i, j+1)-velxd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*velxd0(i, j)-velxd0(i, j+1)-velxd0(i&
&       , j-1))
      val_o = twentyfourth*(-velx(i, j+1)+26.d0*velx(i, j)-velx(i, j-1))
      uxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      uxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      uxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      uyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      uyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = ccross*(velydd(i-1, j-2)-9.d0*velydd(i-1, j-1)-9.d0*&
&       velydd(i-1, j)+velydd(i-1, j+1)+7.d0*(9.d0*velydd(i, j-1)-velydd&
&       (i, j-2)+9.d0*velydd(i, j)-velydd(i, j+1))+7.d0*(9.d0*velydd(i+1&
&       , j-1)-velydd(i+1, j-2)+9.d0*velydd(i+1, j)-velydd(i+1, j+1))+&
&       velydd(i+2, j-2)-9.d0*velydd(i+2, j-1)+velydd(i+2, j+1)-9.d0*&
&       velydd(i+2, j))
      val_nd = ccross*(velyd(i-1, j-2)-9.d0*velyd(i-1, j-1)-9.d0*velyd(i&
&       -1, j)+velyd(i-1, j+1)+7.d0*(9.d0*velyd(i, j-1)-velyd(i, j-2)+&
&       9.d0*velyd(i, j)-velyd(i, j+1))+7.d0*(9.d0*velyd(i+1, j-1)-velyd&
&       (i+1, j-2)+9.d0*velyd(i+1, j)-velyd(i+1, j+1))+velyd(i+2, j-2)-&
&       9.d0*velyd(i+2, j-1)+velyd(i+2, j+1)-9.d0*velyd(i+2, j))
      val_nd0 = ccross*(velyd0(i-1, j-2)-9.d0*velyd0(i-1, j-1)-9.d0*&
&       velyd0(i-1, j)+velyd0(i-1, j+1)+7.d0*(9.d0*velyd0(i, j-1)-velyd0&
&       (i, j-2)+9.d0*velyd0(i, j)-velyd0(i, j+1))+7.d0*(9.d0*velyd0(i+1&
&       , j-1)-velyd0(i+1, j-2)+9.d0*velyd0(i+1, j)-velyd0(i+1, j+1))+&
&       velyd0(i+2, j-2)-9.d0*velyd0(i+2, j-1)+velyd0(i+2, j+1)-9.d0*&
&       velyd0(i+2, j))
      val_n = ccross*(-(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+9.d0*vely(i-&
&       1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0&
&       *vely(i, j)-vely(i, j+1))+7.d0*(-vely(i+1, j-2)+9.d0*vely(i+1, j&
&       -1)+9.d0*vely(i+1, j)-vely(i+1, j+1))-(-vely(i+2, j-2)+9.d0*vely&
&       (i+2, j-1)+9.d0*vely(i+2, j)-vely(i+2, j+1)))
      val_sdd = ccross*(velydd(i-2, j-2)-9.d0*velydd(i-2, j-1)-9.d0*&
&       velydd(i-2, j)+velydd(i-2, j+1)+7.d0*(9.d0*velydd(i-1, j-1)-&
&       velydd(i-1, j-2)+9.d0*velydd(i-1, j)-velydd(i-1, j+1))+7.d0*(&
&       9.d0*velydd(i, j-1)-velydd(i, j-2)+9.d0*velydd(i, j)-velydd(i, j&
&       +1))+velydd(i+1, j-2)-9.d0*velydd(i+1, j-1)+velydd(i+1, j+1)-&
&       9.d0*velydd(i+1, j))
      val_sd = ccross*(velyd(i-2, j-2)-9.d0*velyd(i-2, j-1)-9.d0*velyd(i&
&       -2, j)+velyd(i-2, j+1)+7.d0*(9.d0*velyd(i-1, j-1)-velyd(i-1, j-2&
&       )+9.d0*velyd(i-1, j)-velyd(i-1, j+1))+7.d0*(9.d0*velyd(i, j-1)-&
&       velyd(i, j-2)+9.d0*velyd(i, j)-velyd(i, j+1))+velyd(i+1, j-2)-&
&       9.d0*velyd(i+1, j-1)+velyd(i+1, j+1)-9.d0*velyd(i+1, j))
      val_sd0 = ccross*(velyd0(i-2, j-2)-9.d0*velyd0(i-2, j-1)-9.d0*&
&       velyd0(i-2, j)+velyd0(i-2, j+1)+7.d0*(9.d0*velyd0(i-1, j-1)-&
&       velyd0(i-1, j-2)+9.d0*velyd0(i-1, j)-velyd0(i-1, j+1))+7.d0*(&
&       9.d0*velyd0(i, j-1)-velyd0(i, j-2)+9.d0*velyd0(i, j)-velyd0(i, j&
&       +1))+velyd0(i+1, j-2)-9.d0*velyd0(i+1, j-1)+velyd0(i+1, j+1)-&
&       9.d0*velyd0(i+1, j))
      val_s = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-2, j-1)+9.d0*vely(i-&
&       2, j)-vely(i-2, j+1))+7.d0*(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+&
&       9.d0*vely(i-1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(&
&       i, j-1)+9.d0*vely(i, j)-vely(i, j+1))-(-vely(i+1, j-2)+9.d0*vely&
&       (i+1, j-1)+9.d0*vely(i+1, j)-vely(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*velydd(i, j-1)-velydd(i, j)-velydd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*velyd(i, j-1)-velyd(i, j)-velyd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*velyd0(i, j-1)-velyd0(i, j)-velyd0(i&
&       , j-2))
      val_e = twentyfourth*(-vely(i, j)+26.d0*vely(i, j-1)-vely(i, j-2))
      val_odd = twentyfourth*(26.d0*velydd(i, j)-velydd(i, j+1)-velydd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*velyd(i, j)-velyd(i, j+1)-velyd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*velyd0(i, j)-velyd0(i, j+1)-velyd0(i&
&       , j-1))
      val_o = twentyfourth*(-vely(i, j+1)+26.d0*vely(i, j)-vely(i, j-1))
      vxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      vxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      vxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      vyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      vyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = ccross*(velzdd(i-1, j-2)-9.d0*velzdd(i-1, j-1)-9.d0*&
&       velzdd(i-1, j)+velzdd(i-1, j+1)+7.d0*(9.d0*velzdd(i, j-1)-velzdd&
&       (i, j-2)+9.d0*velzdd(i, j)-velzdd(i, j+1))+7.d0*(9.d0*velzdd(i+1&
&       , j-1)-velzdd(i+1, j-2)+9.d0*velzdd(i+1, j)-velzdd(i+1, j+1))+&
&       velzdd(i+2, j-2)-9.d0*velzdd(i+2, j-1)+velzdd(i+2, j+1)-9.d0*&
&       velzdd(i+2, j))
      val_nd = ccross*(velzd(i-1, j-2)-9.d0*velzd(i-1, j-1)-9.d0*velzd(i&
&       -1, j)+velzd(i-1, j+1)+7.d0*(9.d0*velzd(i, j-1)-velzd(i, j-2)+&
&       9.d0*velzd(i, j)-velzd(i, j+1))+7.d0*(9.d0*velzd(i+1, j-1)-velzd&
&       (i+1, j-2)+9.d0*velzd(i+1, j)-velzd(i+1, j+1))+velzd(i+2, j-2)-&
&       9.d0*velzd(i+2, j-1)+velzd(i+2, j+1)-9.d0*velzd(i+2, j))
      val_nd0 = ccross*(velzd0(i-1, j-2)-9.d0*velzd0(i-1, j-1)-9.d0*&
&       velzd0(i-1, j)+velzd0(i-1, j+1)+7.d0*(9.d0*velzd0(i, j-1)-velzd0&
&       (i, j-2)+9.d0*velzd0(i, j)-velzd0(i, j+1))+7.d0*(9.d0*velzd0(i+1&
&       , j-1)-velzd0(i+1, j-2)+9.d0*velzd0(i+1, j)-velzd0(i+1, j+1))+&
&       velzd0(i+2, j-2)-9.d0*velzd0(i+2, j-1)+velzd0(i+2, j+1)-9.d0*&
&       velzd0(i+2, j))
      val_n = ccross*(-(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+9.d0*velz(i-&
&       1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0&
&       *velz(i, j)-velz(i, j+1))+7.d0*(-velz(i+1, j-2)+9.d0*velz(i+1, j&
&       -1)+9.d0*velz(i+1, j)-velz(i+1, j+1))-(-velz(i+2, j-2)+9.d0*velz&
&       (i+2, j-1)+9.d0*velz(i+2, j)-velz(i+2, j+1)))
      val_sdd = ccross*(velzdd(i-2, j-2)-9.d0*velzdd(i-2, j-1)-9.d0*&
&       velzdd(i-2, j)+velzdd(i-2, j+1)+7.d0*(9.d0*velzdd(i-1, j-1)-&
&       velzdd(i-1, j-2)+9.d0*velzdd(i-1, j)-velzdd(i-1, j+1))+7.d0*(&
&       9.d0*velzdd(i, j-1)-velzdd(i, j-2)+9.d0*velzdd(i, j)-velzdd(i, j&
&       +1))+velzdd(i+1, j-2)-9.d0*velzdd(i+1, j-1)+velzdd(i+1, j+1)-&
&       9.d0*velzdd(i+1, j))
      val_sd = ccross*(velzd(i-2, j-2)-9.d0*velzd(i-2, j-1)-9.d0*velzd(i&
&       -2, j)+velzd(i-2, j+1)+7.d0*(9.d0*velzd(i-1, j-1)-velzd(i-1, j-2&
&       )+9.d0*velzd(i-1, j)-velzd(i-1, j+1))+7.d0*(9.d0*velzd(i, j-1)-&
&       velzd(i, j-2)+9.d0*velzd(i, j)-velzd(i, j+1))+velzd(i+1, j-2)-&
&       9.d0*velzd(i+1, j-1)+velzd(i+1, j+1)-9.d0*velzd(i+1, j))
      val_sd0 = ccross*(velzd0(i-2, j-2)-9.d0*velzd0(i-2, j-1)-9.d0*&
&       velzd0(i-2, j)+velzd0(i-2, j+1)+7.d0*(9.d0*velzd0(i-1, j-1)-&
&       velzd0(i-1, j-2)+9.d0*velzd0(i-1, j)-velzd0(i-1, j+1))+7.d0*(&
&       9.d0*velzd0(i, j-1)-velzd0(i, j-2)+9.d0*velzd0(i, j)-velzd0(i, j&
&       +1))+velzd0(i+1, j-2)-9.d0*velzd0(i+1, j-1)+velzd0(i+1, j+1)-&
&       9.d0*velzd0(i+1, j))
      val_s = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-2, j-1)+9.d0*velz(i-&
&       2, j)-velz(i-2, j+1))+7.d0*(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+&
&       9.d0*velz(i-1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(&
&       i, j-1)+9.d0*velz(i, j)-velz(i, j+1))-(-velz(i+1, j-2)+9.d0*velz&
&       (i+1, j-1)+9.d0*velz(i+1, j)-velz(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*velzdd(i, j-1)-velzdd(i, j)-velzdd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*velzd(i, j-1)-velzd(i, j)-velzd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*velzd0(i, j-1)-velzd0(i, j)-velzd0(i&
&       , j-2))
      val_e = twentyfourth*(-velz(i, j)+26.d0*velz(i, j-1)-velz(i, j-2))
      val_odd = twentyfourth*(26.d0*velzdd(i, j)-velzdd(i, j+1)-velzdd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*velzd(i, j)-velzd(i, j+1)-velzd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*velzd0(i, j)-velzd0(i, j+1)-velzd0(i&
&       , j-1))
      val_o = twentyfourth*(-velz(i, j+1)+26.d0*velz(i, j)-velz(i, j-1))
      wxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      wxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      wxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      wyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      wyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = ccross*(tlocdd(i-1, j-2)-9.d0*tlocdd(i-1, j-1)-9.d0*&
&       tlocdd(i-1, j)+tlocdd(i-1, j+1)+7.d0*(9.d0*tlocdd(i, j-1)-tlocdd&
&       (i, j-2)+9.d0*tlocdd(i, j)-tlocdd(i, j+1))+7.d0*(9.d0*tlocdd(i+1&
&       , j-1)-tlocdd(i+1, j-2)+9.d0*tlocdd(i+1, j)-tlocdd(i+1, j+1))+&
&       tlocdd(i+2, j-2)-9.d0*tlocdd(i+2, j-1)+tlocdd(i+2, j+1)-9.d0*&
&       tlocdd(i+2, j))
      val_nd = ccross*(tlocd(i-1, j-2)-9.d0*tlocd(i-1, j-1)-9.d0*tlocd(i&
&       -1, j)+tlocd(i-1, j+1)+7.d0*(9.d0*tlocd(i, j-1)-tlocd(i, j-2)+&
&       9.d0*tlocd(i, j)-tlocd(i, j+1))+7.d0*(9.d0*tlocd(i+1, j-1)-tlocd&
&       (i+1, j-2)+9.d0*tlocd(i+1, j)-tlocd(i+1, j+1))+tlocd(i+2, j-2)-&
&       9.d0*tlocd(i+2, j-1)+tlocd(i+2, j+1)-9.d0*tlocd(i+2, j))
      val_nd0 = ccross*(tlocd0(i-1, j-2)-9.d0*tlocd0(i-1, j-1)-9.d0*&
&       tlocd0(i-1, j)+tlocd0(i-1, j+1)+7.d0*(9.d0*tlocd0(i, j-1)-tlocd0&
&       (i, j-2)+9.d0*tlocd0(i, j)-tlocd0(i, j+1))+7.d0*(9.d0*tlocd0(i+1&
&       , j-1)-tlocd0(i+1, j-2)+9.d0*tlocd0(i+1, j)-tlocd0(i+1, j+1))+&
&       tlocd0(i+2, j-2)-9.d0*tlocd0(i+2, j-1)+tlocd0(i+2, j+1)-9.d0*&
&       tlocd0(i+2, j))
      val_n = ccross*(-(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i-&
&       1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(i, j-1)+9.d0&
&       *tloc(i, j)-tloc(i, j+1))+7.d0*(-tloc(i+1, j-2)+9.d0*tloc(i+1, j&
&       -1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1))-(-tloc(i+2, j-2)+9.d0*tloc&
&       (i+2, j-1)+9.d0*tloc(i+2, j)-tloc(i+2, j+1)))
      val_sdd = ccross*(tlocdd(i-2, j-2)-9.d0*tlocdd(i-2, j-1)-9.d0*&
&       tlocdd(i-2, j)+tlocdd(i-2, j+1)+7.d0*(9.d0*tlocdd(i-1, j-1)-&
&       tlocdd(i-1, j-2)+9.d0*tlocdd(i-1, j)-tlocdd(i-1, j+1))+7.d0*(&
&       9.d0*tlocdd(i, j-1)-tlocdd(i, j-2)+9.d0*tlocdd(i, j)-tlocdd(i, j&
&       +1))+tlocdd(i+1, j-2)-9.d0*tlocdd(i+1, j-1)+tlocdd(i+1, j+1)-&
&       9.d0*tlocdd(i+1, j))
      val_sd = ccross*(tlocd(i-2, j-2)-9.d0*tlocd(i-2, j-1)-9.d0*tlocd(i&
&       -2, j)+tlocd(i-2, j+1)+7.d0*(9.d0*tlocd(i-1, j-1)-tlocd(i-1, j-2&
&       )+9.d0*tlocd(i-1, j)-tlocd(i-1, j+1))+7.d0*(9.d0*tlocd(i, j-1)-&
&       tlocd(i, j-2)+9.d0*tlocd(i, j)-tlocd(i, j+1))+tlocd(i+1, j-2)-&
&       9.d0*tlocd(i+1, j-1)+tlocd(i+1, j+1)-9.d0*tlocd(i+1, j))
      val_sd0 = ccross*(tlocd0(i-2, j-2)-9.d0*tlocd0(i-2, j-1)-9.d0*&
&       tlocd0(i-2, j)+tlocd0(i-2, j+1)+7.d0*(9.d0*tlocd0(i-1, j-1)-&
&       tlocd0(i-1, j-2)+9.d0*tlocd0(i-1, j)-tlocd0(i-1, j+1))+7.d0*(&
&       9.d0*tlocd0(i, j-1)-tlocd0(i, j-2)+9.d0*tlocd0(i, j)-tlocd0(i, j&
&       +1))+tlocd0(i+1, j-2)-9.d0*tlocd0(i+1, j-1)+tlocd0(i+1, j+1)-&
&       9.d0*tlocd0(i+1, j))
      val_s = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-2, j-1)+9.d0*tloc(i-&
&       2, j)-tloc(i-2, j+1))+7.d0*(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+&
&       9.d0*tloc(i-1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(&
&       i, j-1)+9.d0*tloc(i, j)-tloc(i, j+1))-(-tloc(i+1, j-2)+9.d0*tloc&
&       (i+1, j-1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*tlocdd(i, j-1)-tlocdd(i, j)-tlocdd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*tlocd(i, j-1)-tlocd(i, j)-tlocd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*tlocd0(i, j-1)-tlocd0(i, j)-tlocd0(i&
&       , j-2))
      val_e = twentyfourth*(-tloc(i, j)+26.d0*tloc(i, j-1)-tloc(i, j-2))
      val_odd = twentyfourth*(26.d0*tlocdd(i, j)-tlocdd(i, j+1)-tlocdd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*tlocd(i, j)-tlocd(i, j+1)-tlocd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*tlocd0(i, j)-tlocd0(i, j+1)-tlocd0(i&
&       , j-1))
      val_o = twentyfourth*(-tloc(i, j+1)+26.d0*tloc(i, j)-tloc(i, j-1))
      txdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      txd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      txd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      tydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      tyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      tyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      uudd = 0.0625d0*(9.d0*velxdd(i, j-1)-velxdd(i, j-2)+9.d0*velxdd(i&
&       , j)-velxdd(i, j+1))
      uud = 0.0625d0*(9.d0*velxd(i, j-1)-velxd(i, j-2)+9.d0*velxd(i, j)-&
&       velxd(i, j+1))
      uud0 = 0.0625d0*(9.d0*velxd0(i, j-1)-velxd0(i, j-2)+9.d0*velxd0(i&
&       , j)-velxd0(i, j+1))
      uu = 0.0625d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0*velx(i, j)-&
&       velx(i, j+1))
      vvdd = 0.0625d0*(9.d0*velydd(i, j-1)-velydd(i, j-2)+9.d0*velydd(i&
&       , j)-velydd(i, j+1))
      vvd = 0.0625d0*(9.d0*velyd(i, j-1)-velyd(i, j-2)+9.d0*velyd(i, j)-&
&       velyd(i, j+1))
      vvd0 = 0.0625d0*(9.d0*velyd0(i, j-1)-velyd0(i, j-2)+9.d0*velyd0(i&
&       , j)-velyd0(i, j+1))
      vv = 0.0625d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0*vely(i, j)-&
&       vely(i, j+1))
      wwdd = 0.0625d0*(9.d0*velzdd(i, j-1)-velzdd(i, j-2)+9.d0*velzdd(i&
&       , j)-velzdd(i, j+1))
      wwd = 0.0625d0*(9.d0*velzd(i, j-1)-velzd(i, j-2)+9.d0*velzd(i, j)-&
&       velzd(i, j+1))
      wwd0 = 0.0625d0*(9.d0*velzd0(i, j-1)-velzd0(i, j-2)+9.d0*velzd0(i&
&       , j)-velzd0(i, j+1))
      ww = 0.0625d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0*velz(i, j)-&
&       velz(i, j+1))
!
      mmudd = 0.0625d0*(9.d0*mudd(i, j-1)-mudd(i, j-2)+9.d0*mudd(i, j)-&
&       mudd(i, j+1))
      mmud = 0.0625d0*(9.d0*mud(i, j-1)-mud(i, j-2)+9.d0*mud(i, j)-mud(i&
&       , j+1))
      mmud0 = 0.0625d0*(9.d0*mud0(i, j-1)-mud0(i, j-2)+9.d0*mud0(i, j)-&
&       mud0(i, j+1))
      mmu = 0.0625d0*(-mu(i, j-2)+9.d0*mu(i, j-1)+9.d0*mu(i, j)-mu(i, j+&
&       1))
      lambdadd = cpprandtl*mmudd
      lambdad = cpprandtl*mmud
      lambdad0 = cpprandtl*mmud0
      lambda = mmu*cpprandtl
!
      fvrou2dd = twothird*(mmud*(two*uxd0-vyd0)+(two*ux-vy)*mmudd+(two*&
&       uxd-vyd)*mmud0+mmu*(two*uxdd-vydd))
      fvrou2d = twothird*((two*ux-vy)*mmud+mmu*(two*uxd-vyd))
      fvrou2d0 = twothird*((two*ux-vy)*mmud0+mmu*(two*uxd0-vyd0))
      fvrou2 = twothird*mmu*(two*ux-vy)
      fvrov2dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      fvrov2d = (uy+vx)*mmud + mmu*(uyd+vxd)
      fvrov2d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      fvrov2 = mmu*(uy+vx)
      fvrow2dd = mmud*wxd0 + wx*mmudd + wxd*mmud0 + mmu*wxdd
      fvrow2d = wx*mmud + mmu*wxd
      fvrow2d0 = wx*mmud0 + mmu*wxd0
      fvrow2 = mmu*wx
      fvroe2dd = lambdad*txd0 + tx*lambdadd + txd*lambdad0 + lambda*txdd&
&       + uud*fvrou2d0 + fvrou2*uudd + fvrou2d*uud0 + uu*fvrou2dd + vvd*&
&       fvrov2d0 + fvrov2*vvdd + fvrov2d*vvd0 + vv*fvrov2dd + wwd*&
&       fvrow2d0 + fvrow2*wwdd + fvrow2d*wwd0 + ww*fvrow2dd
      gvrou2dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      gvrou2d = (uy+vx)*mmud + mmu*(uyd+vxd)
      gvrou2d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      gvrou2 = mmu*(uy+vx)
      gvrov2dd = twothird*(mmud*(two*vyd0-uxd0)+(two*vy-ux)*mmudd+(two*&
&       vyd-uxd)*mmud0+mmu*(two*vydd-uxdd))
      gvrov2d = twothird*((two*vy-ux)*mmud+mmu*(two*vyd-uxd))
      gvrov2d0 = twothird*((two*vy-ux)*mmud0+mmu*(two*vyd0-uxd0))
      gvrov2 = twothird*mmu*(-ux+two*vy)
      gvrow2dd = mmud*wyd0 + wy*mmudd + wyd*mmud0 + mmu*wydd
      gvrow2d = wy*mmud + mmu*wyd
      gvrow2d0 = wy*mmud0 + mmu*wyd0
      gvrow2 = mmu*wy
      gvroe2dd = lambdad*tyd0 + ty*lambdadd + tyd*lambdad0 + lambda*tydd&
&       + uud*gvrou2d0 + gvrou2*uudd + gvrou2d*uud0 + uu*gvrou2dd + vvd*&
&       gvrov2d0 + gvrov2*vvdd + gvrov2d*vvd0 + vv*gvrov2dd + wwd*&
&       gvrow2d0 + gvrow2*wwdd + gvrow2d*wwd0 + ww*gvrow2dd
!!  fvrou2 = TWOTHIRD*mmu*( TWO*ux -     vy  -  wz  )
!!  fvrov2 =          mmu*(     uy +     vx         )
!!  fvrow2 =          mmu*(     uz           +  wx  )
!!  fvroe2 = (lambda*tx + uu*fvrou2 + vv*fvrov2 + ww * fvrow2)
!!
!!  gvrou2 =          mmu*(     uy +     vx       )
!!  gvrov2 = TWOTHIRD*mmu*(    -ux + TWO*vy -  wz )
!!  gvrow2 =          mmu*(              vz +  wy )
!!  gvroe2 = (lambda*ty + uu*gvrou2 + vv*gvrov2 + ww*gvrow2)
!1st direction
!
!
!
!
!
!
!1st direction
      rhomrd = wd(i, j, 1)
      rhomrd0 = wd0(i, j, 1)
      rhomr = w(i, j, 1)
      temp3 = w(i, j, 2)/rhomr
      tempd = (wd0(i, j, 2)-temp3*rhomrd0)/rhomr
      temp = temp3
      temp3 = (wd(i, j, 2)-rhomrd*temp)/rhomr
      urdd = (-(rhomrd*tempd)-temp3*rhomrd0)/rhomr
      urd = temp3
      urd0 = tempd
      ur = temp
      temp3 = w(i, j, 3)/rhomr
      tempd = (wd0(i, j, 3)-temp3*rhomrd0)/rhomr
      temp = temp3
      temp3 = (wd(i, j, 3)-rhomrd*temp)/rhomr
      vrdd = (-(rhomrd*tempd)-temp3*rhomrd0)/rhomr
      vrd = temp3
      vrd0 = tempd
      vr = temp
      c2rdd = gam*rgaz*tlocdd(i, j)
      c2rd = gam*rgaz*tlocd(i, j)
      c2rd0 = gam*rgaz*tlocd0(i, j)
      c2r = gam*rgaz*tloc(i, j)
!
      rhomld = wd(i, j-1, 1)
      rhomld0 = wd0(i, j-1, 1)
      rhoml = w(i, j-1, 1)
      temp3 = w(i, j-1, 2)/rhoml
      tempd = (wd0(i, j-1, 2)-temp3*rhomld0)/rhoml
      temp = temp3
      temp3 = (wd(i, j-1, 2)-rhomld*temp)/rhoml
      uldd = (-(rhomld*tempd)-temp3*rhomld0)/rhoml
      uld = temp3
      uld0 = tempd
      ul = temp
      temp3 = w(i, j-1, 3)/rhoml
      tempd = (wd0(i, j-1, 3)-temp3*rhomld0)/rhoml
      temp = temp3
      temp3 = (wd(i, j-1, 3)-rhomld*temp)/rhoml
      vldd = (-(rhomld*tempd)-temp3*rhomld0)/rhoml
      vld = temp3
      vld0 = tempd
      vl = temp
      c2ldd = gam*rgaz*tlocdd(i, j-1)
      c2ld = gam*rgaz*tlocd(i, j-1)
      c2ld0 = gam*rgaz*tlocd0(i, j-1)
      c2l = gam*rgaz*tloc(i, j-1)
!
      tempd = (rhomrd0-rhomr*rhomld0/rhoml)/rhoml
      temp = rhomr/rhoml
      temp3 = SQRT(temp)
      IF (temp .EQ. 0.0) THEN
        temp0d = 0.0_8
      ELSE
        temp0d = tempd/(2.0*temp3)
      END IF
      temp0 = temp3
      IF (temp .EQ. 0.0) THEN
        rd = 0.0_8
        rdd = 0.0_8
      ELSE
        temp3 = 2.0*temp0*rhoml
        temp2 = (rhomrd-rhomld*temp)/temp3
        rdd = (-(rhomld*tempd)-temp2*(rhoml*2.0*temp0d+2.0*temp0*rhomld0&
&         ))/temp3
        rd = temp2
      END IF
      rd0 = temp0d
      r = temp0
      temp3 = one/(one+r)
      temp0d = -(temp3*rd0/(one+r))
      temp0 = temp3
      temp3 = temp0*rd/(one+r)
      rrdd = -((rd*temp0d+temp0*rdd-temp3*rd0)/(one+r))
      rrd = -temp3
      rrd0 = temp0d
      rr = temp0
      omrrdd = -rrdd
      omrrd = -rrd
      omrrd0 = -rrd0
      omrr = one - rr
!
      udd = uld*rrd0 + rr*uldd + rrd*uld0 + ul*rrdd + urd*omrrd0 + omrr*&
&       urdd + omrrd*urd0 + ur*omrrdd
      ud = rr*uld + ul*rrd + omrr*urd + ur*omrrd
      ud0 = rr*uld0 + ul*rrd0 + omrr*urd0 + ur*omrrd0
      u = ul*rr + ur*omrr
      vdd = vld*rrd0 + rr*vldd + rrd*vld0 + vl*rrdd + vrd*omrrd0 + omrr*&
&       vrdd + omrrd*vrd0 + vr*omrrdd
      vd = rr*vld + vl*rrd + omrr*vrd + vr*omrrd
      vd0 = rr*vld0 + vl*rrd0 + omrr*vrd0 + vr*omrrd0
      v = vl*rr + vr*omrr
!
      c2xdd = c2ld*rrd0 + rr*c2ldd + rrd*c2ld0 + c2l*rrdd + c2rd*omrrd0 &
&       + omrr*c2rdd + omrrd*c2rd0 + c2r*omrrdd
      c2xd = rr*c2ld + c2l*rrd + omrr*c2rd + c2r*omrrd
      c2xd0 = rr*c2ld0 + c2l*rrd0 + omrr*c2rd0 + c2r*omrrd0
      c2x = c2l*rr + c2r*omrr
      nx2 = nx(i, j, 2)*nx(i, j, 2) + ny(i, j, 2)*ny(i, j, 2)
      x2dd = nx(i, j, 2)*udd + ny(i, j, 2)*vdd
      x2d = nx(i, j, 2)*ud + ny(i, j, 2)*vd
      x2d0 = nx(i, j, 2)*ud0 + ny(i, j, 2)*vd0
      x2 = nx(i, j, 2)*u + ny(i, j, 2)*v
      IF (x2 .GE. 0.) THEN
        abdd = x2dd
        abd = x2d
        abd0 = x2d0
        ab = x2
      ELSE
        abdd = -x2dd
        abd = -x2d
        abd0 = -x2d0
        ab = -x2
      END IF
      temp3 = SQRT(nx2*c2x)
      IF (nx2*c2x .EQ. 0.0) THEN
        temp0d = 0.0_8
      ELSE
        temp0d = nx2*c2xd0/(2.0*temp3)
      END IF
      temp0 = temp3
      IF (nx2*c2x .EQ. 0.0) THEN
        sqd = 0.0_8
        sqdd = 0.0_8
      ELSE
        temp3 = c2xd/(2.0*temp0)
        sqdd = nx2*(c2xdd-temp3*2.0*temp0d)/(2.0*temp0)
        sqd = nx2*temp3
      END IF
      sqd0 = temp0d
      sq = temp0
!
      rspecdd = abdd + sqdd
      rspecd = abd + sqd
      rspecd0 = abd0 + sqd0
      rspec = ab + sq
!
      rspecbisdd = rspecdd
      rspecbisd = rspecd
      rspecbisd0 = rspecd0
      rspecbis = rspec
      IF (rspec .LT. rspecbis) THEN
        rspecdd = rspecbisdd
        rspecd = rspecbisd
        rspecd0 = rspecbisd0
        rspec = rspecbis
      ELSE
        rspec = rspec
      END IF
      sqbisdd = sqdd
      sqbisd = sqd
      sqbisd0 = sqd0
      sqbis = sq
      IF (sq .LT. sqbis) THEN
        sqdd = sqbisdd
        sqd = sqbisd
        sqd0 = sqbisd0
        sq = sqbis
      ELSE
        sq = sq
      END IF
!1st direction
      DO l=j-gh,j+gh-1
!DIR$ IVDEP
        DO k=i-gh,i+gh-1
          IF (p(k-1, l) - two*p(k, l) + p(k+1, l) .GE. 0.) THEN
            abs0dd = pdd(k-1, l) - two*pdd(k, l) + pdd(k+1, l)
            abs0d = pd(k-1, l) - two*pd(k, l) + pd(k+1, l)
            abs0d0 = pd0(k-1, l) - two*pd0(k, l) + pd0(k+1, l)
            abs0 = p(k-1, l) - two*p(k, l) + p(k+1, l)
          ELSE
            abs0dd = two*pdd(k, l) - pdd(k-1, l) - pdd(k+1, l)
            abs0d = two*pd(k, l) - pd(k-1, l) - pd(k+1, l)
            abs0d0 = two*pd0(k, l) - pd0(k-1, l) - pd0(k+1, l)
            abs0 = -(p(k-1, l)-two*p(k, l)+p(k+1, l))
          END IF
          x3dd = pdd(k-1, l) + two*pdd(k, l) + pdd(k+1, l)
          x3d = pd(k-1, l) + two*pd(k, l) + pd(k+1, l)
          x3d0 = pd0(k-1, l) + two*pd0(k, l) + pd0(k+1, l)
          x3 = p(k-1, l) + two*p(k, l) + p(k+1, l)
          IF (x3 .GE. 0.) THEN
            abs1dd = x3dd
            abs1d = x3d
            abs1d0 = x3d0
            abs1 = x3
          ELSE
            abs1dd = -x3dd
            abs1d = -x3d
            abs1d0 = -x3d0
            abs1 = -x3
          END IF
          temp3 = abs0*abs1d/abs1
          temp2 = (abs0d-temp3)/abs1
          k_sensor1dd = (abs0dd-(abs1d*abs0d0+abs0*abs1dd-temp3*abs1d0)/&
&           abs1-temp2*abs1d0)/abs1
          k_sensor1d = temp2
          k_sensor1d0 = (abs0d0-abs0*abs1d0/abs1)/abs1
          k_sensor1 = abs0/abs1
! k_sensor2 = ABS(p(k-2,l) - TWO*p(k-1,l) + p(k,l)) / &
!             ABS(p(k-2,l) + TWO*p(k-1,l) + p(k,l))
          temp3 = gradud(k, l, 1) + gradvd(k, l, 2)
          temp2 = gradu(k, l, 1) + gradv(k, l, 2)
          divu2dd = 2*(temp3*(gradud0(k, l, 1)+gradvd0(k, l, 2))+temp2*(&
&           gradudd(k, l, 1)+gradvdd(k, l, 2)))
          divu2d = 2*(temp2*temp3)
          divu2d0 = 2*(gradu(k, l, 1)+gradv(k, l, 2))*(gradud0(k, l, 1)+&
&           gradvd0(k, l, 2))
          divu2 = (gradu(k, l, 1)+gradv(k, l, 2))*(gradu(k, l, 1)+gradv(&
&           k, l, 2))
          temp3 = gradvd(k, l, 1) - gradud(k, l, 2)
          temp2 = gradv(k, l, 1) - gradu(k, l, 2)
          vort2dd = 2*(temp3*(gradvd0(k, l, 1)-gradud0(k, l, 2))+temp2*(&
&           gradvdd(k, l, 1)-gradudd(k, l, 2)))
          vort2d = 2*(temp2*temp3)
          vort2d0 = 2*(gradv(k, l, 1)-gradu(k, l, 2))*(gradvd0(k, l, 1)-&
&           gradud0(k, l, 2))
          vort2 = (gradv(k, l, 1)-gradu(k, l, 2))*(gradv(k, l, 1)-gradu(&
&           k, l, 2))
          temp3 = divu2/(divu2+vort2+1d-15)
          temp0d = (divu2d0-temp3*(divu2d0+vort2d0))/(divu2+vort2+1d-15)
          temp0 = temp3
          temp3 = (divu2d-temp0*(divu2d+vort2d))/(divu2+vort2+1d-15)
          ducros1dd = (divu2dd-(divu2d+vort2d)*temp0d-temp0*(divu2dd+&
&           vort2dd)-temp3*(divu2d0+vort2d0))/(divu2+vort2+1d-15)
          ducros1d = temp3
          ducros1d0 = temp0d
          ducros1 = temp0
          temp0 = 10.d0*vol(k, l)
          temp3 = (gradu(k, l, 1)+gradv(k, l, 2))/(sq+1d-15)
          tempd = (gradud0(k, l, 1)+gradvd0(k, l, 2)-temp3*sqd0)/(sq+&
&           1d-15)
          temp = temp3
          temp3 = (gradud(k, l, 1)+gradvd(k, l, 2)-temp*sqd)/(sq+1d-15)
          arg1dd = temp0*(gradudd(k, l, 1)+gradvdd(k, l, 2)-sqd*tempd-&
&           temp*sqdd-temp3*sqd0)/(sq+1d-15)
          arg1d = temp0*temp3
          arg1d0 = temp0*tempd
          arg1 = temp0*temp + 2.5d0
          temp3 = -(TANH(arg1)*TANH(arg1)) + 1.0
          dxm1dd = -(half*(temp3*arg1dd-arg1d*2*TANH(arg1)*(1.0-TANH(&
&           arg1)**2)*arg1d0))
          dxm1d = -(half*(temp3*arg1d))
          dxm1d0 = -(half*(1.0-TANH(arg1)**2)*arg1d0)
          dxm1 = half*(one-TANH(arg1))
! divu2     = (gradu(k-1,l,1)+gradv(k-1,l,2)) * (gradu(k-1,l,1)+gradv(k-1,l,2))
! vort2     = (gradv(k-1,l,1)-gradu(k-1,l,2)) * (gradv(k-1,l,1)-gradu(k-1,l,2))
! ducros2   = divu2/(divu2+vort2+1d-15)
! dxm2       = HALF*(ONE-tanh(2.5d0+10.d0*vol(k,l)/(sq+1d-15)*(gradu(k-1,l,1)+gradv(k-1,l,2))) )
! coef      = MAX( k_sensor1*ducros1, &
!                  k_sensor2*ducros2)
! coef      = MAX( k_sensor1*ducros1*dxm1, &
!                  k_sensor2*ducros2*dxm2)
          temp3 = ducros1*k_sensor1d + k_sensor1*ducros1d
          coefdd = temp3*dxm1d0 + dxm1*(k_sensor1d*ducros1d0+ducros1*&
&           k_sensor1dd+ducros1d*k_sensor1d0+k_sensor1*ducros1dd) + &
&           dxm1d*(ducros1*k_sensor1d0+k_sensor1*ducros1d0) + k_sensor1*&
&           ducros1*dxm1dd
          coefd = dxm1*temp3 + k_sensor1*ducros1*dxm1d
          coefd0 = dxm1*(ducros1*k_sensor1d0+k_sensor1*ducros1d0) + &
&           k_sensor1*ducros1*dxm1d0
          coef = k_sensor1*ducros1*dxm1
          eps2arradd(k, l) = k2*coefdd
          eps2arrad(k, l) = k2*coefd
          eps2arrad0(k, l) = k2*coefd0
          eps2arra(k, l) = k2*coef
        END DO
      END DO
      IF (eps2arra(i, j-2) .LT. eps2arra(i, j-3)) THEN
        y13dd = eps2arradd(i, j-3)
        y13d = eps2arrad(i, j-3)
        y13d0 = eps2arrad0(i, j-3)
        y13 = eps2arra(i, j-3)
      ELSE
        y13dd = eps2arradd(i, j-2)
        y13d = eps2arrad(i, j-2)
        y13d0 = eps2arrad0(i, j-2)
        y13 = eps2arra(i, j-2)
      END IF
      IF (eps2arra(i, j+2) .LT. y13) THEN
        y12dd = y13dd
        y12d = y13d
        y12d0 = y13d0
        y12 = y13
      ELSE
        y12dd = eps2arradd(i, j+2)
        y12d = eps2arrad(i, j+2)
        y12d0 = eps2arrad0(i, j+2)
        y12 = eps2arra(i, j+2)
      END IF
      IF (eps2arra(i-3, j) .LT. y12) THEN
        y11dd = y12dd
        y11d = y12d
        y11d0 = y12d0
        y11 = y12
      ELSE
        y11dd = eps2arradd(i-3, j)
        y11d = eps2arrad(i-3, j)
        y11d0 = eps2arrad0(i-3, j)
        y11 = eps2arra(i-3, j)
      END IF
      IF (eps2arra(i-2, j) .LT. y11) THEN
        y10dd = y11dd
        y10d = y11d
        y10d0 = y11d0
        y10 = y11
      ELSE
        y10dd = eps2arradd(i-2, j)
        y10d = eps2arrad(i-2, j)
        y10d0 = eps2arrad0(i-2, j)
        y10 = eps2arra(i-2, j)
      END IF
      IF (eps2arra(i+2, j) .LT. y10) THEN
        y9dd = y10dd
        y9d = y10d
        y9d0 = y10d0
        y9 = y10
      ELSE
        y9dd = eps2arradd(i+2, j)
        y9d = eps2arrad(i+2, j)
        y9d0 = eps2arrad0(i+2, j)
        y9 = eps2arra(i+2, j)
      END IF
      IF (eps2arra(i-1, j-1) .LT. y9) THEN
        y8dd = y9dd
        y8d = y9d
        y8d0 = y9d0
        y8 = y9
      ELSE
        y8dd = eps2arradd(i-1, j-1)
        y8d = eps2arrad(i-1, j-1)
        y8d0 = eps2arrad0(i-1, j-1)
        y8 = eps2arra(i-1, j-1)
      END IF
      IF (eps2arra(i-1, j+1) .LT. y8) THEN
        y7dd = y8dd
        y7d = y8d
        y7d0 = y8d0
        y7 = y8
      ELSE
        y7dd = eps2arradd(i-1, j+1)
        y7d = eps2arrad(i-1, j+1)
        y7d0 = eps2arrad0(i-1, j+1)
        y7 = eps2arra(i-1, j+1)
      END IF
      IF (eps2arra(i+1, j-1) .LT. y7) THEN
        y6dd = y7dd
        y6d = y7d
        y6d0 = y7d0
        y6 = y7
      ELSE
        y6dd = eps2arradd(i+1, j-1)
        y6d = eps2arrad(i+1, j-1)
        y6d0 = eps2arrad0(i+1, j-1)
        y6 = eps2arra(i+1, j-1)
      END IF
      IF (eps2arra(i+1, j+1) .LT. y6) THEN
        y5dd = y6dd
        y5d = y6d
        y5d0 = y6d0
        y5 = y6
      ELSE
        y5dd = eps2arradd(i+1, j+1)
        y5d = eps2arrad(i+1, j+1)
        y5d0 = eps2arrad0(i+1, j+1)
        y5 = eps2arra(i+1, j+1)
      END IF
      IF (eps2arra(i, j+1) .LT. y5) THEN
        y4dd = y5dd
        y4d = y5d
        y4d0 = y5d0
        y4 = y5
      ELSE
        y4dd = eps2arradd(i, j+1)
        y4d = eps2arrad(i, j+1)
        y4d0 = eps2arrad0(i, j+1)
        y4 = eps2arra(i, j+1)
      END IF
      IF (eps2arra(i+1, j) .LT. y4) THEN
        y3dd = y4dd
        y3d = y4d
        y3d0 = y4d0
        y3 = y4
      ELSE
        y3dd = eps2arradd(i+1, j)
        y3d = eps2arrad(i+1, j)
        y3d0 = eps2arrad0(i+1, j)
        y3 = eps2arra(i+1, j)
      END IF
      IF (eps2arra(i, j-1) .LT. y3) THEN
        y2dd = y3dd
        y2d = y3d
        y2d0 = y3d0
        y2 = y3
      ELSE
        y2dd = eps2arradd(i, j-1)
        y2d = eps2arrad(i, j-1)
        y2d0 = eps2arrad0(i, j-1)
        y2 = eps2arra(i, j-1)
      END IF
      IF (eps2arra(i-1, j) .LT. y2) THEN
        y1dd = y2dd
        y1d = y2d
        y1d0 = y2d0
        y1 = y2
      ELSE
        y1dd = eps2arradd(i-1, j)
        y1d = eps2arrad(i-1, j)
        y1d0 = eps2arrad0(i-1, j)
        y1 = eps2arra(i-1, j)
      END IF
      IF (eps2arra(i, j) .LT. y1) THEN
        eps2dd = y1dd
        eps2d = y1d
        eps2d0 = y1d0
        eps2 = y1
      ELSE
        eps2dd = eps2arradd(i, j)
        eps2d = eps2arrad(i, j)
        eps2d0 = eps2arrad0(i, j)
        eps2 = eps2arra(i, j)
      END IF
      IF (zero .LT. k4 - 12.d0*eps2) THEN
        eps4dd = -(12.d0*eps2dd)
        eps4d = -(12.d0*eps2d)
        eps4d0 = -(12.d0*eps2d0)
        eps4 = k4 - 12.d0*eps2
      ELSE
        eps4 = zero
        eps4d = 0.0_8
        eps4dd = 0.0_8
        eps4d0 = 0.0_8
      END IF
! eps4      = MAX(ZERO,k4 - 3.d0/70.d0 * eps2)
      diffrod = wd(i, j, 1) - wd(i-1, j, 1)
      diffrod0 = wd0(i, j, 1) - wd0(i-1, j, 1)
      diffro = w(i, j, 1) - w(i-1, j, 1)
      diffroud = wd(i, j, 2) - wd(i-1, j, 2)
      diffroud0 = wd0(i, j, 2) - wd0(i-1, j, 2)
      diffrou = w(i, j, 2) - w(i-1, j, 2)
      diffrovd = wd(i, j, 3) - wd(i-1, j, 3)
      diffrovd0 = wd0(i, j, 3) - wd0(i-1, j, 3)
      diffrov = w(i, j, 3) - w(i-1, j, 3)
      diffrowd = wd(i, j, 4) - wd(i-1, j, 4)
      diffrowd0 = wd0(i, j, 4) - wd0(i-1, j, 4)
      diffrow = w(i, j, 4) - w(i-1, j, 4)
      diffroed = wd(i, j, 5) - wd(i-1, j, 5)
      diffroed0 = wd0(i, j, 5) - wd0(i-1, j, 5)
      diffroe = w(i, j, 5) - w(i-1, j, 5)
!
      temp0d = diffro*eps2d0 + eps2*diffrod0 + predro1*eps4d0 + eps4*&
&       predro1d0
      temp0 = eps2*diffro + eps4*predro1
      temp3 = diffro*eps2d + diffrod*eps2 + predro1*eps4d + predro1d*&
&       eps4
      dissro1dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec*&
&       (eps2d*diffrod0+diffro*eps2dd+diffrod*eps2d0+eps4d*predro1d0+&
&       predro1*eps4dd+predro1d*eps4d0)
      temp0d = diffrou*eps2d0 + eps2*diffroud0 + predrou1*eps4d0 + eps4*&
&       predrou1d0
      temp0 = eps2*diffrou + eps4*predrou1
      temp3 = diffrou*eps2d + diffroud*eps2 + predrou1*eps4d + predrou1d&
&       *eps4
      dissrou1dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffroud0+diffrou*eps2dd+diffroud*eps2d0+eps4d*&
&       predrou1d0+predrou1*eps4dd+predrou1d*eps4d0)
      temp0d = diffrov*eps2d0 + eps2*diffrovd0 + predrov1*eps4d0 + eps4*&
&       predrov1d0
      temp0 = eps2*diffrov + eps4*predrov1
      temp3 = diffrov*eps2d + diffrovd*eps2 + predrov1*eps4d + predrov1d&
&       *eps4
      dissrov1dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffrovd0+diffrov*eps2dd+diffrovd*eps2d0+eps4d*&
&       predrov1d0+predrov1*eps4dd+predrov1d*eps4d0)
      temp0d = diffrow*eps2d0 + eps2*diffrowd0 + predrow1*eps4d0 + eps4*&
&       predrow1d0
      temp0 = eps2*diffrow + eps4*predrow1
      temp3 = diffrow*eps2d + diffrowd*eps2 + predrow1*eps4d + predrow1d&
&       *eps4
      dissrow1dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffrowd0+diffrow*eps2dd+diffrowd*eps2d0+eps4d*&
&       predrow1d0+predrow1*eps4dd+predrow1d*eps4d0)
      temp0d = diffroe*eps2d0 + eps2*diffroed0 + predroe1*eps4d0 + eps4*&
&       predroe1d0
      temp0 = eps2*diffroe + eps4*predroe1
      temp3 = diffroe*eps2d + diffroed*eps2 + predroe1*eps4d + predroe1d&
&       *eps4
      dissroe1dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffroed0+diffroe*eps2dd+diffroed*eps2d0+eps4d*&
&       predroe1d0+predroe1*eps4dd+predroe1d*eps4d0)
      diffrod = wd(i, j, 1) - wd(i, j-1, 1)
      diffrod0 = wd0(i, j, 1) - wd0(i, j-1, 1)
      diffro = w(i, j, 1) - w(i, j-1, 1)
      diffroud = wd(i, j, 2) - wd(i, j-1, 2)
      diffroud0 = wd0(i, j, 2) - wd0(i, j-1, 2)
      diffrou = w(i, j, 2) - w(i, j-1, 2)
      diffrovd = wd(i, j, 3) - wd(i, j-1, 3)
      diffrovd0 = wd0(i, j, 3) - wd0(i, j-1, 3)
      diffrov = w(i, j, 3) - w(i, j-1, 3)
      diffrowd = wd(i, j, 4) - wd(i, j-1, 4)
      diffrowd0 = wd0(i, j, 4) - wd0(i, j-1, 4)
      diffrow = w(i, j, 4) - w(i, j-1, 4)
      diffroed = wd(i, j, 5) - wd(i, j-1, 5)
      diffroed0 = wd0(i, j, 5) - wd0(i, j-1, 5)
      diffroe = w(i, j, 5) - w(i, j-1, 5)
      temp0d = diffro*eps2d0 + eps2*diffrod0 + predro2*eps4d0 + eps4*&
&       predro2d0
      temp0 = eps2*diffro + eps4*predro2
      temp3 = diffro*eps2d + diffrod*eps2 + predro2*eps4d + predro2d*&
&       eps4
      dissro2dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec*&
&       (eps2d*diffrod0+diffro*eps2dd+diffrod*eps2d0+eps4d*predro2d0+&
&       predro2*eps4dd+predro2d*eps4d0)
      temp0d = diffrou*eps2d0 + eps2*diffroud0 + predrou2*eps4d0 + eps4*&
&       predrou2d0
      temp0 = eps2*diffrou + eps4*predrou2
      temp3 = diffrou*eps2d + diffroud*eps2 + predrou2*eps4d + predrou2d&
&       *eps4
      dissrou2dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffroud0+diffrou*eps2dd+diffroud*eps2d0+eps4d*&
&       predrou2d0+predrou2*eps4dd+predrou2d*eps4d0)
      temp0d = diffrov*eps2d0 + eps2*diffrovd0 + predrov2*eps4d0 + eps4*&
&       predrov2d0
      temp0 = eps2*diffrov + eps4*predrov2
      temp3 = diffrov*eps2d + diffrovd*eps2 + predrov2*eps4d + predrov2d&
&       *eps4
      dissrov2dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffrovd0+diffrov*eps2dd+diffrovd*eps2d0+eps4d*&
&       predrov2d0+predrov2*eps4dd+predrov2d*eps4d0)
      temp0d = diffrow*eps2d0 + eps2*diffrowd0 + predrow2*eps4d0 + eps4*&
&       predrow2d0
      temp0 = eps2*diffrow + eps4*predrow2
      temp3 = diffrow*eps2d + diffrowd*eps2 + predrow2*eps4d + predrow2d&
&       *eps4
      dissrow2dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffrowd0+diffrow*eps2dd+diffrowd*eps2d0+eps4d*&
&       predrow2d0+predrow2*eps4dd+predrow2d*eps4d0)
      temp0d = diffroe*eps2d0 + eps2*diffroed0 + predroe2*eps4d0 + eps4*&
&       predroe2d0
      temp0 = eps2*diffroe + eps4*predroe2
      temp3 = diffroe*eps2d + diffroed*eps2 + predroe2*eps4d + predroe2d&
&       *eps4
      dissroe2dd = rspecd*temp0d + temp0*rspecdd + temp3*rspecd0 + rspec&
&       *(eps2d*diffroed0+diffroe*eps2dd+diffroed*eps2d0+eps4d*&
&       predroe2d0+predroe2*eps4dd+predroe2d*eps4d0)
      sc1 = nx(i, j, 1)
      sc2 = ny(i, j, 1)
      arg1 = sc1*sc1 + sc2*sc2
      sn = SQRT(arg1)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
      hndd(i, j, 1, 1) = fxro1dd - dissro1dd
!
      hndd(i, j, 2, 1) = fxrou1dd - dissrou1dd - sn*(nxloc*fvrou1dd+&
&       nyloc*gvrou1dd)
!
      hndd(i, j, 3, 1) = fxrov1dd - dissrov1dd - sn*(nxloc*fvrov1dd+&
&       nyloc*gvrov1dd)
!
      hndd(i, j, 4, 1) = fxrow1dd - dissrow1dd - sn*(nxloc*fvrow1dd+&
&       nyloc*gvrow1dd)
!
      hndd(i, j, 5, 1) = fxroe1dd - dissroe1dd - sn*(nxloc*fvroe1dd+&
&       nyloc*gvroe1dd)
      sc1 = nx(i, j, 2)
      sc2 = ny(i, j, 2)
      arg1 = sc1*sc1 + sc2*sc2
      sn = SQRT(arg1)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
      hndd(i, j, 1, 2) = fxro2dd - dissro2dd
!
      hndd(i, j, 2, 2) = fxrou2dd - dissrou2dd - sn*(nxloc*fvrou2dd+&
&       nyloc*gvrou2dd)
!
      hndd(i, j, 3, 2) = fxrov2dd - dissrov2dd - sn*(nxloc*fvrov2dd+&
&       nyloc*gvrov2dd)
!
      hndd(i, j, 4, 2) = fxrow2dd - dissrow2dd - sn*(nxloc*fvrow2dd+&
&       nyloc*gvrow2dd)
!
      hndd(i, j, 5, 2) = fxroe2dd - dissroe2dd - sn*(nxloc*fvroe2dd+&
&       nyloc*gvroe2dd)
    END DO
  END DO
  residudd = 0.0_8
!
! fluxes balance
  DO j=1,jm
!DIR$ IVDEP
    DO i=1,im
      residudd(i, j, 1) = hndd(i, j, 1, 1) - hndd(i+1, j, 1, 1) + hndd(i&
&       , j, 1, 2) - hndd(i, j+1, 1, 2)
      residudd(i, j, 2) = hndd(i, j, 2, 1) - hndd(i+1, j, 2, 1) + hndd(i&
&       , j, 2, 2) - hndd(i, j+1, 2, 2)
      residudd(i, j, 3) = hndd(i, j, 3, 1) - hndd(i+1, j, 3, 1) + hndd(i&
&       , j, 3, 2) - hndd(i, j+1, 3, 2)
      residudd(i, j, 4) = hndd(i, j, 4, 1) - hndd(i+1, j, 4, 1) + hndd(i&
&       , j, 4, 2) - hndd(i, j+1, 4, 2)
      residudd(i, j, 5) = hndd(i, j, 5, 1) - hndd(i+1, j, 5, 1) + hndd(i&
&       , j, 5, 2) - hndd(i, j+1, 5, 2)
    END DO
  END DO
END SUBROUTINE FLUX_NUM_DNC5_MAXSC_2D_D_D
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

