! This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of flux_num_dnc5_nowall_nodiss_2d_d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDe
!adInstrs with!StaticTaping):
!   variations   of useful results: residud
!   with respect to varying inputs: w
!   RW status of diff variables: w:in residud:out
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of flux_num_dnc5_nowall_nodiss_2d in forward (tangent) mode (with options with!SliceDeadControl with!SliceDead
!Instrs with!StaticTaping):
!   variations   of useful results: residu
!   with respect to varying inputs: w
!   RW status of diff variables: w:in residu:out
! =============================================================================
!          consistent fluxes for DNC5 2D
! =============================================================================
!
SUBROUTINE FLUX_NUM_DNC5_NOWALL_NODISS_2D_D_D(residu, residud, residudd&
& , w, wd0, wd, x0, y0, nx, ny, xc, yc, vol, volf, gh, cp, cv, prandtl, &
& gam, rgaz, cs, muref, tref, s_suth, k2, k4, im, jm)
  IMPLICIT NONE
! variables for dimension -----------------------------------------
  INTEGER :: im, jm, gh
! required arguments ----------------------------------------------
! thermo
  REAL*8, INTENT(IN) :: cp, cv, prandtl, gam, rgaz
! dissipation
  REAL*8, INTENT(IN) :: k2, k4
! viscosity
  REAL*8, INTENT(IN) :: cs, muref, tref, s_suth
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: x0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: y0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: nx
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: ny
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: xc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: yc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: vol
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2), INTENT(IN) :: volf
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: w
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: wd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: wd
! Returned objects ------------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residud
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: &
& residudd
! Non-required arguments -------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hn
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hnd
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hndd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: f, g
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: fd, gd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: fdd, gdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velx
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: vely
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velyd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velyd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velydd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velz
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tloc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: p
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pd0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pdd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mud0
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mud
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mudd
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradu, gradv, gradw, &
& gradmu
  REAL*8, DIMENSION(5) :: deltar, deltal, t
  INTEGER :: i, j, h
  REAL*8 :: nx_n, nx_s, nx_e, nx_o, volm1, ux, vx, wx, tx
  REAL*8 :: uxd0, vxd0, wxd0, txd0
  REAL*8 :: uxd, vxd, wxd, txd
  REAL*8 :: uxdd, vxdd, wxdd, txdd
  REAL*8 :: ny_n, ny_s, ny_e, ny_o, uy, vy, wy, ty
  REAL*8 :: uyd0, vyd0, wyd0, tyd0
  REAL*8 :: uyd, vyd, wyd, tyd
  REAL*8 :: uydd, vydd, wydd, tydd
  REAL*8 :: val_n, val_s, val_e, val_o
  REAL*8 :: val_nd0, val_sd0, val_ed0, val_od0
  REAL*8 :: val_nd, val_sd, val_ed, val_od
  REAL*8 :: val_ndd, val_sdd, val_edd, val_odd
  REAL*8 :: fxro1, fxro2, fxrou1, fxrou2, fxrov1, fxrov2, fxrow1, fxrow2&
& , fxroe1, fxroe2
  REAL*8 :: fxro1d, fxro2d, fxrou1d, fxrou2d, fxrov1d, fxrov2d, fxrow1d&
& , fxrow2d, fxroe1d, fxroe2d
  REAL*8 :: fxro1dd, fxro2dd, fxrou1dd, fxrou2dd, fxrov1dd, fxrov2dd, &
& fxrow1dd, fxrow2dd, fxroe1dd, fxroe2dd
  REAL*8 :: fvro1, fvro2, fvrou1, fvrou2, fvrov1, fvrov2, fvrow1, fvrow2&
& , fvroe1, fvroe2
  REAL*8 :: fvrou1d0, fvrou2d0, fvrov1d0, fvrov2d0, fvrow1d0, fvrow2d0
  REAL*8 :: fvrou1d, fvrou2d, fvrov1d, fvrov2d, fvrow1d, fvrow2d, &
& fvroe1d, fvroe2d
  REAL*8 :: fvrou1dd, fvrou2dd, fvrov1dd, fvrov2dd, fvrow1dd, fvrow2dd, &
& fvroe1dd, fvroe2dd
  REAL*8 :: gvro1, gvro2, gvrou1, gvrou2, gvrov1, gvrov2, gvrow1, gvrow2&
& , gvroe1, gvroe2
  REAL*8 :: gvrou1d0, gvrou2d0, gvrov1d0, gvrov2d0, gvrow1d0, gvrow2d0
  REAL*8 :: gvrou1d, gvrou2d, gvrov1d, gvrov2d, gvrow1d, gvrow2d, &
& gvroe1d, gvroe2d
  REAL*8 :: gvrou1dd, gvrou2dd, gvrov1dd, gvrov2dd, gvrow1dd, gvrow2dd, &
& gvroe1dd, gvroe2dd
  REAL*8 :: dissro1, dissro2, dissrou1, dissrou2, dissrov1, dissrov2, &
& dissrow1, dissrow2, dissroe1, dissroe2
  REAL*8 :: cpprandtl, mmu, lambda, uu, vv, ww, ro, rom1, htot, eloc, ec
  REAL*8 :: mmud0, lambdad0, uud0, vvd0, wwd0, rod0, rom1d0, htotd0, &
& elocd0, ecd0
  REAL*8 :: mmud, lambdad, uud, vvd, wwd, rod, rom1d, htotd, elocd, ecd
  REAL*8 :: mmudd, lambdadd, uudd, vvdd, wwdd, rom1dd, htotdd, elocdd, &
& ecdd
  REAL*8 :: predro1, predrou1, predrov1, predrow1, predroe1, eps2, eps4
  REAL*8 :: predro2, predrou2, predrov2, predrow2, predroe2, rspec
  REAL*8 :: divu, divu2, vort2, dx, dy, dxm1, dym1, dxm2, dym2
  REAL*8 :: nxloc, nyloc, sn, invsn, sc1, sc2
  REAL*8 :: gui, gvi, gwi, gmui
  REAL*8 :: guj, gvj, gwj, gmuj
  REAL*8 :: rhom, rhomr, rhoml, rhom1l, c2l, c2r, rr, r, u, ur, ul, vr, &
& vl, wr, wl, c2x, nx2, ny2
  REAL*8 :: ab, sq, ducros1, ducros2, k_sensor1, k_sensor2
  REAL*8 :: b1, b2, b3, b4, b5, c1, c2, c3, c4, c5, d1, d2, d3, wiggle, &
& denom, betas
  REAL*8 :: omrr, coef, test, diffro, diffrou, diffrov, diffrow, diffroe&
& , v
  REAL*8 :: half, one, zero, two, twothird, fourth, twelfth, cvm1
  REAL*8 :: twentyfourth, ccross
  REAL*8 :: mach2, alpha, vn2, cprim
  INTRINSIC SQRT
  REAL*8 :: result1
  REAL*8 :: result1d0
  REAL*8 :: result1d
  REAL*8 :: result1dd
  REAL*8 :: arg1
  REAL*8 :: temp
  REAL*8 :: tempd
  REAL*8 :: temp0
  REAL*8 :: temp1
  REAL*8 :: temp2
! -----------------------------------------------------------------
!
  half = 0.5d0
  one = 1.d0
  two = 2.d0
  twothird = 2.d0/3.d0
  twelfth = 0.25d0/3.d0
  cpprandtl = cp/prandtl
  cvm1 = one/cv
  twentyfourth = one/24.d0
  ccross = twelfth*0.0625d0
! k2 = 1.d0
! k4 = 1.d0/60d0 already in coef for predictor
! Coef for grad o6
  denom = 1.d0/60.d0
!expression for FV
! c3 = b3
! c2 = c3 + b2
! c1 = c2 + b1
  c1 = 37.d0*denom
  c2 = -(8.d0*denom)
  c3 = denom
!predictor
! for Sutherland
  result1 = SQRT(tref)
  betas = muref*(tref+cs)/(result1*tref)
  velxd = 0.0_8
  velyd = 0.0_8
  velzd = 0.0_8
  tlocd = 0.0_8
  mud = 0.0_8
  tlocdd = 0.0_8
  velydd = 0.0_8
  pd0 = 0.0_8
  velzdd = 0.0_8
  fdd = 0.0_8
  velxd0 = 0.0_8
  velyd0 = 0.0_8
  velzd0 = 0.0_8
  pdd = 0.0_8
  mudd = 0.0_8
  velxdd = 0.0_8
  tlocd0 = 0.0_8
  gdd = 0.0_8
  mud0 = 0.0_8
! Primitives
  DO j=1-gh,jm+gh
!GCC$ IVDEP
    DO i=1-gh,im+gh
      rod = wd(i, j, 1)
      rod0 = wd0(i, j, 1)
      ro = w(i, j, 1)
      temp0 = one*rod/(ro*ro)
      rom1dd = temp0*2*rod0/ro
      rom1d = -temp0
      rom1d0 = -(one*rod0/ro**2)
      rom1 = one/ro
      velxdd(i, j) = wd(i, j, 2)*rom1d0 + rom1d*wd0(i, j, 2) + w(i, j, 2&
&       )*rom1dd
      velxd(i, j) = rom1*wd(i, j, 2) + w(i, j, 2)*rom1d
      velxd0(i, j) = rom1*wd0(i, j, 2) + w(i, j, 2)*rom1d0
      velx(i, j) = w(i, j, 2)*rom1
      velydd(i, j) = wd(i, j, 3)*rom1d0 + rom1d*wd0(i, j, 3) + w(i, j, 3&
&       )*rom1dd
      velyd(i, j) = rom1*wd(i, j, 3) + w(i, j, 3)*rom1d
      velyd0(i, j) = rom1*wd0(i, j, 3) + w(i, j, 3)*rom1d0
      vely(i, j) = w(i, j, 3)*rom1
      velzdd(i, j) = wd(i, j, 4)*rom1d0 + rom1d*wd0(i, j, 4) + w(i, j, 4&
&       )*rom1dd
      velzd(i, j) = rom1*wd(i, j, 4) + w(i, j, 4)*rom1d
      velzd0(i, j) = rom1*wd0(i, j, 4) + w(i, j, 4)*rom1d0
      velz(i, j) = w(i, j, 4)*rom1
!
      temp0 = 2*velx(i, j)
      temp1 = 2*vely(i, j)
      temp2 = 2*velz(i, j)
      ecdd = half*(velxd(i, j)*2*velxd0(i, j)+temp0*velxdd(i, j)+velyd(i&
&       , j)*2*velyd0(i, j)+temp1*velydd(i, j)+velzd(i, j)*2*velzd0(i, j&
&       )+temp2*velzdd(i, j))
      ecd = half*(temp0*velxd(i, j)+temp1*velyd(i, j)+temp2*velzd(i, j))
      ecd0 = half*(2*velx(i, j)*velxd0(i, j)+2*vely(i, j)*velyd0(i, j)+2&
&       *velz(i, j)*velzd0(i, j))
      ec = half*(velx(i, j)*velx(i, j)+vely(i, j)*vely(i, j)+velz(i, j)*&
&       velz(i, j))
! ec  = HALF*( velx(i,j)*velx(i,j) &
!            + vely(i,j)*vely(i,j))
!
      tempd = wd0(i, j, 5) - ro*ecd0 - ec*rod0
      temp = w(i, j, 5) - ec*ro
      temp2 = wd(i, j, 5) - ro*ecd - rod*ec
      elocdd = temp2*rom1d0 + rom1*(-(ecd*rod0)-ro*ecdd-rod*ecd0) + &
&       rom1d*tempd + temp*rom1dd
      elocd = rom1*temp2 + temp*rom1d
      elocd0 = rom1*tempd + temp*rom1d0
      eloc = temp*rom1
!
      tlocdd(i, j) = cvm1*elocdd
      tlocd(i, j) = cvm1*elocd
      tlocd0(i, j) = cvm1*elocd0
      tloc(i, j) = eloc*cvm1
!
      pdd(i, j) = (gam-one)*(rod*elocd0+elocd*rod0+ro*elocdd)
      pd(i, j) = (gam-one)*(eloc*rod+ro*elocd)
      pd0(i, j) = (gam-one)*(eloc*rod0+ro*elocd0)
      p(i, j) = (gam-one)*ro*eloc
!  p(i,j)  = ro*rgaz*tloc(i,j)
      tempd = wd0(i, j, 5) + pd0(i, j)
      temp = w(i, j, 5) + p(i, j)
      temp2 = wd(i, j, 5) + pd(i, j)
      htotdd = temp2*rom1d0 + rom1*pdd(i, j) + rom1d*tempd + temp*rom1dd
      htotd = rom1*temp2 + temp*rom1d
      htotd0 = rom1*tempd + temp*rom1d0
      fdd(i, j, 1) = 0.0_8
      fdd(i, j, 2) = wd(i, j, 2)*velxd0(i, j) + velxd(i, j)*wd0(i, j, 2)&
&       + w(i, j, 2)*velxdd(i, j) + pdd(i, j)
      fdd(i, j, 3) = wd(i, j, 2)*velyd0(i, j) + velyd(i, j)*wd0(i, j, 2)&
&       + w(i, j, 2)*velydd(i, j)
      fdd(i, j, 4) = wd(i, j, 2)*velzd0(i, j) + velzd(i, j)*wd0(i, j, 2)&
&       + w(i, j, 2)*velzdd(i, j)
      fdd(i, j, 5) = wd(i, j, 2)*htotd0 + htotd*wd0(i, j, 2) + w(i, j, 2&
&       )*htotdd
      gdd(i, j, 1) = 0.0_8
      gdd(i, j, 2) = wd(i, j, 3)*velxd0(i, j) + velxd(i, j)*wd0(i, j, 3)&
&       + w(i, j, 3)*velxdd(i, j)
      gdd(i, j, 3) = wd(i, j, 3)*velyd0(i, j) + velyd(i, j)*wd0(i, j, 3)&
&       + w(i, j, 3)*velydd(i, j) + pdd(i, j)
      gdd(i, j, 4) = wd(i, j, 3)*velzd0(i, j) + velzd(i, j)*wd0(i, j, 3)&
&       + w(i, j, 3)*velzdd(i, j)
      gdd(i, j, 5) = wd(i, j, 3)*htotd0 + htotd*wd0(i, j, 3) + w(i, j, 3&
&       )*htotdd
!h(i,j,1)  = w(i,j,4)
!h(i,j,2)  = w(i,j,4) * velx(i,j)
!h(i,j,3)  = w(i,j,4) * vely(i,j)
!h(i,j,4)  = w(i,j,4) * velz(i,j) + p(i,j)
!h(i,j,5)  = w(i,j,4) * htot
      temp2 = SQRT(tloc(i, j))
      IF (tloc(i, j) .EQ. 0.0) THEN
        tempd = 0.0_8
      ELSE
        tempd = tlocd0(i, j)/(2.0*temp2)
      END IF
      temp = temp2
      IF (tloc(i, j) .EQ. 0.0) THEN
        result1d = 0.0_8
        result1dd = 0.0_8
      ELSE
        temp2 = tlocd(i, j)/(2.0*temp)
        result1dd = (tlocdd(i, j)-temp2*2.0*tempd)/(2.0*temp)
        result1d = temp2
      END IF
      result1d0 = tempd
      result1 = temp
      temp2 = result1*tloc(i, j)/(s_suth+tloc(i, j))
      tempd = (tloc(i, j)*result1d0+(result1-temp2)*tlocd0(i, j))/(&
&       s_suth+tloc(i, j))
      temp = temp2
      temp2 = (tloc(i, j)*result1d+(result1-temp)*tlocd(i, j))/(s_suth+&
&       tloc(i, j))
      mudd(i, j) = betas*((result1d-temp2)*tlocd0(i, j)+tloc(i, j)*&
&       result1dd+tlocd(i, j)*(result1d0-tempd)+(result1-temp)*tlocdd(i&
&       , j))/(s_suth+tloc(i, j))
      mud(i, j) = betas*temp2
      mud0(i, j) = betas*tempd
      mu(i, j) = betas*temp
    END DO
  END DO
  hndd = 0.0_8
  DO j=1,jm+1
!DIR$ IVDEP
    DO i=1,im+1
!
      fxro1dd = nx(i, j, 1)*(c1*(fdd(i, j, 1)+fdd(i-1, j, 1))+c2*(fdd(i+&
&       1, j, 1)+fdd(i-2, j, 1))+c3*(fdd(i+2, j, 1)+fdd(i-3, j, 1))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 1)+gdd(i-1, j, 1))+c2*(gdd(i+1, j, 1)&
&       +gdd(i-2, j, 1))+c3*(gdd(i+2, j, 1)+gdd(i-3, j, 1)))
      fxrou1dd = nx(i, j, 1)*(c1*(fdd(i, j, 2)+fdd(i-1, j, 2))+c2*(fdd(i&
&       +1, j, 2)+fdd(i-2, j, 2))+c3*(fdd(i+2, j, 2)+fdd(i-3, j, 2))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 2)+gdd(i-1, j, 2))+c2*(gdd(i+1, j, 2)&
&       +gdd(i-2, j, 2))+c3*(gdd(i+2, j, 2)+gdd(i-3, j, 2)))
      fxrov1dd = nx(i, j, 1)*(c1*(fdd(i, j, 3)+fdd(i-1, j, 3))+c2*(fdd(i&
&       +1, j, 3)+fdd(i-2, j, 3))+c3*(fdd(i+2, j, 3)+fdd(i-3, j, 3))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 3)+gdd(i-1, j, 3))+c2*(gdd(i+1, j, 3)&
&       +gdd(i-2, j, 3))+c3*(gdd(i+2, j, 3)+gdd(i-3, j, 3)))
      fxrow1dd = nx(i, j, 1)*(c1*(fdd(i, j, 4)+fdd(i-1, j, 4))+c2*(fdd(i&
&       +1, j, 4)+fdd(i-2, j, 4))+c3*(fdd(i+2, j, 4)+fdd(i-3, j, 4))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 4)+gdd(i-1, j, 4))+c2*(gdd(i+1, j, 4)&
&       +gdd(i-2, j, 4))+c3*(gdd(i+2, j, 4)+gdd(i-3, j, 4)))
      fxroe1dd = nx(i, j, 1)*(c1*(fdd(i, j, 5)+fdd(i-1, j, 5))+c2*(fdd(i&
&       +1, j, 5)+fdd(i-2, j, 5))+c3*(fdd(i+2, j, 5)+fdd(i-3, j, 5))) + &
&       ny(i, j, 1)*(c1*(gdd(i, j, 5)+gdd(i-1, j, 5))+c2*(gdd(i+1, j, 5)&
&       +gdd(i-2, j, 5))+c3*(gdd(i+2, j, 5)+gdd(i-3, j, 5)))
      fxro2dd = nx(i, j, 2)*(c1*(fdd(i, j, 1)+fdd(i, j-1, 1))+c2*(fdd(i&
&       , j+1, 1)+fdd(i, j-2, 1))+c3*(fdd(i, j+2, 1)+fdd(i, j-3, 1))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 1)+gdd(i, j-1, 1))+c2*(gdd(i, j+1, 1)&
&       +gdd(i, j-2, 1))+c3*(gdd(i, j+2, 1)+gdd(i, j-3, 1)))
      fxrou2dd = nx(i, j, 2)*(c1*(fdd(i, j, 2)+fdd(i, j-1, 2))+c2*(fdd(i&
&       , j+1, 2)+fdd(i, j-2, 2))+c3*(fdd(i, j+2, 2)+fdd(i, j-3, 2))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 2)+gdd(i, j-1, 2))+c2*(gdd(i, j+1, 2)&
&       +gdd(i, j-2, 2))+c3*(gdd(i, j+2, 2)+gdd(i, j-3, 2)))
      fxrov2dd = nx(i, j, 2)*(c1*(fdd(i, j, 3)+fdd(i, j-1, 3))+c2*(fdd(i&
&       , j+1, 3)+fdd(i, j-2, 3))+c3*(fdd(i, j+2, 3)+fdd(i, j-3, 3))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 3)+gdd(i, j-1, 3))+c2*(gdd(i, j+1, 3)&
&       +gdd(i, j-2, 3))+c3*(gdd(i, j+2, 3)+gdd(i, j-3, 3)))
      fxrow2dd = nx(i, j, 2)*(c1*(fdd(i, j, 4)+fdd(i, j-1, 4))+c2*(fdd(i&
&       , j+1, 4)+fdd(i, j-2, 4))+c3*(fdd(i, j+2, 4)+fdd(i, j-3, 4))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 4)+gdd(i, j-1, 4))+c2*(gdd(i, j+1, 4)&
&       +gdd(i, j-2, 4))+c3*(gdd(i, j+2, 4)+gdd(i, j-3, 4)))
      fxroe2dd = nx(i, j, 2)*(c1*(fdd(i, j, 5)+fdd(i, j-1, 5))+c2*(fdd(i&
&       , j+1, 5)+fdd(i, j-2, 5))+c3*(fdd(i, j+2, 5)+fdd(i, j-3, 5))) + &
&       ny(i, j, 2)*(c1*(gdd(i, j, 5)+gdd(i, j-1, 5))+c2*(gdd(i, j+1, 5)&
&       +gdd(i, j-2, 5))+c3*(gdd(i, j+2, 5)+gdd(i, j-3, 5)))
! grad for viscous fluxes o4 - 5p
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccros = TWELFTH*0.0625d0
      volm1 = volf(i, j, 1)
      nx_n = half*(nx(i+1, j, 1)+nx(i, j, 1))
      nx_s = -(half*(nx(i-1, j, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i-1, j+1, 2)+nx(i, j+1, 2))
      nx_e = -(half*(nx(i-1, j, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j, 1)+ny(i, j, 1))
      ny_s = -(half*(ny(i-1, j, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i-1, j+1, 2)+ny(i, j+1, 2))
      ny_e = -(half*(ny(i-1, j, 2)+ny(i, j, 2)))
      val_ndd = twentyfourth*(26.d0*velxdd(i, j)-velxdd(i+1, j)-velxdd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*velxd(i, j)-velxd(i+1, j)-velxd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*velxd0(i, j)-velxd0(i+1, j)-velxd0(i&
&       -1, j))
      val_n = twentyfourth*(-velx(i+1, j)+26.d0*velx(i, j)-velx(i-1, j))
      val_sdd = twentyfourth*(26.d0*velxdd(i-1, j)-velxdd(i, j)-velxdd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*velxd(i-1, j)-velxd(i, j)-velxd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*velxd0(i-1, j)-velxd0(i, j)-velxd0(i&
&       -2, j))
      val_s = twentyfourth*(-velx(i, j)+26.d0*velx(i-1, j)-velx(i-2, j))
      val_edd = ccross*(velxdd(i-2, j-2)-9.d0*velxdd(i-1, j-2)-9.d0*&
&       velxdd(i, j-2)+velxdd(i+1, j-2)+7.d0*(9.d0*velxdd(i-1, j-1)-&
&       velxdd(i-2, j-1)+9.d0*velxdd(i, j-1)-velxdd(i+1, j-1))+7.d0*(&
&       9.d0*velxdd(i-1, j)-velxdd(i-2, j)+9.d0*velxdd(i, j)-velxdd(i+1&
&       , j))+velxdd(i-2, j+1)-9.d0*velxdd(i-1, j+1)+velxdd(i+1, j+1)-&
&       9.d0*velxdd(i, j+1))
      val_ed = ccross*(velxd(i-2, j-2)-9.d0*velxd(i-1, j-2)-9.d0*velxd(i&
&       , j-2)+velxd(i+1, j-2)+7.d0*(9.d0*velxd(i-1, j-1)-velxd(i-2, j-1&
&       )+9.d0*velxd(i, j-1)-velxd(i+1, j-1))+7.d0*(9.d0*velxd(i-1, j)-&
&       velxd(i-2, j)+9.d0*velxd(i, j)-velxd(i+1, j))+velxd(i-2, j+1)-&
&       9.d0*velxd(i-1, j+1)+velxd(i+1, j+1)-9.d0*velxd(i, j+1))
      val_ed0 = ccross*(velxd0(i-2, j-2)-9.d0*velxd0(i-1, j-2)-9.d0*&
&       velxd0(i, j-2)+velxd0(i+1, j-2)+7.d0*(9.d0*velxd0(i-1, j-1)-&
&       velxd0(i-2, j-1)+9.d0*velxd0(i, j-1)-velxd0(i+1, j-1))+7.d0*(&
&       9.d0*velxd0(i-1, j)-velxd0(i-2, j)+9.d0*velxd0(i, j)-velxd0(i+1&
&       , j))+velxd0(i-2, j+1)-9.d0*velxd0(i-1, j+1)+velxd0(i+1, j+1)-&
&       9.d0*velxd0(i, j+1))
      val_e = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-1, j-2)+9.d0*velx(i&
&       , j-2)-velx(i+1, j-2))+7.d0*(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)&
&       +9.d0*velx(i, j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx&
&       (i-1, j)+9.d0*velx(i, j)-velx(i+1, j))-(-velx(i-2, j+1)+9.d0*&
&       velx(i-1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1)))
      val_odd = ccross*(velxdd(i-2, j-1)-9.d0*velxdd(i-1, j-1)-9.d0*&
&       velxdd(i, j-1)+velxdd(i+1, j-1)+7.d0*(9.d0*velxdd(i-1, j)-velxdd&
&       (i-2, j)+9.d0*velxdd(i, j)-velxdd(i+1, j))+7.d0*(9.d0*velxdd(i-1&
&       , j+1)-velxdd(i-2, j+1)+9.d0*velxdd(i, j+1)-velxdd(i+1, j+1))+&
&       velxdd(i-2, j+2)-9.d0*velxdd(i-1, j+2)+velxdd(i+1, j+2)-9.d0*&
&       velxdd(i, j+2))
      val_od = ccross*(velxd(i-2, j-1)-9.d0*velxd(i-1, j-1)-9.d0*velxd(i&
&       , j-1)+velxd(i+1, j-1)+7.d0*(9.d0*velxd(i-1, j)-velxd(i-2, j)+&
&       9.d0*velxd(i, j)-velxd(i+1, j))+7.d0*(9.d0*velxd(i-1, j+1)-velxd&
&       (i-2, j+1)+9.d0*velxd(i, j+1)-velxd(i+1, j+1))+velxd(i-2, j+2)-&
&       9.d0*velxd(i-1, j+2)+velxd(i+1, j+2)-9.d0*velxd(i, j+2))
      val_od0 = ccross*(velxd0(i-2, j-1)-9.d0*velxd0(i-1, j-1)-9.d0*&
&       velxd0(i, j-1)+velxd0(i+1, j-1)+7.d0*(9.d0*velxd0(i-1, j)-velxd0&
&       (i-2, j)+9.d0*velxd0(i, j)-velxd0(i+1, j))+7.d0*(9.d0*velxd0(i-1&
&       , j+1)-velxd0(i-2, j+1)+9.d0*velxd0(i, j+1)-velxd0(i+1, j+1))+&
&       velxd0(i-2, j+2)-9.d0*velxd0(i-1, j+2)+velxd0(i+1, j+2)-9.d0*&
&       velxd0(i, j+2))
      val_o = ccross*(-(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)+9.d0*velx(i&
&       , j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+&
&       9.d0*velx(i, j)-velx(i+1, j))+7.d0*(-velx(i-2, j+1)+9.d0*velx(i-&
&       1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1))-(-velx(i-2, j+2)+9.d0*&
&       velx(i-1, j+2)+9.d0*velx(i, j+2)-velx(i+1, j+2)))
      uxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      uxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      uxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      uyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      uyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = twentyfourth*(26.d0*velydd(i, j)-velydd(i+1, j)-velydd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*velyd(i, j)-velyd(i+1, j)-velyd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*velyd0(i, j)-velyd0(i+1, j)-velyd0(i&
&       -1, j))
      val_n = twentyfourth*(-vely(i+1, j)+26.d0*vely(i, j)-vely(i-1, j))
      val_sdd = twentyfourth*(26.d0*velydd(i-1, j)-velydd(i, j)-velydd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*velyd(i-1, j)-velyd(i, j)-velyd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*velyd0(i-1, j)-velyd0(i, j)-velyd0(i&
&       -2, j))
      val_s = twentyfourth*(-vely(i, j)+26.d0*vely(i-1, j)-vely(i-2, j))
      val_edd = ccross*(velydd(i-2, j-2)-9.d0*velydd(i-1, j-2)-9.d0*&
&       velydd(i, j-2)+velydd(i+1, j-2)+7.d0*(9.d0*velydd(i-1, j-1)-&
&       velydd(i-2, j-1)+9.d0*velydd(i, j-1)-velydd(i+1, j-1))+7.d0*(&
&       9.d0*velydd(i-1, j)-velydd(i-2, j)+9.d0*velydd(i, j)-velydd(i+1&
&       , j))+velydd(i-2, j+1)-9.d0*velydd(i-1, j+1)+velydd(i+1, j+1)-&
&       9.d0*velydd(i, j+1))
      val_ed = ccross*(velyd(i-2, j-2)-9.d0*velyd(i-1, j-2)-9.d0*velyd(i&
&       , j-2)+velyd(i+1, j-2)+7.d0*(9.d0*velyd(i-1, j-1)-velyd(i-2, j-1&
&       )+9.d0*velyd(i, j-1)-velyd(i+1, j-1))+7.d0*(9.d0*velyd(i-1, j)-&
&       velyd(i-2, j)+9.d0*velyd(i, j)-velyd(i+1, j))+velyd(i-2, j+1)-&
&       9.d0*velyd(i-1, j+1)+velyd(i+1, j+1)-9.d0*velyd(i, j+1))
      val_ed0 = ccross*(velyd0(i-2, j-2)-9.d0*velyd0(i-1, j-2)-9.d0*&
&       velyd0(i, j-2)+velyd0(i+1, j-2)+7.d0*(9.d0*velyd0(i-1, j-1)-&
&       velyd0(i-2, j-1)+9.d0*velyd0(i, j-1)-velyd0(i+1, j-1))+7.d0*(&
&       9.d0*velyd0(i-1, j)-velyd0(i-2, j)+9.d0*velyd0(i, j)-velyd0(i+1&
&       , j))+velyd0(i-2, j+1)-9.d0*velyd0(i-1, j+1)+velyd0(i+1, j+1)-&
&       9.d0*velyd0(i, j+1))
      val_e = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-1, j-2)+9.d0*vely(i&
&       , j-2)-vely(i+1, j-2))+7.d0*(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)&
&       +9.d0*vely(i, j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely&
&       (i-1, j)+9.d0*vely(i, j)-vely(i+1, j))-(-vely(i-2, j+1)+9.d0*&
&       vely(i-1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1)))
      val_odd = ccross*(velydd(i-2, j-1)-9.d0*velydd(i-1, j-1)-9.d0*&
&       velydd(i, j-1)+velydd(i+1, j-1)+7.d0*(9.d0*velydd(i-1, j)-velydd&
&       (i-2, j)+9.d0*velydd(i, j)-velydd(i+1, j))+7.d0*(9.d0*velydd(i-1&
&       , j+1)-velydd(i-2, j+1)+9.d0*velydd(i, j+1)-velydd(i+1, j+1))+&
&       velydd(i-2, j+2)-9.d0*velydd(i-1, j+2)+velydd(i+1, j+2)-9.d0*&
&       velydd(i, j+2))
      val_od = ccross*(velyd(i-2, j-1)-9.d0*velyd(i-1, j-1)-9.d0*velyd(i&
&       , j-1)+velyd(i+1, j-1)+7.d0*(9.d0*velyd(i-1, j)-velyd(i-2, j)+&
&       9.d0*velyd(i, j)-velyd(i+1, j))+7.d0*(9.d0*velyd(i-1, j+1)-velyd&
&       (i-2, j+1)+9.d0*velyd(i, j+1)-velyd(i+1, j+1))+velyd(i-2, j+2)-&
&       9.d0*velyd(i-1, j+2)+velyd(i+1, j+2)-9.d0*velyd(i, j+2))
      val_od0 = ccross*(velyd0(i-2, j-1)-9.d0*velyd0(i-1, j-1)-9.d0*&
&       velyd0(i, j-1)+velyd0(i+1, j-1)+7.d0*(9.d0*velyd0(i-1, j)-velyd0&
&       (i-2, j)+9.d0*velyd0(i, j)-velyd0(i+1, j))+7.d0*(9.d0*velyd0(i-1&
&       , j+1)-velyd0(i-2, j+1)+9.d0*velyd0(i, j+1)-velyd0(i+1, j+1))+&
&       velyd0(i-2, j+2)-9.d0*velyd0(i-1, j+2)+velyd0(i+1, j+2)-9.d0*&
&       velyd0(i, j+2))
      val_o = ccross*(-(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)+9.d0*vely(i&
&       , j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+&
&       9.d0*vely(i, j)-vely(i+1, j))+7.d0*(-vely(i-2, j+1)+9.d0*vely(i-&
&       1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1))-(-vely(i-2, j+2)+9.d0*&
&       vely(i-1, j+2)+9.d0*vely(i, j+2)-vely(i+1, j+2)))
      vxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      vxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      vxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      vyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      vyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = twentyfourth*(26.d0*velzdd(i, j)-velzdd(i+1, j)-velzdd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*velzd(i, j)-velzd(i+1, j)-velzd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*velzd0(i, j)-velzd0(i+1, j)-velzd0(i&
&       -1, j))
      val_n = twentyfourth*(-velz(i+1, j)+26.d0*velz(i, j)-velz(i-1, j))
      val_sdd = twentyfourth*(26.d0*velzdd(i-1, j)-velzdd(i, j)-velzdd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*velzd(i-1, j)-velzd(i, j)-velzd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*velzd0(i-1, j)-velzd0(i, j)-velzd0(i&
&       -2, j))
      val_s = twentyfourth*(-velz(i, j)+26.d0*velz(i-1, j)-velz(i-2, j))
      val_edd = ccross*(velzdd(i-2, j-2)-9.d0*velzdd(i-1, j-2)-9.d0*&
&       velzdd(i, j-2)+velzdd(i+1, j-2)+7.d0*(9.d0*velzdd(i-1, j-1)-&
&       velzdd(i-2, j-1)+9.d0*velzdd(i, j-1)-velzdd(i+1, j-1))+7.d0*(&
&       9.d0*velzdd(i-1, j)-velzdd(i-2, j)+9.d0*velzdd(i, j)-velzdd(i+1&
&       , j))+velzdd(i-2, j+1)-9.d0*velzdd(i-1, j+1)+velzdd(i+1, j+1)-&
&       9.d0*velzdd(i, j+1))
      val_ed = ccross*(velzd(i-2, j-2)-9.d0*velzd(i-1, j-2)-9.d0*velzd(i&
&       , j-2)+velzd(i+1, j-2)+7.d0*(9.d0*velzd(i-1, j-1)-velzd(i-2, j-1&
&       )+9.d0*velzd(i, j-1)-velzd(i+1, j-1))+7.d0*(9.d0*velzd(i-1, j)-&
&       velzd(i-2, j)+9.d0*velzd(i, j)-velzd(i+1, j))+velzd(i-2, j+1)-&
&       9.d0*velzd(i-1, j+1)+velzd(i+1, j+1)-9.d0*velzd(i, j+1))
      val_ed0 = ccross*(velzd0(i-2, j-2)-9.d0*velzd0(i-1, j-2)-9.d0*&
&       velzd0(i, j-2)+velzd0(i+1, j-2)+7.d0*(9.d0*velzd0(i-1, j-1)-&
&       velzd0(i-2, j-1)+9.d0*velzd0(i, j-1)-velzd0(i+1, j-1))+7.d0*(&
&       9.d0*velzd0(i-1, j)-velzd0(i-2, j)+9.d0*velzd0(i, j)-velzd0(i+1&
&       , j))+velzd0(i-2, j+1)-9.d0*velzd0(i-1, j+1)+velzd0(i+1, j+1)-&
&       9.d0*velzd0(i, j+1))
      val_e = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-1, j-2)+9.d0*velz(i&
&       , j-2)-velz(i+1, j-2))+7.d0*(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)&
&       +9.d0*velz(i, j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz&
&       (i-1, j)+9.d0*velz(i, j)-velz(i+1, j))-(-velz(i-2, j+1)+9.d0*&
&       velz(i-1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1)))
      val_odd = ccross*(velzdd(i-2, j-1)-9.d0*velzdd(i-1, j-1)-9.d0*&
&       velzdd(i, j-1)+velzdd(i+1, j-1)+7.d0*(9.d0*velzdd(i-1, j)-velzdd&
&       (i-2, j)+9.d0*velzdd(i, j)-velzdd(i+1, j))+7.d0*(9.d0*velzdd(i-1&
&       , j+1)-velzdd(i-2, j+1)+9.d0*velzdd(i, j+1)-velzdd(i+1, j+1))+&
&       velzdd(i-2, j+2)-9.d0*velzdd(i-1, j+2)+velzdd(i+1, j+2)-9.d0*&
&       velzdd(i, j+2))
      val_od = ccross*(velzd(i-2, j-1)-9.d0*velzd(i-1, j-1)-9.d0*velzd(i&
&       , j-1)+velzd(i+1, j-1)+7.d0*(9.d0*velzd(i-1, j)-velzd(i-2, j)+&
&       9.d0*velzd(i, j)-velzd(i+1, j))+7.d0*(9.d0*velzd(i-1, j+1)-velzd&
&       (i-2, j+1)+9.d0*velzd(i, j+1)-velzd(i+1, j+1))+velzd(i-2, j+2)-&
&       9.d0*velzd(i-1, j+2)+velzd(i+1, j+2)-9.d0*velzd(i, j+2))
      val_od0 = ccross*(velzd0(i-2, j-1)-9.d0*velzd0(i-1, j-1)-9.d0*&
&       velzd0(i, j-1)+velzd0(i+1, j-1)+7.d0*(9.d0*velzd0(i-1, j)-velzd0&
&       (i-2, j)+9.d0*velzd0(i, j)-velzd0(i+1, j))+7.d0*(9.d0*velzd0(i-1&
&       , j+1)-velzd0(i-2, j+1)+9.d0*velzd0(i, j+1)-velzd0(i+1, j+1))+&
&       velzd0(i-2, j+2)-9.d0*velzd0(i-1, j+2)+velzd0(i+1, j+2)-9.d0*&
&       velzd0(i, j+2))
      val_o = ccross*(-(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)+9.d0*velz(i&
&       , j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+&
&       9.d0*velz(i, j)-velz(i+1, j))+7.d0*(-velz(i-2, j+1)+9.d0*velz(i-&
&       1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1))-(-velz(i-2, j+2)+9.d0*&
&       velz(i-1, j+2)+9.d0*velz(i, j+2)-velz(i+1, j+2)))
      wxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      wxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      wxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      wyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      wyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = twentyfourth*(26.d0*tlocdd(i, j)-tlocdd(i+1, j)-tlocdd(i&
&       -1, j))
      val_nd = twentyfourth*(26.d0*tlocd(i, j)-tlocd(i+1, j)-tlocd(i-1, &
&       j))
      val_nd0 = twentyfourth*(26.d0*tlocd0(i, j)-tlocd0(i+1, j)-tlocd0(i&
&       -1, j))
      val_n = twentyfourth*(-tloc(i+1, j)+26.d0*tloc(i, j)-tloc(i-1, j))
      val_sdd = twentyfourth*(26.d0*tlocdd(i-1, j)-tlocdd(i, j)-tlocdd(i&
&       -2, j))
      val_sd = twentyfourth*(26.d0*tlocd(i-1, j)-tlocd(i, j)-tlocd(i-2, &
&       j))
      val_sd0 = twentyfourth*(26.d0*tlocd0(i-1, j)-tlocd0(i, j)-tlocd0(i&
&       -2, j))
      val_s = twentyfourth*(-tloc(i, j)+26.d0*tloc(i-1, j)-tloc(i-2, j))
      val_edd = ccross*(tlocdd(i-2, j-2)-9.d0*tlocdd(i-1, j-2)-9.d0*&
&       tlocdd(i, j-2)+tlocdd(i+1, j-2)+7.d0*(9.d0*tlocdd(i-1, j-1)-&
&       tlocdd(i-2, j-1)+9.d0*tlocdd(i, j-1)-tlocdd(i+1, j-1))+7.d0*(&
&       9.d0*tlocdd(i-1, j)-tlocdd(i-2, j)+9.d0*tlocdd(i, j)-tlocdd(i+1&
&       , j))+tlocdd(i-2, j+1)-9.d0*tlocdd(i-1, j+1)+tlocdd(i+1, j+1)-&
&       9.d0*tlocdd(i, j+1))
      val_ed = ccross*(tlocd(i-2, j-2)-9.d0*tlocd(i-1, j-2)-9.d0*tlocd(i&
&       , j-2)+tlocd(i+1, j-2)+7.d0*(9.d0*tlocd(i-1, j-1)-tlocd(i-2, j-1&
&       )+9.d0*tlocd(i, j-1)-tlocd(i+1, j-1))+7.d0*(9.d0*tlocd(i-1, j)-&
&       tlocd(i-2, j)+9.d0*tlocd(i, j)-tlocd(i+1, j))+tlocd(i-2, j+1)-&
&       9.d0*tlocd(i-1, j+1)+tlocd(i+1, j+1)-9.d0*tlocd(i, j+1))
      val_ed0 = ccross*(tlocd0(i-2, j-2)-9.d0*tlocd0(i-1, j-2)-9.d0*&
&       tlocd0(i, j-2)+tlocd0(i+1, j-2)+7.d0*(9.d0*tlocd0(i-1, j-1)-&
&       tlocd0(i-2, j-1)+9.d0*tlocd0(i, j-1)-tlocd0(i+1, j-1))+7.d0*(&
&       9.d0*tlocd0(i-1, j)-tlocd0(i-2, j)+9.d0*tlocd0(i, j)-tlocd0(i+1&
&       , j))+tlocd0(i-2, j+1)-9.d0*tlocd0(i-1, j+1)+tlocd0(i+1, j+1)-&
&       9.d0*tlocd0(i, j+1))
      val_e = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-1, j-2)+9.d0*tloc(i&
&       , j-2)-tloc(i+1, j-2))+7.d0*(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)&
&       +9.d0*tloc(i, j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc&
&       (i-1, j)+9.d0*tloc(i, j)-tloc(i+1, j))-(-tloc(i-2, j+1)+9.d0*&
&       tloc(i-1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1)))
      val_odd = ccross*(tlocdd(i-2, j-1)-9.d0*tlocdd(i-1, j-1)-9.d0*&
&       tlocdd(i, j-1)+tlocdd(i+1, j-1)+7.d0*(9.d0*tlocdd(i-1, j)-tlocdd&
&       (i-2, j)+9.d0*tlocdd(i, j)-tlocdd(i+1, j))+7.d0*(9.d0*tlocdd(i-1&
&       , j+1)-tlocdd(i-2, j+1)+9.d0*tlocdd(i, j+1)-tlocdd(i+1, j+1))+&
&       tlocdd(i-2, j+2)-9.d0*tlocdd(i-1, j+2)+tlocdd(i+1, j+2)-9.d0*&
&       tlocdd(i, j+2))
      val_od = ccross*(tlocd(i-2, j-1)-9.d0*tlocd(i-1, j-1)-9.d0*tlocd(i&
&       , j-1)+tlocd(i+1, j-1)+7.d0*(9.d0*tlocd(i-1, j)-tlocd(i-2, j)+&
&       9.d0*tlocd(i, j)-tlocd(i+1, j))+7.d0*(9.d0*tlocd(i-1, j+1)-tlocd&
&       (i-2, j+1)+9.d0*tlocd(i, j+1)-tlocd(i+1, j+1))+tlocd(i-2, j+2)-&
&       9.d0*tlocd(i-1, j+2)+tlocd(i+1, j+2)-9.d0*tlocd(i, j+2))
      val_od0 = ccross*(tlocd0(i-2, j-1)-9.d0*tlocd0(i-1, j-1)-9.d0*&
&       tlocd0(i, j-1)+tlocd0(i+1, j-1)+7.d0*(9.d0*tlocd0(i-1, j)-tlocd0&
&       (i-2, j)+9.d0*tlocd0(i, j)-tlocd0(i+1, j))+7.d0*(9.d0*tlocd0(i-1&
&       , j+1)-tlocd0(i-2, j+1)+9.d0*tlocd0(i, j+1)-tlocd0(i+1, j+1))+&
&       tlocd0(i-2, j+2)-9.d0*tlocd0(i-1, j+2)+tlocd0(i+1, j+2)-9.d0*&
&       tlocd0(i, j+2))
      val_o = ccross*(-(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i&
&       , j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc(i-1, j)+&
&       9.d0*tloc(i, j)-tloc(i+1, j))+7.d0*(-tloc(i-2, j+1)+9.d0*tloc(i-&
&       1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1))-(-tloc(i-2, j+2)+9.d0*&
&       tloc(i-1, j+2)+9.d0*tloc(i, j+2)-tloc(i+1, j+2)))
      txdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      txd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      txd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      tydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      tyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      tyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
!
! Computation of viscous fluxes
!
      uudd = 0.0625d0*(9.d0*velxdd(i-1, j)-velxdd(i-2, j)+9.d0*velxdd(i&
&       , j)-velxdd(i+1, j))
      uud = 0.0625d0*(9.d0*velxd(i-1, j)-velxd(i-2, j)+9.d0*velxd(i, j)-&
&       velxd(i+1, j))
      uud0 = 0.0625d0*(9.d0*velxd0(i-1, j)-velxd0(i-2, j)+9.d0*velxd0(i&
&       , j)-velxd0(i+1, j))
      uu = 0.0625d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+9.d0*velx(i, j)-&
&       velx(i+1, j))
      vvdd = 0.0625d0*(9.d0*velydd(i-1, j)-velydd(i-2, j)+9.d0*velydd(i&
&       , j)-velydd(i+1, j))
      vvd = 0.0625d0*(9.d0*velyd(i-1, j)-velyd(i-2, j)+9.d0*velyd(i, j)-&
&       velyd(i+1, j))
      vvd0 = 0.0625d0*(9.d0*velyd0(i-1, j)-velyd0(i-2, j)+9.d0*velyd0(i&
&       , j)-velyd0(i+1, j))
      vv = 0.0625d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+9.d0*vely(i, j)-&
&       vely(i+1, j))
      wwdd = 0.0625d0*(9.d0*velzdd(i-1, j)-velzdd(i-2, j)+9.d0*velzdd(i&
&       , j)-velzdd(i+1, j))
      wwd = 0.0625d0*(9.d0*velzd(i-1, j)-velzd(i-2, j)+9.d0*velzd(i, j)-&
&       velzd(i+1, j))
      wwd0 = 0.0625d0*(9.d0*velzd0(i-1, j)-velzd0(i-2, j)+9.d0*velzd0(i&
&       , j)-velzd0(i+1, j))
      ww = 0.0625d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+9.d0*velz(i, j)-&
&       velz(i+1, j))
!
      mmudd = 0.0625d0*(9.d0*mudd(i-1, j)-mudd(i-2, j)+9.d0*mudd(i, j)-&
&       mudd(i+1, j))
      mmud = 0.0625d0*(9.d0*mud(i-1, j)-mud(i-2, j)+9.d0*mud(i, j)-mud(i&
&       +1, j))
      mmud0 = 0.0625d0*(9.d0*mud0(i-1, j)-mud0(i-2, j)+9.d0*mud0(i, j)-&
&       mud0(i+1, j))
      mmu = 0.0625d0*(-mu(i-2, j)+9.d0*mu(i-1, j)+9.d0*mu(i, j)-mu(i+1, &
&       j))
      lambdadd = cpprandtl*mmudd
      lambdad = cpprandtl*mmud
      lambdad0 = cpprandtl*mmud0
      lambda = mmu*cpprandtl
!
      fvrou1dd = twothird*(mmud*(two*uxd0-vyd0)+(two*ux-vy)*mmudd+(two*&
&       uxd-vyd)*mmud0+mmu*(two*uxdd-vydd))
      fvrou1d = twothird*((two*ux-vy)*mmud+mmu*(two*uxd-vyd))
      fvrou1d0 = twothird*((two*ux-vy)*mmud0+mmu*(two*uxd0-vyd0))
      fvrou1 = twothird*mmu*(two*ux-vy)
      fvrov1dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      fvrov1d = (uy+vx)*mmud + mmu*(uyd+vxd)
      fvrov1d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      fvrov1 = mmu*(uy+vx)
      fvrow1dd = mmud*wxd0 + wx*mmudd + wxd*mmud0 + mmu*wxdd
      fvrow1d = wx*mmud + mmu*wxd
      fvrow1d0 = wx*mmud0 + mmu*wxd0
      fvrow1 = mmu*wx
      fvroe1dd = lambdad*txd0 + tx*lambdadd + txd*lambdad0 + lambda*txdd&
&       + uud*fvrou1d0 + fvrou1*uudd + fvrou1d*uud0 + uu*fvrou1dd + vvd*&
&       fvrov1d0 + fvrov1*vvdd + fvrov1d*vvd0 + vv*fvrov1dd + wwd*&
&       fvrow1d0 + fvrow1*wwdd + fvrow1d*wwd0 + ww*fvrow1dd
! fvroe1 = (lambda*tx + uu*fvrou1 + vv*fvrov1)
!
      gvrou1dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      gvrou1d = (uy+vx)*mmud + mmu*(uyd+vxd)
      gvrou1d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      gvrou1 = mmu*(uy+vx)
      gvrov1dd = twothird*(mmud*(two*vyd0-uxd0)+(two*vy-ux)*mmudd+(two*&
&       vyd-uxd)*mmud0+mmu*(two*vydd-uxdd))
      gvrov1d = twothird*((two*vy-ux)*mmud+mmu*(two*vyd-uxd))
      gvrov1d0 = twothird*((two*vy-ux)*mmud0+mmu*(two*vyd0-uxd0))
      gvrov1 = twothird*mmu*(-ux+two*vy)
      gvrow1dd = mmud*wyd0 + wy*mmudd + wyd*mmud0 + mmu*wydd
      gvrow1d = wy*mmud + mmu*wyd
      gvrow1d0 = wy*mmud0 + mmu*wyd0
      gvrow1 = mmu*wy
      gvroe1dd = lambdad*tyd0 + ty*lambdadd + tyd*lambdad0 + lambda*tydd&
&       + uud*gvrou1d0 + gvrou1*uudd + gvrou1d*uud0 + uu*gvrou1dd + vvd*&
&       gvrov1d0 + gvrov1*vvdd + gvrov1d*vvd0 + vv*gvrov1dd + wwd*&
&       gvrow1d0 + gvrow1*wwdd + gvrow1d*wwd0 + ww*gvrow1dd
! gvroe1 = (lambda*ty + uu*gvrou1 + vv*gvrov1)
!!  fvrou1 = TWOTHIRD*mmu*( TWO*ux -     vy  -   wz  )
!!  fvrov1 =          mmu*(     uy +     vx          )
!!  fvrow1 =          mmu*(     uz           +   wx  )
!!  fvroe1 = lambda*tx + uu*fvrou1 + vv*fvrov1 + ww * fvrow1
!!  !
!!  gvrou1 =          mmu*(     uy +     vx          )
!!  gvrov1 = TWOTHIRD*mmu*(    -ux + TWO*vy   -  wz  )
!!  gvrow1 =          mmu*(              vz   +  wy  )
!!  gvroe1 = lambda*ty + uu*gvrou1 + vv*gvrov1 + ww * gvrow1
! grad for viscous fluxes o4 - 5p
!
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccross = TWELFTH*0.0625d0
      volm1 = volf(i, j, 2)
      nx_n = half*(nx(i+1, j-1, 1)+nx(i+1, j, 1))
      nx_s = -(half*(nx(i, j-1, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i, j+1, 2)+nx(i, j, 2))
      nx_e = -(half*(nx(i, j-1, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j-1, 1)+ny(i+1, j, 1))
      ny_s = -(half*(ny(i, j-1, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i, j+1, 2)+ny(i, j, 2))
      ny_e = -(half*(ny(i, j-1, 2)+ny(i, j, 2)))
      val_ndd = ccross*(velxdd(i-1, j-2)-9.d0*velxdd(i-1, j-1)-9.d0*&
&       velxdd(i-1, j)+velxdd(i-1, j+1)+7.d0*(9.d0*velxdd(i, j-1)-velxdd&
&       (i, j-2)+9.d0*velxdd(i, j)-velxdd(i, j+1))+7.d0*(9.d0*velxdd(i+1&
&       , j-1)-velxdd(i+1, j-2)+9.d0*velxdd(i+1, j)-velxdd(i+1, j+1))+&
&       velxdd(i+2, j-2)-9.d0*velxdd(i+2, j-1)+velxdd(i+2, j+1)-9.d0*&
&       velxdd(i+2, j))
      val_nd = ccross*(velxd(i-1, j-2)-9.d0*velxd(i-1, j-1)-9.d0*velxd(i&
&       -1, j)+velxd(i-1, j+1)+7.d0*(9.d0*velxd(i, j-1)-velxd(i, j-2)+&
&       9.d0*velxd(i, j)-velxd(i, j+1))+7.d0*(9.d0*velxd(i+1, j-1)-velxd&
&       (i+1, j-2)+9.d0*velxd(i+1, j)-velxd(i+1, j+1))+velxd(i+2, j-2)-&
&       9.d0*velxd(i+2, j-1)+velxd(i+2, j+1)-9.d0*velxd(i+2, j))
      val_nd0 = ccross*(velxd0(i-1, j-2)-9.d0*velxd0(i-1, j-1)-9.d0*&
&       velxd0(i-1, j)+velxd0(i-1, j+1)+7.d0*(9.d0*velxd0(i, j-1)-velxd0&
&       (i, j-2)+9.d0*velxd0(i, j)-velxd0(i, j+1))+7.d0*(9.d0*velxd0(i+1&
&       , j-1)-velxd0(i+1, j-2)+9.d0*velxd0(i+1, j)-velxd0(i+1, j+1))+&
&       velxd0(i+2, j-2)-9.d0*velxd0(i+2, j-1)+velxd0(i+2, j+1)-9.d0*&
&       velxd0(i+2, j))
      val_n = ccross*(-(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+9.d0*velx(i-&
&       1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0&
&       *velx(i, j)-velx(i, j+1))+7.d0*(-velx(i+1, j-2)+9.d0*velx(i+1, j&
&       -1)+9.d0*velx(i+1, j)-velx(i+1, j+1))-(-velx(i+2, j-2)+9.d0*velx&
&       (i+2, j-1)+9.d0*velx(i+2, j)-velx(i+2, j+1)))
      val_sdd = ccross*(velxdd(i-2, j-2)-9.d0*velxdd(i-2, j-1)-9.d0*&
&       velxdd(i-2, j)+velxdd(i-2, j+1)+7.d0*(9.d0*velxdd(i-1, j-1)-&
&       velxdd(i-1, j-2)+9.d0*velxdd(i-1, j)-velxdd(i-1, j+1))+7.d0*(&
&       9.d0*velxdd(i, j-1)-velxdd(i, j-2)+9.d0*velxdd(i, j)-velxdd(i, j&
&       +1))+velxdd(i+1, j-2)-9.d0*velxdd(i+1, j-1)+velxdd(i+1, j+1)-&
&       9.d0*velxdd(i+1, j))
      val_sd = ccross*(velxd(i-2, j-2)-9.d0*velxd(i-2, j-1)-9.d0*velxd(i&
&       -2, j)+velxd(i-2, j+1)+7.d0*(9.d0*velxd(i-1, j-1)-velxd(i-1, j-2&
&       )+9.d0*velxd(i-1, j)-velxd(i-1, j+1))+7.d0*(9.d0*velxd(i, j-1)-&
&       velxd(i, j-2)+9.d0*velxd(i, j)-velxd(i, j+1))+velxd(i+1, j-2)-&
&       9.d0*velxd(i+1, j-1)+velxd(i+1, j+1)-9.d0*velxd(i+1, j))
      val_sd0 = ccross*(velxd0(i-2, j-2)-9.d0*velxd0(i-2, j-1)-9.d0*&
&       velxd0(i-2, j)+velxd0(i-2, j+1)+7.d0*(9.d0*velxd0(i-1, j-1)-&
&       velxd0(i-1, j-2)+9.d0*velxd0(i-1, j)-velxd0(i-1, j+1))+7.d0*(&
&       9.d0*velxd0(i, j-1)-velxd0(i, j-2)+9.d0*velxd0(i, j)-velxd0(i, j&
&       +1))+velxd0(i+1, j-2)-9.d0*velxd0(i+1, j-1)+velxd0(i+1, j+1)-&
&       9.d0*velxd0(i+1, j))
      val_s = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-2, j-1)+9.d0*velx(i-&
&       2, j)-velx(i-2, j+1))+7.d0*(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+&
&       9.d0*velx(i-1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(&
&       i, j-1)+9.d0*velx(i, j)-velx(i, j+1))-(-velx(i+1, j-2)+9.d0*velx&
&       (i+1, j-1)+9.d0*velx(i+1, j)-velx(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*velxdd(i, j-1)-velxdd(i, j)-velxdd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*velxd(i, j-1)-velxd(i, j)-velxd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*velxd0(i, j-1)-velxd0(i, j)-velxd0(i&
&       , j-2))
      val_e = twentyfourth*(-velx(i, j)+26.d0*velx(i, j-1)-velx(i, j-2))
      val_odd = twentyfourth*(26.d0*velxdd(i, j)-velxdd(i, j+1)-velxdd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*velxd(i, j)-velxd(i, j+1)-velxd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*velxd0(i, j)-velxd0(i, j+1)-velxd0(i&
&       , j-1))
      val_o = twentyfourth*(-velx(i, j+1)+26.d0*velx(i, j)-velx(i, j-1))
      uxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      uxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      uxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      uyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      uyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = ccross*(velydd(i-1, j-2)-9.d0*velydd(i-1, j-1)-9.d0*&
&       velydd(i-1, j)+velydd(i-1, j+1)+7.d0*(9.d0*velydd(i, j-1)-velydd&
&       (i, j-2)+9.d0*velydd(i, j)-velydd(i, j+1))+7.d0*(9.d0*velydd(i+1&
&       , j-1)-velydd(i+1, j-2)+9.d0*velydd(i+1, j)-velydd(i+1, j+1))+&
&       velydd(i+2, j-2)-9.d0*velydd(i+2, j-1)+velydd(i+2, j+1)-9.d0*&
&       velydd(i+2, j))
      val_nd = ccross*(velyd(i-1, j-2)-9.d0*velyd(i-1, j-1)-9.d0*velyd(i&
&       -1, j)+velyd(i-1, j+1)+7.d0*(9.d0*velyd(i, j-1)-velyd(i, j-2)+&
&       9.d0*velyd(i, j)-velyd(i, j+1))+7.d0*(9.d0*velyd(i+1, j-1)-velyd&
&       (i+1, j-2)+9.d0*velyd(i+1, j)-velyd(i+1, j+1))+velyd(i+2, j-2)-&
&       9.d0*velyd(i+2, j-1)+velyd(i+2, j+1)-9.d0*velyd(i+2, j))
      val_nd0 = ccross*(velyd0(i-1, j-2)-9.d0*velyd0(i-1, j-1)-9.d0*&
&       velyd0(i-1, j)+velyd0(i-1, j+1)+7.d0*(9.d0*velyd0(i, j-1)-velyd0&
&       (i, j-2)+9.d0*velyd0(i, j)-velyd0(i, j+1))+7.d0*(9.d0*velyd0(i+1&
&       , j-1)-velyd0(i+1, j-2)+9.d0*velyd0(i+1, j)-velyd0(i+1, j+1))+&
&       velyd0(i+2, j-2)-9.d0*velyd0(i+2, j-1)+velyd0(i+2, j+1)-9.d0*&
&       velyd0(i+2, j))
      val_n = ccross*(-(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+9.d0*vely(i-&
&       1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0&
&       *vely(i, j)-vely(i, j+1))+7.d0*(-vely(i+1, j-2)+9.d0*vely(i+1, j&
&       -1)+9.d0*vely(i+1, j)-vely(i+1, j+1))-(-vely(i+2, j-2)+9.d0*vely&
&       (i+2, j-1)+9.d0*vely(i+2, j)-vely(i+2, j+1)))
      val_sdd = ccross*(velydd(i-2, j-2)-9.d0*velydd(i-2, j-1)-9.d0*&
&       velydd(i-2, j)+velydd(i-2, j+1)+7.d0*(9.d0*velydd(i-1, j-1)-&
&       velydd(i-1, j-2)+9.d0*velydd(i-1, j)-velydd(i-1, j+1))+7.d0*(&
&       9.d0*velydd(i, j-1)-velydd(i, j-2)+9.d0*velydd(i, j)-velydd(i, j&
&       +1))+velydd(i+1, j-2)-9.d0*velydd(i+1, j-1)+velydd(i+1, j+1)-&
&       9.d0*velydd(i+1, j))
      val_sd = ccross*(velyd(i-2, j-2)-9.d0*velyd(i-2, j-1)-9.d0*velyd(i&
&       -2, j)+velyd(i-2, j+1)+7.d0*(9.d0*velyd(i-1, j-1)-velyd(i-1, j-2&
&       )+9.d0*velyd(i-1, j)-velyd(i-1, j+1))+7.d0*(9.d0*velyd(i, j-1)-&
&       velyd(i, j-2)+9.d0*velyd(i, j)-velyd(i, j+1))+velyd(i+1, j-2)-&
&       9.d0*velyd(i+1, j-1)+velyd(i+1, j+1)-9.d0*velyd(i+1, j))
      val_sd0 = ccross*(velyd0(i-2, j-2)-9.d0*velyd0(i-2, j-1)-9.d0*&
&       velyd0(i-2, j)+velyd0(i-2, j+1)+7.d0*(9.d0*velyd0(i-1, j-1)-&
&       velyd0(i-1, j-2)+9.d0*velyd0(i-1, j)-velyd0(i-1, j+1))+7.d0*(&
&       9.d0*velyd0(i, j-1)-velyd0(i, j-2)+9.d0*velyd0(i, j)-velyd0(i, j&
&       +1))+velyd0(i+1, j-2)-9.d0*velyd0(i+1, j-1)+velyd0(i+1, j+1)-&
&       9.d0*velyd0(i+1, j))
      val_s = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-2, j-1)+9.d0*vely(i-&
&       2, j)-vely(i-2, j+1))+7.d0*(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+&
&       9.d0*vely(i-1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(&
&       i, j-1)+9.d0*vely(i, j)-vely(i, j+1))-(-vely(i+1, j-2)+9.d0*vely&
&       (i+1, j-1)+9.d0*vely(i+1, j)-vely(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*velydd(i, j-1)-velydd(i, j)-velydd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*velyd(i, j-1)-velyd(i, j)-velyd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*velyd0(i, j-1)-velyd0(i, j)-velyd0(i&
&       , j-2))
      val_e = twentyfourth*(-vely(i, j)+26.d0*vely(i, j-1)-vely(i, j-2))
      val_odd = twentyfourth*(26.d0*velydd(i, j)-velydd(i, j+1)-velydd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*velyd(i, j)-velyd(i, j+1)-velyd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*velyd0(i, j)-velyd0(i, j+1)-velyd0(i&
&       , j-1))
      val_o = twentyfourth*(-vely(i, j+1)+26.d0*vely(i, j)-vely(i, j-1))
      vxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      vxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      vxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      vyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      vyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = ccross*(velzdd(i-1, j-2)-9.d0*velzdd(i-1, j-1)-9.d0*&
&       velzdd(i-1, j)+velzdd(i-1, j+1)+7.d0*(9.d0*velzdd(i, j-1)-velzdd&
&       (i, j-2)+9.d0*velzdd(i, j)-velzdd(i, j+1))+7.d0*(9.d0*velzdd(i+1&
&       , j-1)-velzdd(i+1, j-2)+9.d0*velzdd(i+1, j)-velzdd(i+1, j+1))+&
&       velzdd(i+2, j-2)-9.d0*velzdd(i+2, j-1)+velzdd(i+2, j+1)-9.d0*&
&       velzdd(i+2, j))
      val_nd = ccross*(velzd(i-1, j-2)-9.d0*velzd(i-1, j-1)-9.d0*velzd(i&
&       -1, j)+velzd(i-1, j+1)+7.d0*(9.d0*velzd(i, j-1)-velzd(i, j-2)+&
&       9.d0*velzd(i, j)-velzd(i, j+1))+7.d0*(9.d0*velzd(i+1, j-1)-velzd&
&       (i+1, j-2)+9.d0*velzd(i+1, j)-velzd(i+1, j+1))+velzd(i+2, j-2)-&
&       9.d0*velzd(i+2, j-1)+velzd(i+2, j+1)-9.d0*velzd(i+2, j))
      val_nd0 = ccross*(velzd0(i-1, j-2)-9.d0*velzd0(i-1, j-1)-9.d0*&
&       velzd0(i-1, j)+velzd0(i-1, j+1)+7.d0*(9.d0*velzd0(i, j-1)-velzd0&
&       (i, j-2)+9.d0*velzd0(i, j)-velzd0(i, j+1))+7.d0*(9.d0*velzd0(i+1&
&       , j-1)-velzd0(i+1, j-2)+9.d0*velzd0(i+1, j)-velzd0(i+1, j+1))+&
&       velzd0(i+2, j-2)-9.d0*velzd0(i+2, j-1)+velzd0(i+2, j+1)-9.d0*&
&       velzd0(i+2, j))
      val_n = ccross*(-(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+9.d0*velz(i-&
&       1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0&
&       *velz(i, j)-velz(i, j+1))+7.d0*(-velz(i+1, j-2)+9.d0*velz(i+1, j&
&       -1)+9.d0*velz(i+1, j)-velz(i+1, j+1))-(-velz(i+2, j-2)+9.d0*velz&
&       (i+2, j-1)+9.d0*velz(i+2, j)-velz(i+2, j+1)))
      val_sdd = ccross*(velzdd(i-2, j-2)-9.d0*velzdd(i-2, j-1)-9.d0*&
&       velzdd(i-2, j)+velzdd(i-2, j+1)+7.d0*(9.d0*velzdd(i-1, j-1)-&
&       velzdd(i-1, j-2)+9.d0*velzdd(i-1, j)-velzdd(i-1, j+1))+7.d0*(&
&       9.d0*velzdd(i, j-1)-velzdd(i, j-2)+9.d0*velzdd(i, j)-velzdd(i, j&
&       +1))+velzdd(i+1, j-2)-9.d0*velzdd(i+1, j-1)+velzdd(i+1, j+1)-&
&       9.d0*velzdd(i+1, j))
      val_sd = ccross*(velzd(i-2, j-2)-9.d0*velzd(i-2, j-1)-9.d0*velzd(i&
&       -2, j)+velzd(i-2, j+1)+7.d0*(9.d0*velzd(i-1, j-1)-velzd(i-1, j-2&
&       )+9.d0*velzd(i-1, j)-velzd(i-1, j+1))+7.d0*(9.d0*velzd(i, j-1)-&
&       velzd(i, j-2)+9.d0*velzd(i, j)-velzd(i, j+1))+velzd(i+1, j-2)-&
&       9.d0*velzd(i+1, j-1)+velzd(i+1, j+1)-9.d0*velzd(i+1, j))
      val_sd0 = ccross*(velzd0(i-2, j-2)-9.d0*velzd0(i-2, j-1)-9.d0*&
&       velzd0(i-2, j)+velzd0(i-2, j+1)+7.d0*(9.d0*velzd0(i-1, j-1)-&
&       velzd0(i-1, j-2)+9.d0*velzd0(i-1, j)-velzd0(i-1, j+1))+7.d0*(&
&       9.d0*velzd0(i, j-1)-velzd0(i, j-2)+9.d0*velzd0(i, j)-velzd0(i, j&
&       +1))+velzd0(i+1, j-2)-9.d0*velzd0(i+1, j-1)+velzd0(i+1, j+1)-&
&       9.d0*velzd0(i+1, j))
      val_s = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-2, j-1)+9.d0*velz(i-&
&       2, j)-velz(i-2, j+1))+7.d0*(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+&
&       9.d0*velz(i-1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(&
&       i, j-1)+9.d0*velz(i, j)-velz(i, j+1))-(-velz(i+1, j-2)+9.d0*velz&
&       (i+1, j-1)+9.d0*velz(i+1, j)-velz(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*velzdd(i, j-1)-velzdd(i, j)-velzdd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*velzd(i, j-1)-velzd(i, j)-velzd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*velzd0(i, j-1)-velzd0(i, j)-velzd0(i&
&       , j-2))
      val_e = twentyfourth*(-velz(i, j)+26.d0*velz(i, j-1)-velz(i, j-2))
      val_odd = twentyfourth*(26.d0*velzdd(i, j)-velzdd(i, j+1)-velzdd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*velzd(i, j)-velzd(i, j+1)-velzd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*velzd0(i, j)-velzd0(i, j+1)-velzd0(i&
&       , j-1))
      val_o = twentyfourth*(-velz(i, j+1)+26.d0*velz(i, j)-velz(i, j-1))
      wxdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      wxd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      wxd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      wyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      wyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_ndd = ccross*(tlocdd(i-1, j-2)-9.d0*tlocdd(i-1, j-1)-9.d0*&
&       tlocdd(i-1, j)+tlocdd(i-1, j+1)+7.d0*(9.d0*tlocdd(i, j-1)-tlocdd&
&       (i, j-2)+9.d0*tlocdd(i, j)-tlocdd(i, j+1))+7.d0*(9.d0*tlocdd(i+1&
&       , j-1)-tlocdd(i+1, j-2)+9.d0*tlocdd(i+1, j)-tlocdd(i+1, j+1))+&
&       tlocdd(i+2, j-2)-9.d0*tlocdd(i+2, j-1)+tlocdd(i+2, j+1)-9.d0*&
&       tlocdd(i+2, j))
      val_nd = ccross*(tlocd(i-1, j-2)-9.d0*tlocd(i-1, j-1)-9.d0*tlocd(i&
&       -1, j)+tlocd(i-1, j+1)+7.d0*(9.d0*tlocd(i, j-1)-tlocd(i, j-2)+&
&       9.d0*tlocd(i, j)-tlocd(i, j+1))+7.d0*(9.d0*tlocd(i+1, j-1)-tlocd&
&       (i+1, j-2)+9.d0*tlocd(i+1, j)-tlocd(i+1, j+1))+tlocd(i+2, j-2)-&
&       9.d0*tlocd(i+2, j-1)+tlocd(i+2, j+1)-9.d0*tlocd(i+2, j))
      val_nd0 = ccross*(tlocd0(i-1, j-2)-9.d0*tlocd0(i-1, j-1)-9.d0*&
&       tlocd0(i-1, j)+tlocd0(i-1, j+1)+7.d0*(9.d0*tlocd0(i, j-1)-tlocd0&
&       (i, j-2)+9.d0*tlocd0(i, j)-tlocd0(i, j+1))+7.d0*(9.d0*tlocd0(i+1&
&       , j-1)-tlocd0(i+1, j-2)+9.d0*tlocd0(i+1, j)-tlocd0(i+1, j+1))+&
&       tlocd0(i+2, j-2)-9.d0*tlocd0(i+2, j-1)+tlocd0(i+2, j+1)-9.d0*&
&       tlocd0(i+2, j))
      val_n = ccross*(-(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i-&
&       1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(i, j-1)+9.d0&
&       *tloc(i, j)-tloc(i, j+1))+7.d0*(-tloc(i+1, j-2)+9.d0*tloc(i+1, j&
&       -1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1))-(-tloc(i+2, j-2)+9.d0*tloc&
&       (i+2, j-1)+9.d0*tloc(i+2, j)-tloc(i+2, j+1)))
      val_sdd = ccross*(tlocdd(i-2, j-2)-9.d0*tlocdd(i-2, j-1)-9.d0*&
&       tlocdd(i-2, j)+tlocdd(i-2, j+1)+7.d0*(9.d0*tlocdd(i-1, j-1)-&
&       tlocdd(i-1, j-2)+9.d0*tlocdd(i-1, j)-tlocdd(i-1, j+1))+7.d0*(&
&       9.d0*tlocdd(i, j-1)-tlocdd(i, j-2)+9.d0*tlocdd(i, j)-tlocdd(i, j&
&       +1))+tlocdd(i+1, j-2)-9.d0*tlocdd(i+1, j-1)+tlocdd(i+1, j+1)-&
&       9.d0*tlocdd(i+1, j))
      val_sd = ccross*(tlocd(i-2, j-2)-9.d0*tlocd(i-2, j-1)-9.d0*tlocd(i&
&       -2, j)+tlocd(i-2, j+1)+7.d0*(9.d0*tlocd(i-1, j-1)-tlocd(i-1, j-2&
&       )+9.d0*tlocd(i-1, j)-tlocd(i-1, j+1))+7.d0*(9.d0*tlocd(i, j-1)-&
&       tlocd(i, j-2)+9.d0*tlocd(i, j)-tlocd(i, j+1))+tlocd(i+1, j-2)-&
&       9.d0*tlocd(i+1, j-1)+tlocd(i+1, j+1)-9.d0*tlocd(i+1, j))
      val_sd0 = ccross*(tlocd0(i-2, j-2)-9.d0*tlocd0(i-2, j-1)-9.d0*&
&       tlocd0(i-2, j)+tlocd0(i-2, j+1)+7.d0*(9.d0*tlocd0(i-1, j-1)-&
&       tlocd0(i-1, j-2)+9.d0*tlocd0(i-1, j)-tlocd0(i-1, j+1))+7.d0*(&
&       9.d0*tlocd0(i, j-1)-tlocd0(i, j-2)+9.d0*tlocd0(i, j)-tlocd0(i, j&
&       +1))+tlocd0(i+1, j-2)-9.d0*tlocd0(i+1, j-1)+tlocd0(i+1, j+1)-&
&       9.d0*tlocd0(i+1, j))
      val_s = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-2, j-1)+9.d0*tloc(i-&
&       2, j)-tloc(i-2, j+1))+7.d0*(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+&
&       9.d0*tloc(i-1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(&
&       i, j-1)+9.d0*tloc(i, j)-tloc(i, j+1))-(-tloc(i+1, j-2)+9.d0*tloc&
&       (i+1, j-1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1)))
      val_edd = twentyfourth*(26.d0*tlocdd(i, j-1)-tlocdd(i, j)-tlocdd(i&
&       , j-2))
      val_ed = twentyfourth*(26.d0*tlocd(i, j-1)-tlocd(i, j)-tlocd(i, j-&
&       2))
      val_ed0 = twentyfourth*(26.d0*tlocd0(i, j-1)-tlocd0(i, j)-tlocd0(i&
&       , j-2))
      val_e = twentyfourth*(-tloc(i, j)+26.d0*tloc(i, j-1)-tloc(i, j-2))
      val_odd = twentyfourth*(26.d0*tlocdd(i, j)-tlocdd(i, j+1)-tlocdd(i&
&       , j-1))
      val_od = twentyfourth*(26.d0*tlocd(i, j)-tlocd(i, j+1)-tlocd(i, j-&
&       1))
      val_od0 = twentyfourth*(26.d0*tlocd0(i, j)-tlocd0(i, j+1)-tlocd0(i&
&       , j-1))
      val_o = twentyfourth*(-tloc(i, j+1)+26.d0*tloc(i, j)-tloc(i, j-1))
      txdd = volm1*(nx_n*val_ndd+nx_s*val_sdd+nx_o*val_odd+nx_e*val_edd)
      txd = volm1*(nx_n*val_nd+nx_s*val_sd+nx_o*val_od+nx_e*val_ed)
      txd0 = volm1*(nx_n*val_nd0+nx_s*val_sd0+nx_o*val_od0+nx_e*val_ed0)
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      tydd = volm1*(ny_n*val_ndd+ny_s*val_sdd+ny_o*val_odd+ny_e*val_edd)
      tyd = volm1*(ny_n*val_nd+ny_s*val_sd+ny_o*val_od+ny_e*val_ed)
      tyd0 = volm1*(ny_n*val_nd0+ny_s*val_sd0+ny_o*val_od0+ny_e*val_ed0)
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      uudd = 0.0625d0*(9.d0*velxdd(i, j-1)-velxdd(i, j-2)+9.d0*velxdd(i&
&       , j)-velxdd(i, j+1))
      uud = 0.0625d0*(9.d0*velxd(i, j-1)-velxd(i, j-2)+9.d0*velxd(i, j)-&
&       velxd(i, j+1))
      uud0 = 0.0625d0*(9.d0*velxd0(i, j-1)-velxd0(i, j-2)+9.d0*velxd0(i&
&       , j)-velxd0(i, j+1))
      uu = 0.0625d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0*velx(i, j)-&
&       velx(i, j+1))
      vvdd = 0.0625d0*(9.d0*velydd(i, j-1)-velydd(i, j-2)+9.d0*velydd(i&
&       , j)-velydd(i, j+1))
      vvd = 0.0625d0*(9.d0*velyd(i, j-1)-velyd(i, j-2)+9.d0*velyd(i, j)-&
&       velyd(i, j+1))
      vvd0 = 0.0625d0*(9.d0*velyd0(i, j-1)-velyd0(i, j-2)+9.d0*velyd0(i&
&       , j)-velyd0(i, j+1))
      vv = 0.0625d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0*vely(i, j)-&
&       vely(i, j+1))
      wwdd = 0.0625d0*(9.d0*velzdd(i, j-1)-velzdd(i, j-2)+9.d0*velzdd(i&
&       , j)-velzdd(i, j+1))
      wwd = 0.0625d0*(9.d0*velzd(i, j-1)-velzd(i, j-2)+9.d0*velzd(i, j)-&
&       velzd(i, j+1))
      wwd0 = 0.0625d0*(9.d0*velzd0(i, j-1)-velzd0(i, j-2)+9.d0*velzd0(i&
&       , j)-velzd0(i, j+1))
      ww = 0.0625d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0*velz(i, j)-&
&       velz(i, j+1))
!
      mmudd = 0.0625d0*(9.d0*mudd(i, j-1)-mudd(i, j-2)+9.d0*mudd(i, j)-&
&       mudd(i, j+1))
      mmud = 0.0625d0*(9.d0*mud(i, j-1)-mud(i, j-2)+9.d0*mud(i, j)-mud(i&
&       , j+1))
      mmud0 = 0.0625d0*(9.d0*mud0(i, j-1)-mud0(i, j-2)+9.d0*mud0(i, j)-&
&       mud0(i, j+1))
      mmu = 0.0625d0*(-mu(i, j-2)+9.d0*mu(i, j-1)+9.d0*mu(i, j)-mu(i, j+&
&       1))
      lambdadd = cpprandtl*mmudd
      lambdad = cpprandtl*mmud
      lambdad0 = cpprandtl*mmud0
      lambda = mmu*cpprandtl
!
      fvrou2dd = twothird*(mmud*(two*uxd0-vyd0)+(two*ux-vy)*mmudd+(two*&
&       uxd-vyd)*mmud0+mmu*(two*uxdd-vydd))
      fvrou2d = twothird*((two*ux-vy)*mmud+mmu*(two*uxd-vyd))
      fvrou2d0 = twothird*((two*ux-vy)*mmud0+mmu*(two*uxd0-vyd0))
      fvrou2 = twothird*mmu*(two*ux-vy)
      fvrov2dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      fvrov2d = (uy+vx)*mmud + mmu*(uyd+vxd)
      fvrov2d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      fvrov2 = mmu*(uy+vx)
      fvrow2dd = mmud*wxd0 + wx*mmudd + wxd*mmud0 + mmu*wxdd
      fvrow2d = wx*mmud + mmu*wxd
      fvrow2d0 = wx*mmud0 + mmu*wxd0
      fvrow2 = mmu*wx
      fvroe2dd = lambdad*txd0 + tx*lambdadd + txd*lambdad0 + lambda*txdd&
&       + uud*fvrou2d0 + fvrou2*uudd + fvrou2d*uud0 + uu*fvrou2dd + vvd*&
&       fvrov2d0 + fvrov2*vvdd + fvrov2d*vvd0 + vv*fvrov2dd + wwd*&
&       fvrow2d0 + fvrow2*wwdd + fvrow2d*wwd0 + ww*fvrow2dd
! fvroe2 = (lambda*tx + uu*fvrou2 + vv*fvrov2)
      gvrou2dd = mmud*(uyd0+vxd0) + (uy+vx)*mmudd + (uyd+vxd)*mmud0 + &
&       mmu*(uydd+vxdd)
      gvrou2d = (uy+vx)*mmud + mmu*(uyd+vxd)
      gvrou2d0 = (uy+vx)*mmud0 + mmu*(uyd0+vxd0)
      gvrou2 = mmu*(uy+vx)
      gvrov2dd = twothird*(mmud*(two*vyd0-uxd0)+(two*vy-ux)*mmudd+(two*&
&       vyd-uxd)*mmud0+mmu*(two*vydd-uxdd))
      gvrov2d = twothird*((two*vy-ux)*mmud+mmu*(two*vyd-uxd))
      gvrov2d0 = twothird*((two*vy-ux)*mmud0+mmu*(two*vyd0-uxd0))
      gvrov2 = twothird*mmu*(-ux+two*vy)
      gvrow2dd = mmud*wyd0 + wy*mmudd + wyd*mmud0 + mmu*wydd
      gvrow2d = wy*mmud + mmu*wyd
      gvrow2d0 = wy*mmud0 + mmu*wyd0
      gvrow2 = mmu*wy
      gvroe2dd = lambdad*tyd0 + ty*lambdadd + tyd*lambdad0 + lambda*tydd&
&       + uud*gvrou2d0 + gvrou2*uudd + gvrou2d*uud0 + uu*gvrou2dd + vvd*&
&       gvrov2d0 + gvrov2*vvdd + gvrov2d*vvd0 + vv*gvrov2dd + wwd*&
&       gvrow2d0 + gvrow2*wwdd + gvrow2d*wwd0 + ww*gvrow2dd
! gvroe2 = (lambda*ty + uu*gvrou2 + vv*gvrov2)
!!  fvrou2 = TWOTHIRD*mmu*( TWO*ux -     vy  -  wz  )
!!  fvrov2 =          mmu*(     uy +     vx         )
!!  fvrow2 =          mmu*(     uz           +  wx  )
!!  fvroe2 = (lambda*tx + uu*fvrou2 + vv*fvrov2 + ww * fvrow2)
!!
!!  gvrou2 =          mmu*(     uy +     vx       )
!!  gvrov2 = TWOTHIRD*mmu*(    -ux + TWO*vy -  wz )
!!  gvrow2 =          mmu*(              vz +  wy )
!!  gvroe2 = (lambda*ty + uu*gvrou2 + vv*gvrov2 + ww*gvrow2)
      sc1 = nx(i, j, 1)
      sc2 = ny(i, j, 1)
      arg1 = sc1*sc1 + sc2*sc2
      sn = SQRT(arg1)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
      hndd(i, j, 1, 1) = fxro1dd
!
      hndd(i, j, 2, 1) = fxrou1dd - sn*(nxloc*fvrou1dd+nyloc*gvrou1dd)
!
      hndd(i, j, 3, 1) = fxrov1dd - sn*(nxloc*fvrov1dd+nyloc*gvrov1dd)
!
      hndd(i, j, 4, 1) = fxrow1dd - sn*(nxloc*fvrow1dd+nyloc*gvrow1dd)
! hn(i,j,4,1) = ZERO
!
      hndd(i, j, 5, 1) = fxroe1dd - sn*(nxloc*fvroe1dd+nyloc*gvroe1dd)
      sc1 = nx(i, j, 2)
      sc2 = ny(i, j, 2)
      arg1 = sc1*sc1 + sc2*sc2
      sn = SQRT(arg1)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
      hndd(i, j, 1, 2) = fxro2dd
!
      hndd(i, j, 2, 2) = fxrou2dd - sn*(nxloc*fvrou2dd+nyloc*gvrou2dd)
!
      hndd(i, j, 3, 2) = fxrov2dd - sn*(nxloc*fvrov2dd+nyloc*gvrov2dd)
!
      hndd(i, j, 4, 2) = fxrow2dd - sn*(nxloc*fvrow2dd+nyloc*gvrow2dd)
! hn(i,j,4,2) = ZERO
!
      hndd(i, j, 5, 2) = fxroe2dd - sn*(nxloc*fvroe2dd+nyloc*gvroe2dd)
    END DO
  END DO
  residudd = 0.0_8
!
! fluxes balance
  DO j=1,jm
!GCC$ IVDEP
    DO i=1,im
      residudd(i, j, 1) = hndd(i, j, 1, 1) - hndd(i+1, j, 1, 1) + hndd(i&
&       , j, 1, 2) - hndd(i, j+1, 1, 2)
      residudd(i, j, 2) = hndd(i, j, 2, 1) - hndd(i+1, j, 2, 1) + hndd(i&
&       , j, 2, 2) - hndd(i, j+1, 2, 2)
      residudd(i, j, 3) = hndd(i, j, 3, 1) - hndd(i+1, j, 3, 1) + hndd(i&
&       , j, 3, 2) - hndd(i, j+1, 3, 2)
      residudd(i, j, 4) = hndd(i, j, 4, 1) - hndd(i+1, j, 4, 1) + hndd(i&
&       , j, 4, 2) - hndd(i, j+1, 4, 2)
      residudd(i, j, 5) = hndd(i, j, 5, 1) - hndd(i+1, j, 5, 1) + hndd(i&
&       , j, 5, 2) - hndd(i, j+1, 5, 2)
    END DO
  END DO
END SUBROUTINE FLUX_NUM_DNC5_NOWALL_NODISS_2D_D_D
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

