!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of bordersfromcenters_rectangular_2d in reverse (adjoint) mode (with options with!SliceDeadControl with!SliceD
!eadInstrs with!StaticTaping):
!   gradient     of useful results: xc ymin xmin yc x0 y0
!   with respect to varying inputs: xc ymin xmin yc x0 y0
!   RW status of diff variables: xc:incr ymin:incr xmin:incr yc:incr
!                x0:in-out y0:in-out
! This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed w
!ith this file, You can obtain one at https://mozilla.org/MPL/2.0/.
SUBROUTINE BORDERSFROMCENTERS_RECTANGULAR_2D_B(x0, x0b, y0, y0b, xc, xcb&
& , yc, ycb, im, jm, xmin, xminb, ymin, yminb)
  IMPLICIT NONE
! variables for dimension -----------------------------------------
  INTEGER :: im, jm, gh
! required arguments ----------------------------------------------
! Returned objects ------------------------------------------------
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: x0
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: x0b
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: y0
  REAL*8, DIMENSION(im+1, jm+1), INTENT(INOUT) :: y0b
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: xc
  REAL*8, DIMENSION(im, jm) :: xcb
  REAL*8, DIMENSION(im, jm), INTENT(IN) :: yc
  REAL*8, DIMENSION(im, jm) :: ycb
  REAL*8, INTENT(IN) :: xmin, ymin
  REAL*8 :: xminb, yminb
! Non-required arguments -------------------------------------------
  INTEGER :: i, j, g, dummy
! ------------------------------------------------------------------
  REAL*8 :: two, half, fourth
  two = 2.d0
  DO j=jm+1,1,-1
    y0b(im, j) = y0b(im, j) + y0b(im+1, j)
    y0b(im+1, j) = 0.0_8
  END DO
  DO i=im+1,1,-1
    x0b(i, jm) = x0b(i, jm) + x0b(i, jm+1)
    x0b(i, jm+1) = 0.0_8
  END DO
  DO j=jm+1,2,-1
    DO i=im,1,-1
      ycb(i, j-1) = ycb(i, j-1) + two*y0b(i, j)
      y0b(i, j-1) = y0b(i, j-1) - y0b(i, j)
      y0b(i, j) = 0.0_8
    END DO
  END DO
  DO j=jm,1,-1
    DO i=im+1,2,-1
      xcb(i-1, j) = xcb(i-1, j) + two*x0b(i, j)
      x0b(i-1, j) = x0b(i-1, j) - x0b(i, j)
      x0b(i, j) = 0.0_8
    END DO
  END DO
  DO i=im+1,1,-1
    yminb = yminb + y0b(i, 1)
    y0b(i, 1) = 0.0_8
  END DO
  DO j=jm+1,1,-1
    xminb = xminb + x0b(1, j)
    x0b(1, j) = 0.0_8
  END DO
END SUBROUTINE BORDERSFROMCENTERS_RECTANGULAR_2D_B

