!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of flux_num_dnc5_maxsc_2d in reverse (adjoint) mode (with options with!SliceDeadControl with!SliceDeadInstrs w
!ith!StaticTaping):
!   gradient     of useful results: residu
!   with respect to varying inputs: w residu
!   RW status of diff variables: w:out residu:in-out
! This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed w
!ith this file, You can obtain one at https://mozilla.org/MPL/2.0/
! =============================================================================
!          consistent fluxes for DNC5 2D
! =============================================================================
!
SUBROUTINE FLUX_NUM_DNC5_MAXSC_2D_B(residu, residub, w, wb, x0, y0, nx, &
& ny, xc, yc, vol, volf, gh, cp, cv, prandtl, gam, rgaz, cs, muref, tref&
& , s_suth, k2, k4, im, jm)
  IMPLICIT NONE
! variables for dimension -----------------------------------------
  INTEGER :: im, jm, gh
! required arguments ----------------------------------------------
! thermo
  REAL*8, INTENT(IN) :: cp, cv, prandtl, gam, rgaz
! dissipation
  REAL*8, INTENT(IN) :: k2, k4
! viscosity
  REAL*8, INTENT(IN) :: cs, muref, tref, s_suth
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: x0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1), INTENT(IN) :: y0
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: nx
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 2), INTENT(IN) :: ny
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: xc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: yc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh), INTENT(IN) :: vol
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2), INTENT(IN) :: volf
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(IN) :: w
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: wb
! Returned objects ------------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5), INTENT(INOUT) :: residub
! Non-required arguments -------------------------------------------
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hn
  REAL*8, DIMENSION(1-gh:im+gh+1, 1-gh:jm+gh+1, 5, 2) :: hnb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: f, g
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 5) :: fb, gb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velx
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velxb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: vely
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velyb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velz
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: velzb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tloc
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: tlocb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: p
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: pb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: mub
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradu, gradv, gradw, &
& gradmu
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh, 2) :: gradub, gradvb
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: eps2arra
  REAL*8, DIMENSION(1-gh:im+gh, 1-gh:jm+gh) :: eps2arrab
  REAL*8, DIMENSION(5) :: deltar, deltal, t
  INTEGER :: i, j, h, k, l
  REAL*8 :: nx_n, nx_s, nx_e, nx_o, volm1, ux, vx, wx, tx
  REAL*8 :: uxb, vxb, wxb, txb
  REAL*8 :: ny_n, ny_s, ny_e, ny_o, uy, vy, wy, ty
  REAL*8 :: uyb, vyb, wyb, tyb
  REAL*8 :: val_n, val_s, val_e, val_o
  REAL*8 :: val_nb, val_sb, val_eb, val_ob
  REAL*8 :: fxro1, fxro2, fxrou1, fxrou2, fxrov1, fxrov2, fxrow1, fxrow2&
& , fxroe1, fxroe2
  REAL*8 :: fxro1b, fxro2b, fxrou1b, fxrou2b, fxrov1b, fxrov2b, fxrow1b&
& , fxrow2b, fxroe1b, fxroe2b
  REAL*8 :: fvro1, fvro2, fvrou1, fvrou2, fvrov1, fvrov2, fvrow1, fvrow2&
& , fvroe1, fvroe2
  REAL*8 :: fvrou1b, fvrou2b, fvrov1b, fvrov2b, fvrow1b, fvrow2b, &
& fvroe1b, fvroe2b
  REAL*8 :: gvro1, gvro2, gvrou1, gvrou2, gvrov1, gvrov2, gvrow1, gvrow2&
& , gvroe1, gvroe2
  REAL*8 :: gvrou1b, gvrou2b, gvrov1b, gvrov2b, gvrow1b, gvrow2b, &
& gvroe1b, gvroe2b
  REAL*8 :: dissro1, dissro2, dissrou1, dissrou2, dissrov1, dissrov2, &
& dissrow1, dissrow2, dissroe1, dissroe2
  REAL*8 :: dissro1b, dissro2b, dissrou1b, dissrou2b, dissrov1b, &
& dissrov2b, dissrow1b, dissrow2b, dissroe1b, dissroe2b
  REAL*8 :: cpprandtl, mmu, lambda, uu, vv, ww, ro, rom1, htot, eloc, ec
  REAL*8 :: mmub, lambdab, uub, vvb, wwb, rob, rom1b, htotb, elocb, ecb
  REAL*8 :: predro1, predrou1, predrov1, predrow1, predroe1, eps2, eps4
  REAL*8 :: predro1b, predrou1b, predrov1b, predrow1b, predroe1b, eps2b&
& , eps4b
  REAL*8 :: predro2, predrou2, predrov2, predrow2, predroe2, rspec, &
& rspecbis
  REAL*8 :: predro2b, predrou2b, predrov2b, predrow2b, predroe2b, rspecb&
& , rspecbisb
  REAL*8 :: divu2, vort2, dx, dy, dxm1, dym1, dxm2, dym2
  REAL*8 :: divu2b, vort2b, dxm1b
  REAL*8 :: nxloc, nyloc, sn, invsn, sc1, sc2
  REAL*8 :: gui, gvi, gwi, gmui
  REAL*8 :: guib, gvib
  REAL*8 :: guj, gvj, gwj, gmuj
  REAL*8 :: gujb, gvjb
  REAL*8 :: rhom, rhomr, rhoml, rhom1l, c2l, c2r, rr, r, u, ur, ul, vr, &
& vl, wr, wl, c2x, nx2, ny2
  REAL*8 :: rhomrb, rhomlb, c2lb, c2rb, rrb, rb, ub, urb, ulb, vrb, vlb&
& , c2xb
  REAL*8 :: ab, sq, ducros1, ducros2, k_sensor1, k_sensor2, sqbis
  REAL*8 :: abb, sqb, ducros1b, k_sensor1b, sqbisb
  REAL*8 :: b1, b2, b3, b4, b5, c1, c2, c3, c4, c5, d1, d2, d3, wiggle, &
& denom, betas
  REAL*8 :: c5d0, c5d1, c5d2, c5d3, c5d4, c5d5
  REAL*8 :: c3d0, c3d1, c3d2, c3d3, c3d4, c3d5
  REAL*8 :: pw, ct0, ct1, ct2, omrr, coef, test, diffro, diffrou, &
& diffrov, diffrow, diffroe, v
  REAL*8 :: omrrb, coefb, diffrob, diffroub, diffrovb, diffrowb, &
& diffroeb, vb
  REAL*8 :: half, one, zero, two, twothird, fourth, twelfth, cvm1, &
& twelve
  REAL*8 :: twentyfourth, ccross
  INTRINSIC SQRT
  INTRINSIC ABS
  INTRINSIC MAX
  INTRINSIC TANH
  REAL*8 :: x1
  REAL*8 :: x2
  REAL*8 :: x2b
  REAL*8 :: y1
  REAL*8 :: y1b
  REAL*8 :: x3
  REAL*8 :: x3b
  REAL*8 :: y2
  REAL*8 :: y2b
  REAL*8 :: y3
  REAL*8 :: y3b
  REAL*8 :: y4
  REAL*8 :: y4b
  REAL*8 :: y5
  REAL*8 :: y5b
  REAL*8 :: y6
  REAL*8 :: y6b
  REAL*8 :: y7
  REAL*8 :: y7b
  REAL*8 :: y8
  REAL*8 :: y8b
  REAL*8 :: y9
  REAL*8 :: y9b
  REAL*8 :: y10
  REAL*8 :: y10b
  REAL*8 :: y11
  REAL*8 :: y11b
  REAL*8 :: y12
  REAL*8 :: y12b
  REAL*8 :: y13
  REAL*8 :: y13b
  REAL*8 :: abs0
  REAL*8 :: abs0b
  REAL*8 :: abs1
  REAL*8 :: abs1b
  REAL*8 :: temp
  REAL*8 :: tempb
  REAL*8 :: temp0
  REAL*8 :: tempb0
  REAL*8 :: temp1
  REAL*8 :: tempb1
  REAL*8 :: ad_save
  REAL*8 :: ad_save0
  REAL*8 :: ad_save1
  REAL*8 :: ad_save2
  REAL*8 :: ad_save3
  REAL*8 :: ad_save4
  REAL*8 :: ad_save5
  REAL*8 :: ad_save6
  REAL*8 :: ad_save7
  REAL*8 :: ad_save8
  REAL*8 :: ad_save9
  REAL*8 :: ad_save10
  REAL*8 :: ad_save11
  REAL*8 :: ad_save12
  REAL*8 :: ad_save13
  REAL*8 :: ad_save14
  INTEGER :: ad_branch
  INTEGER :: ad_branch0
  INTEGER :: ad_branch1
  INTEGER :: ad_branch2
  INTEGER :: ad_branch3
  INTEGER :: ad_branch4
  INTEGER :: ad_branch5
  INTEGER :: ad_branch6
  INTEGER :: ad_branch7
  INTEGER :: ad_branch8
  INTEGER :: ad_branch9
  INTEGER :: ad_branch10
  INTEGER :: ad_branch11
  INTEGER :: ad_branch12
  INTEGER :: ad_branch13
  INTEGER :: ad_branch14
  INTEGER :: ad_branch15
  INTEGER :: ad_branch16
  INTEGER :: ad_branch17
  INTEGER :: ad_branch18
! -----------------------------------------------------------------
!
  half = 0.5d0
  one = 1.d0
  zero = 0.d0
  two = 2.d0
  twothird = 2.d0/3.d0
  twelfth = 0.25d0/3.d0
  cpprandtl = cp/prandtl
  cvm1 = one/cv
  twentyfourth = one/24.d0
  ccross = twelfth*0.0625d0
! k2 = 1.d0
! k4 = 1.d0/60d0 already in coef for predictor
! Coef for grad o4
  denom = 1.d0/12.d0
  b1 = 8.d0*denom
  b2 = -denom
! Coef for grad o6
  denom = 1.d0/60.d0
! b1 =  45.d0 * denom
! b2 = - 9.d0 * denom
! b3 =          denom
!expression for FV
! c3 = b3
! c2 = c3 + b2
! c1 = c2 + b1
  c1 = 37.d0*denom
  c2 = -(8.d0*denom)
  c3 = denom
!predictor
  d1 = 10.d0*denom
  d2 = 5.d0*denom
  d3 = denom
! for Sutherland
  betas = muref*(tref+cs)/(SQRT(tref)*tref)
!$FWD-OF II-LOOP 
! Primitives
  DO j=1-gh,jm+gh
!DIR$ IVDEP
    DO i=1-gh,im+gh
      ro = w(i, j, 1)
      rom1 = one/ro
      velx(i, j) = w(i, j, 2)*rom1
      vely(i, j) = w(i, j, 3)*rom1
      velz(i, j) = w(i, j, 4)*rom1
!
      ec = half*(velx(i, j)*velx(i, j)+vely(i, j)*vely(i, j)+velz(i, j)*&
&       velz(i, j))
! ec  = HALF*( velx(i,j)*velx(i,j) &
!            + vely(i,j)*vely(i,j))
!
      eloc = (w(i, j, 5)-ec*ro)*rom1
!
      tloc(i, j) = eloc*cvm1
!
      p(i, j) = (gam-one)*ro*eloc
!  p(i,j)  = ro*rgaz*tloc(i,j)
      htot = (w(i, j, 5)+p(i, j))*rom1
      f(i, j, 1) = w(i, j, 2)
      f(i, j, 2) = w(i, j, 2)*velx(i, j) + p(i, j)
      f(i, j, 3) = w(i, j, 2)*vely(i, j)
      f(i, j, 4) = w(i, j, 2)*velz(i, j)
      f(i, j, 5) = w(i, j, 2)*htot
      g(i, j, 1) = w(i, j, 3)
      g(i, j, 2) = w(i, j, 3)*velx(i, j)
      g(i, j, 3) = w(i, j, 3)*vely(i, j) + p(i, j)
      g(i, j, 4) = w(i, j, 3)*velz(i, j)
      g(i, j, 5) = w(i, j, 3)*htot
!h(i,j,1)  = w(i,j,4)
!h(i,j,2)  = w(i,j,4) * velx(i,j)
!h(i,j,3)  = w(i,j,4) * vely(i,j)
!h(i,j,4)  = w(i,j,4) * velz(i,j) + p(i,j)
!h(i,j,5)  = w(i,j,4) * htot
      mu(i, j) = betas/(tloc(i, j)+s_suth)*SQRT(tloc(i, j))*tloc(i, j)
    END DO
  END DO
!$FWD-OF II-LOOP 
  DO j=1,jm
!DIR$ IVDEP
    DO i=1,im
! #include "rhs/gradop_7pi.F"
! #include "rhs/gradop_7pj.F"
!idir
      gui = b1*(velx(i+1, j)-velx(i-1, j)) + b2*(velx(i+2, j)-velx(i-2, &
&       j))
      gvi = b1*(vely(i+1, j)-vely(i-1, j)) + b2*(vely(i+2, j)-vely(i-2, &
&       j))
      gwi = b1*(velz(i+1, j)-velz(i-1, j)) + b2*(velz(i+2, j)-velz(i-2, &
&       j))
      gmui = b1*(mu(i+1, j)-mu(i-1, j)) + b2*(mu(i+2, j)-mu(i-2, j))
!jdir
      guj = b1*(velx(i, j+1)-velx(i, j-1)) + b2*(velx(i, j+2)-velx(i, j-&
&       2))
      gvj = b1*(vely(i, j+1)-vely(i, j-1)) + b2*(vely(i, j+2)-vely(i, j-&
&       2))
      gwj = b1*(velz(i, j+1)-velz(i, j-1)) + b2*(velz(i, j+2)-velz(i, j-&
&       2))
      gmuj = b1*(mu(i, j+1)-mu(i, j-1)) + b2*(mu(i, j+2)-mu(i, j-2))
      volm1 = one/vol(i, j)
      dxm1 = half*(nx(i, j, 1)+nx(i+1, j, 1))*volm1
      dxm2 = half*(nx(i, j, 2)+nx(i, j+1, 2))*volm1
      dym1 = half*(ny(i, j, 1)+ny(i+1, j, 1))*volm1
      dym2 = half*(ny(i, j, 2)+ny(i, j+1, 2))*volm1
      gradu(i, j, 1) = dxm1*gui + dxm2*guj
      gradv(i, j, 1) = dxm1*gvi + dxm2*gvj
      gradw(i, j, 1) = dxm1*gwi + dxm2*gwj
      gradmu(i, j, 1) = dxm1*gmui + dxm2*gmuj
      gradu(i, j, 2) = dym1*gui + dym2*guj
      gradv(i, j, 2) = dym1*gvi + dym2*gvj
      gradw(i, j, 2) = dym1*gwi + dym2*gwj
      gradmu(i, j, 2) = dym1*gmui + dym2*gmuj
    END DO
  END DO
!
! trick for ducros in dissipation
  DO i=1,2
    DO h=1,gh
      gradu(:, 1-h, :) = two*gradu(:, 2-h, :) - gradu(:, 3-h, :)
      gradv(:, 1-h, :) = two*gradv(:, 2-h, :) - gradv(:, 3-h, :)
      gradu(:, jm+h, :) = two*gradu(:, jm-1+h, :) - gradu(:, jm-2+h, :)
      gradv(:, jm+h, :) = two*gradv(:, jm-1+h, :) - gradv(:, jm-2+h, :)
      gradu(1-h, :, :) = two*gradu(2-h, :, :) - gradu(3-h, :, :)
      gradv(1-h, :, :) = two*gradv(2-h, :, :) - gradv(3-h, :, :)
      gradu(im+h, :, :) = two*gradu(im-1+h, :, :) - gradu(im-2+h, :, :)
      gradv(im+h, :, :) = two*gradv(im-1+h, :, :) - gradv(im-2+h, :, :)
    END DO
  END DO
  hnb = 0.0_8
!$BWD-OF II-LOOP 
  DO j=1,jm
!$BWD-OF II-LOOP 
!DIR$ IVDEP
    DO i=1,im
      hnb(i, j, 5, 1) = hnb(i, j, 5, 1) + residub(i, j, 5)
      hnb(i+1, j, 5, 1) = hnb(i+1, j, 5, 1) - residub(i, j, 5)
      hnb(i, j, 5, 2) = hnb(i, j, 5, 2) + residub(i, j, 5)
      hnb(i, j+1, 5, 2) = hnb(i, j+1, 5, 2) - residub(i, j, 5)
      residub(i, j, 5) = 0.0_8
      hnb(i, j, 4, 1) = hnb(i, j, 4, 1) + residub(i, j, 4)
      hnb(i+1, j, 4, 1) = hnb(i+1, j, 4, 1) - residub(i, j, 4)
      hnb(i, j, 4, 2) = hnb(i, j, 4, 2) + residub(i, j, 4)
      hnb(i, j+1, 4, 2) = hnb(i, j+1, 4, 2) - residub(i, j, 4)
      residub(i, j, 4) = 0.0_8
      hnb(i, j, 3, 1) = hnb(i, j, 3, 1) + residub(i, j, 3)
      hnb(i+1, j, 3, 1) = hnb(i+1, j, 3, 1) - residub(i, j, 3)
      hnb(i, j, 3, 2) = hnb(i, j, 3, 2) + residub(i, j, 3)
      hnb(i, j+1, 3, 2) = hnb(i, j+1, 3, 2) - residub(i, j, 3)
      residub(i, j, 3) = 0.0_8
      hnb(i, j, 2, 1) = hnb(i, j, 2, 1) + residub(i, j, 2)
      hnb(i+1, j, 2, 1) = hnb(i+1, j, 2, 1) - residub(i, j, 2)
      hnb(i, j, 2, 2) = hnb(i, j, 2, 2) + residub(i, j, 2)
      hnb(i, j+1, 2, 2) = hnb(i, j+1, 2, 2) - residub(i, j, 2)
      residub(i, j, 2) = 0.0_8
      hnb(i, j, 1, 1) = hnb(i, j, 1, 1) + residub(i, j, 1)
      hnb(i+1, j, 1, 1) = hnb(i+1, j, 1, 1) - residub(i, j, 1)
      hnb(i, j, 1, 2) = hnb(i, j, 1, 2) + residub(i, j, 1)
      hnb(i, j+1, 1, 2) = hnb(i, j+1, 1, 2) - residub(i, j, 1)
      residub(i, j, 1) = 0.0_8
    END DO
  END DO
  wb = 0.0_8
  fb = 0.0_8
  gb = 0.0_8
  pb = 0.0_8
  velxb = 0.0_8
  velyb = 0.0_8
  velzb = 0.0_8
  gradub = 0.0_8
  gradvb = 0.0_8
  tlocb = 0.0_8
  eps2arrab = 0.0_8
  mub = 0.0_8
!$BWD-OF II-LOOP 
  DO j=1,jm+1
!$BWD-OF II-LOOP 
!DIR$ IVDEP
    DO i=1,im+1
!
      predro1 = -(d3*w(i-3, j, 1)) + d2*w(i-2, j, 1) - d1*w(i-1, j, 1) +&
&       d1*w(i, j, 1) - d2*w(i+1, j, 1) + d3*w(i+2, j, 1)
      predrou1 = -(d3*w(i-3, j, 2)) + d2*w(i-2, j, 2) - d1*w(i-1, j, 2) &
&       + d1*w(i, j, 2) - d2*w(i+1, j, 2) + d3*w(i+2, j, 2)
      predrov1 = -(d3*w(i-3, j, 3)) + d2*w(i-2, j, 3) - d1*w(i-1, j, 3) &
&       + d1*w(i, j, 3) - d2*w(i+1, j, 3) + d3*w(i+2, j, 3)
      predrow1 = -(d3*w(i-3, j, 4)) + d2*w(i-2, j, 4) - d1*w(i-1, j, 4) &
&       + d1*w(i, j, 4) - d2*w(i+1, j, 4) + d3*w(i+2, j, 4)
      predroe1 = -(d3*w(i-3, j, 5)) + d2*w(i-2, j, 5) - d1*w(i-1, j, 5) &
&       + d1*w(i, j, 5) - d2*w(i+1, j, 5) + d3*w(i+2, j, 5)
      predro2 = -(d3*w(i, j-3, 1)) + d2*w(i, j-2, 1) - d1*w(i, j-1, 1) +&
&       d1*w(i, j, 1) - d2*w(i, j+1, 1) + d3*w(i, j+2, 1)
      predrou2 = -(d3*w(i, j-3, 2)) + d2*w(i, j-2, 2) - d1*w(i, j-1, 2) &
&       + d1*w(i, j, 2) - d2*w(i, j+1, 2) + d3*w(i, j+2, 2)
      predrov2 = -(d3*w(i, j-3, 3)) + d2*w(i, j-2, 3) - d1*w(i, j-1, 3) &
&       + d1*w(i, j, 3) - d2*w(i, j+1, 3) + d3*w(i, j+2, 3)
      predrow2 = -(d3*w(i, j-3, 4)) + d2*w(i, j-2, 4) - d1*w(i, j-1, 4) &
&       + d1*w(i, j, 4) - d2*w(i, j+1, 4) + d3*w(i, j+2, 4)
      predroe2 = -(d3*w(i, j-3, 5)) + d2*w(i, j-2, 5) - d1*w(i, j-1, 5) &
&       + d1*w(i, j, 5) - d2*w(i, j+1, 5) + d3*w(i, j+2, 5)
! grad for viscous fluxes o4 - 5p
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccros = TWELFTH*0.0625d0
      volm1 = volf(i, j, 1)
      nx_n = half*(nx(i+1, j, 1)+nx(i, j, 1))
      nx_s = -(half*(nx(i-1, j, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i-1, j+1, 2)+nx(i, j+1, 2))
      nx_e = -(half*(nx(i-1, j, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j, 1)+ny(i, j, 1))
      ny_s = -(half*(ny(i-1, j, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i-1, j+1, 2)+ny(i, j+1, 2))
      ny_e = -(half*(ny(i-1, j, 2)+ny(i, j, 2)))
      val_n = twentyfourth*(-velx(i+1, j)+26.d0*velx(i, j)-velx(i-1, j))
      val_s = twentyfourth*(-velx(i, j)+26.d0*velx(i-1, j)-velx(i-2, j))
      val_e = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-1, j-2)+9.d0*velx(i&
&       , j-2)-velx(i+1, j-2))+7.d0*(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)&
&       +9.d0*velx(i, j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx&
&       (i-1, j)+9.d0*velx(i, j)-velx(i+1, j))-(-velx(i-2, j+1)+9.d0*&
&       velx(i-1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1)))
      val_o = ccross*(-(-velx(i-2, j-1)+9.d0*velx(i-1, j-1)+9.d0*velx(i&
&       , j-1)-velx(i+1, j-1))+7.d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+&
&       9.d0*velx(i, j)-velx(i+1, j))+7.d0*(-velx(i-2, j+1)+9.d0*velx(i-&
&       1, j+1)+9.d0*velx(i, j+1)-velx(i+1, j+1))-(-velx(i-2, j+2)+9.d0*&
&       velx(i-1, j+2)+9.d0*velx(i, j+2)-velx(i+1, j+2)))
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_n = twentyfourth*(-vely(i+1, j)+26.d0*vely(i, j)-vely(i-1, j))
      val_s = twentyfourth*(-vely(i, j)+26.d0*vely(i-1, j)-vely(i-2, j))
      val_e = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-1, j-2)+9.d0*vely(i&
&       , j-2)-vely(i+1, j-2))+7.d0*(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)&
&       +9.d0*vely(i, j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely&
&       (i-1, j)+9.d0*vely(i, j)-vely(i+1, j))-(-vely(i-2, j+1)+9.d0*&
&       vely(i-1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1)))
      val_o = ccross*(-(-vely(i-2, j-1)+9.d0*vely(i-1, j-1)+9.d0*vely(i&
&       , j-1)-vely(i+1, j-1))+7.d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+&
&       9.d0*vely(i, j)-vely(i+1, j))+7.d0*(-vely(i-2, j+1)+9.d0*vely(i-&
&       1, j+1)+9.d0*vely(i, j+1)-vely(i+1, j+1))-(-vely(i-2, j+2)+9.d0*&
&       vely(i-1, j+2)+9.d0*vely(i, j+2)-vely(i+1, j+2)))
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_n = twentyfourth*(-velz(i+1, j)+26.d0*velz(i, j)-velz(i-1, j))
      val_s = twentyfourth*(-velz(i, j)+26.d0*velz(i-1, j)-velz(i-2, j))
      val_e = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-1, j-2)+9.d0*velz(i&
&       , j-2)-velz(i+1, j-2))+7.d0*(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)&
&       +9.d0*velz(i, j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz&
&       (i-1, j)+9.d0*velz(i, j)-velz(i+1, j))-(-velz(i-2, j+1)+9.d0*&
&       velz(i-1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1)))
      val_o = ccross*(-(-velz(i-2, j-1)+9.d0*velz(i-1, j-1)+9.d0*velz(i&
&       , j-1)-velz(i+1, j-1))+7.d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+&
&       9.d0*velz(i, j)-velz(i+1, j))+7.d0*(-velz(i-2, j+1)+9.d0*velz(i-&
&       1, j+1)+9.d0*velz(i, j+1)-velz(i+1, j+1))-(-velz(i-2, j+2)+9.d0*&
&       velz(i-1, j+2)+9.d0*velz(i, j+2)-velz(i+1, j+2)))
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_n = twentyfourth*(-tloc(i+1, j)+26.d0*tloc(i, j)-tloc(i-1, j))
      val_s = twentyfourth*(-tloc(i, j)+26.d0*tloc(i-1, j)-tloc(i-2, j))
      val_e = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-1, j-2)+9.d0*tloc(i&
&       , j-2)-tloc(i+1, j-2))+7.d0*(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)&
&       +9.d0*tloc(i, j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc&
&       (i-1, j)+9.d0*tloc(i, j)-tloc(i+1, j))-(-tloc(i-2, j+1)+9.d0*&
&       tloc(i-1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1)))
      val_o = ccross*(-(-tloc(i-2, j-1)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i&
&       , j-1)-tloc(i+1, j-1))+7.d0*(-tloc(i-2, j)+9.d0*tloc(i-1, j)+&
&       9.d0*tloc(i, j)-tloc(i+1, j))+7.d0*(-tloc(i-2, j+1)+9.d0*tloc(i-&
&       1, j+1)+9.d0*tloc(i, j+1)-tloc(i+1, j+1))-(-tloc(i-2, j+2)+9.d0*&
&       tloc(i-1, j+2)+9.d0*tloc(i, j+2)-tloc(i+1, j+2)))
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
!
! Computation of viscous fluxes
!
      uu = 0.0625d0*(-velx(i-2, j)+9.d0*velx(i-1, j)+9.d0*velx(i, j)-&
&       velx(i+1, j))
      vv = 0.0625d0*(-vely(i-2, j)+9.d0*vely(i-1, j)+9.d0*vely(i, j)-&
&       vely(i+1, j))
      ww = 0.0625d0*(-velz(i-2, j)+9.d0*velz(i-1, j)+9.d0*velz(i, j)-&
&       velz(i+1, j))
!
      mmu = 0.0625d0*(-mu(i-2, j)+9.d0*mu(i-1, j)+9.d0*mu(i, j)-mu(i+1, &
&       j))
      lambda = mmu*cpprandtl
!
      fvrou1 = twothird*mmu*(two*ux-vy)
      fvrov1 = mmu*(uy+vx)
      fvrow1 = mmu*wx
!
      gvrou1 = mmu*(uy+vx)
      gvrov1 = twothird*mmu*(-ux+two*vy)
      gvrow1 = mmu*wy
!!  fvrou1 = TWOTHIRD*mmu*( TWO*ux -     vy  -   wz  )
!!  fvrov1 =          mmu*(     uy +     vx          )
!!  fvrow1 =          mmu*(     uz           +   wx  )
!!  fvroe1 = lambda*tx + uu*fvrou1 + vv*fvrov1 + ww * fvrow1
!!  !
!!  gvrou1 =          mmu*(     uy +     vx          )
!!  gvrov1 = TWOTHIRD*mmu*(    -ux + TWO*vy   -  wz  )
!!  gvrow1 =          mmu*(              vz   +  wy  )
!!  gvroe1 = lambda*ty + uu*gvrou1 + vv*gvrov1 + ww * gvrow1
! grad for viscous fluxes o4 - 5p
!
! for coef ref Zhing et al, JCP2000 ou Shen et al AIAAP 2008
! 1/16 = 0.0625 ccross = 1/12*1/16
! TWENTYFOURTH = ONE/24.d0
! ccross = TWELFTH*0.0625d0
      volm1 = volf(i, j, 2)
      nx_n = half*(nx(i+1, j-1, 1)+nx(i+1, j, 1))
      nx_s = -(half*(nx(i, j-1, 1)+nx(i, j, 1)))
      nx_o = half*(nx(i, j+1, 2)+nx(i, j, 2))
      nx_e = -(half*(nx(i, j-1, 2)+nx(i, j, 2)))
!
      ny_n = half*(ny(i+1, j-1, 1)+ny(i+1, j, 1))
      ny_s = -(half*(ny(i, j-1, 1)+ny(i, j, 1)))
      ny_o = half*(ny(i, j+1, 2)+ny(i, j, 2))
      ny_e = -(half*(ny(i, j-1, 2)+ny(i, j, 2)))
      val_n = ccross*(-(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+9.d0*velx(i-&
&       1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0&
&       *velx(i, j)-velx(i, j+1))+7.d0*(-velx(i+1, j-2)+9.d0*velx(i+1, j&
&       -1)+9.d0*velx(i+1, j)-velx(i+1, j+1))-(-velx(i+2, j-2)+9.d0*velx&
&       (i+2, j-1)+9.d0*velx(i+2, j)-velx(i+2, j+1)))
      val_s = ccross*(-(-velx(i-2, j-2)+9.d0*velx(i-2, j-1)+9.d0*velx(i-&
&       2, j)-velx(i-2, j+1))+7.d0*(-velx(i-1, j-2)+9.d0*velx(i-1, j-1)+&
&       9.d0*velx(i-1, j)-velx(i-1, j+1))+7.d0*(-velx(i, j-2)+9.d0*velx(&
&       i, j-1)+9.d0*velx(i, j)-velx(i, j+1))-(-velx(i+1, j-2)+9.d0*velx&
&       (i+1, j-1)+9.d0*velx(i+1, j)-velx(i+1, j+1)))
      val_e = twentyfourth*(-velx(i, j)+26.d0*velx(i, j-1)-velx(i, j-2))
      val_o = twentyfourth*(-velx(i, j+1)+26.d0*velx(i, j)-velx(i, j-1))
      ad_save = ux
      ux = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      ad_save0 = uy
      uy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_n = ccross*(-(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+9.d0*vely(i-&
&       1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0&
&       *vely(i, j)-vely(i, j+1))+7.d0*(-vely(i+1, j-2)+9.d0*vely(i+1, j&
&       -1)+9.d0*vely(i+1, j)-vely(i+1, j+1))-(-vely(i+2, j-2)+9.d0*vely&
&       (i+2, j-1)+9.d0*vely(i+2, j)-vely(i+2, j+1)))
      val_s = ccross*(-(-vely(i-2, j-2)+9.d0*vely(i-2, j-1)+9.d0*vely(i-&
&       2, j)-vely(i-2, j+1))+7.d0*(-vely(i-1, j-2)+9.d0*vely(i-1, j-1)+&
&       9.d0*vely(i-1, j)-vely(i-1, j+1))+7.d0*(-vely(i, j-2)+9.d0*vely(&
&       i, j-1)+9.d0*vely(i, j)-vely(i, j+1))-(-vely(i+1, j-2)+9.d0*vely&
&       (i+1, j-1)+9.d0*vely(i+1, j)-vely(i+1, j+1)))
      val_e = twentyfourth*(-vely(i, j)+26.d0*vely(i, j-1)-vely(i, j-2))
      val_o = twentyfourth*(-vely(i, j+1)+26.d0*vely(i, j)-vely(i, j-1))
      ad_save1 = vx
      vx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      ad_save2 = vy
      vy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_n = ccross*(-(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+9.d0*velz(i-&
&       1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0&
&       *velz(i, j)-velz(i, j+1))+7.d0*(-velz(i+1, j-2)+9.d0*velz(i+1, j&
&       -1)+9.d0*velz(i+1, j)-velz(i+1, j+1))-(-velz(i+2, j-2)+9.d0*velz&
&       (i+2, j-1)+9.d0*velz(i+2, j)-velz(i+2, j+1)))
      val_s = ccross*(-(-velz(i-2, j-2)+9.d0*velz(i-2, j-1)+9.d0*velz(i-&
&       2, j)-velz(i-2, j+1))+7.d0*(-velz(i-1, j-2)+9.d0*velz(i-1, j-1)+&
&       9.d0*velz(i-1, j)-velz(i-1, j+1))+7.d0*(-velz(i, j-2)+9.d0*velz(&
&       i, j-1)+9.d0*velz(i, j)-velz(i, j+1))-(-velz(i+1, j-2)+9.d0*velz&
&       (i+1, j-1)+9.d0*velz(i+1, j)-velz(i+1, j+1)))
      val_e = twentyfourth*(-velz(i, j)+26.d0*velz(i, j-1)-velz(i, j-2))
      val_o = twentyfourth*(-velz(i, j+1)+26.d0*velz(i, j)-velz(i, j-1))
      ad_save3 = wx
      wx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      ad_save4 = wy
      wy = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      val_n = ccross*(-(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+9.d0*tloc(i-&
&       1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(i, j-1)+9.d0&
&       *tloc(i, j)-tloc(i, j+1))+7.d0*(-tloc(i+1, j-2)+9.d0*tloc(i+1, j&
&       -1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1))-(-tloc(i+2, j-2)+9.d0*tloc&
&       (i+2, j-1)+9.d0*tloc(i+2, j)-tloc(i+2, j+1)))
      val_s = ccross*(-(-tloc(i-2, j-2)+9.d0*tloc(i-2, j-1)+9.d0*tloc(i-&
&       2, j)-tloc(i-2, j+1))+7.d0*(-tloc(i-1, j-2)+9.d0*tloc(i-1, j-1)+&
&       9.d0*tloc(i-1, j)-tloc(i-1, j+1))+7.d0*(-tloc(i, j-2)+9.d0*tloc(&
&       i, j-1)+9.d0*tloc(i, j)-tloc(i, j+1))-(-tloc(i+1, j-2)+9.d0*tloc&
&       (i+1, j-1)+9.d0*tloc(i+1, j)-tloc(i+1, j+1)))
      val_e = twentyfourth*(-tloc(i, j)+26.d0*tloc(i, j-1)-tloc(i, j-2))
      val_o = twentyfourth*(-tloc(i, j+1)+26.d0*tloc(i, j)-tloc(i, j-1))
      ad_save5 = tx
      tx = (val_n*nx_n+val_s*nx_s+val_o*nx_o+val_e*nx_e)*volm1
      ad_save6 = ty
      ty = (val_n*ny_n+val_s*ny_s+val_o*ny_o+val_e*ny_e)*volm1
      ad_save7 = uu
      uu = 0.0625d0*(-velx(i, j-2)+9.d0*velx(i, j-1)+9.d0*velx(i, j)-&
&       velx(i, j+1))
      ad_save8 = vv
      vv = 0.0625d0*(-vely(i, j-2)+9.d0*vely(i, j-1)+9.d0*vely(i, j)-&
&       vely(i, j+1))
      ad_save9 = ww
      ww = 0.0625d0*(-velz(i, j-2)+9.d0*velz(i, j-1)+9.d0*velz(i, j)-&
&       velz(i, j+1))
!
      ad_save10 = mmu
      mmu = 0.0625d0*(-mu(i, j-2)+9.d0*mu(i, j-1)+9.d0*mu(i, j)-mu(i, j+&
&       1))
      ad_save11 = lambda
      lambda = mmu*cpprandtl
!
      fvrou2 = twothird*mmu*(two*ux-vy)
      fvrov2 = mmu*(uy+vx)
      fvrow2 = mmu*wx
      gvrou2 = mmu*(uy+vx)
      gvrov2 = twothird*mmu*(-ux+two*vy)
      gvrow2 = mmu*wy
!!  fvrou2 = TWOTHIRD*mmu*( TWO*ux -     vy  -  wz  )
!!  fvrov2 =          mmu*(     uy +     vx         )
!!  fvrow2 =          mmu*(     uz           +  wx  )
!!  fvroe2 = (lambda*tx + uu*fvrou2 + vv*fvrov2 + ww * fvrow2)
!!
!!  gvrou2 =          mmu*(     uy +     vx       )
!!  gvrov2 = TWOTHIRD*mmu*(    -ux + TWO*vy -  wz )
!!  gvrow2 =          mmu*(              vz +  wy )
!!  gvroe2 = (lambda*ty + uu*gvrou2 + vv*gvrov2 + ww*gvrow2)
!1st direction
!
!
!
!
!
!
!1st direction
      rhomr = w(i, j, 1)
      ur = w(i, j, 2)/rhomr
      vr = w(i, j, 3)/rhomr
      c2r = gam*rgaz*tloc(i, j)
!
      rhoml = w(i, j-1, 1)
      ul = w(i, j-1, 2)/rhoml
      vl = w(i, j-1, 3)/rhoml
      c2l = gam*rgaz*tloc(i, j-1)
!
      r = SQRT(rhomr/rhoml)
      rr = one/(one+r)
      omrr = one - rr
!
      u = ul*rr + ur*omrr
      v = vl*rr + vr*omrr
!
      c2x = c2l*rr + c2r*omrr
      nx2 = nx(i, j, 2)*nx(i, j, 2) + ny(i, j, 2)*ny(i, j, 2)
      x2 = nx(i, j, 2)*u + ny(i, j, 2)*v
      IF (x2 .GE. 0.) THEN
        ab = x2
        ad_branch1 = 0
      ELSE
        ab = -x2
        ad_branch1 = 1
      END IF
      sq = SQRT(c2x*nx2)
!
      rspec = ab + sq
!
      rspecbis = rspec
      IF (rspec .LT. rspecbis) THEN
        rspec = rspecbis
        ad_branch2 = 0
      ELSE
        rspec = rspec
        ad_branch2 = 1
      END IF
      sqbis = sq
      IF (sq .LT. sqbis) THEN
        sq = sqbis
        ad_branch3 = 0
      ELSE
        sq = sq
        ad_branch3 = 1
      END IF
!$FWD-OF II-LOOP 
!1st direction
      DO l=j-gh,j+gh-1
!DIR$ IVDEP
        DO k=i-gh,i+gh-1
          IF (p(k-1, l) - two*p(k, l) + p(k+1, l) .GE. 0.) THEN
            abs0 = p(k-1, l) - two*p(k, l) + p(k+1, l)
          ELSE
            abs0 = -(p(k-1, l)-two*p(k, l)+p(k+1, l))
          END IF
          x3 = p(k-1, l) + two*p(k, l) + p(k+1, l)
          IF (x3 .GE. 0.) THEN
            abs1 = x3
          ELSE
            abs1 = -x3
          END IF
          k_sensor1 = abs0/abs1
! k_sensor2 = ABS(p(k-2,l) - TWO*p(k-1,l) + p(k,l)) / &
!             ABS(p(k-2,l) + TWO*p(k-1,l) + p(k,l))
          divu2 = (gradu(k, l, 1)+gradv(k, l, 2))*(gradu(k, l, 1)+gradv(&
&           k, l, 2))
          vort2 = (gradv(k, l, 1)-gradu(k, l, 2))*(gradv(k, l, 1)-gradu(&
&           k, l, 2))
          ducros1 = divu2/(divu2+vort2+1d-15)
          dxm1 = half*(one-TANH(2.5d0+10.d0*vol(k, l)/(sq+1d-15)*(gradu(&
&           k, l, 1)+gradv(k, l, 2))))
! divu2     = (gradu(k-1,l,1)+gradv(k-1,l,2)) * (gradu(k-1,l,1)+gradv(k-1,l,2))
! vort2     = (gradv(k-1,l,1)-gradu(k-1,l,2)) * (gradv(k-1,l,1)-gradu(k-1,l,2))
! ducros2   = divu2/(divu2+vort2+1d-15)
! dxm2       = HALF*(ONE-tanh(2.5d0+10.d0*vol(k,l)/(sq+1d-15)*(gradu(k-1,l,1)+gradv(k-1,l,2))) )
! coef      = MAX( k_sensor1*ducros1, &
!                  k_sensor2*ducros2)
! coef      = MAX( k_sensor1*ducros1*dxm1, &
!                  k_sensor2*ducros2*dxm2)
          coef = k_sensor1*ducros1*dxm1
          eps2arra(k, l) = k2*coef
        END DO
      END DO
      IF (eps2arra(i, j-2) .LT. eps2arra(i, j-3)) THEN
        y13 = eps2arra(i, j-3)
        ad_branch4 = 0
      ELSE
        y13 = eps2arra(i, j-2)
        ad_branch4 = 1
      END IF
      IF (eps2arra(i, j+2) .LT. y13) THEN
        y12 = y13
        ad_branch5 = 0
      ELSE
        y12 = eps2arra(i, j+2)
        ad_branch5 = 1
      END IF
      IF (eps2arra(i-3, j) .LT. y12) THEN
        y11 = y12
        ad_branch6 = 0
      ELSE
        y11 = eps2arra(i-3, j)
        ad_branch6 = 1
      END IF
      IF (eps2arra(i-2, j) .LT. y11) THEN
        y10 = y11
        ad_branch7 = 0
      ELSE
        y10 = eps2arra(i-2, j)
        ad_branch7 = 1
      END IF
      IF (eps2arra(i+2, j) .LT. y10) THEN
        y9 = y10
        ad_branch8 = 0
      ELSE
        y9 = eps2arra(i+2, j)
        ad_branch8 = 1
      END IF
      IF (eps2arra(i-1, j-1) .LT. y9) THEN
        y8 = y9
        ad_branch9 = 0
      ELSE
        y8 = eps2arra(i-1, j-1)
        ad_branch9 = 1
      END IF
      IF (eps2arra(i-1, j+1) .LT. y8) THEN
        y7 = y8
        ad_branch10 = 0
      ELSE
        y7 = eps2arra(i-1, j+1)
        ad_branch10 = 1
      END IF
      IF (eps2arra(i+1, j-1) .LT. y7) THEN
        y6 = y7
        ad_branch11 = 0
      ELSE
        y6 = eps2arra(i+1, j-1)
        ad_branch11 = 1
      END IF
      IF (eps2arra(i+1, j+1) .LT. y6) THEN
        y5 = y6
        ad_branch12 = 0
      ELSE
        y5 = eps2arra(i+1, j+1)
        ad_branch12 = 1
      END IF
      IF (eps2arra(i, j+1) .LT. y5) THEN
        y4 = y5
        ad_branch13 = 0
      ELSE
        y4 = eps2arra(i, j+1)
        ad_branch13 = 1
      END IF
      IF (eps2arra(i+1, j) .LT. y4) THEN
        y3 = y4
        ad_branch14 = 0
      ELSE
        y3 = eps2arra(i+1, j)
        ad_branch14 = 1
      END IF
      IF (eps2arra(i, j-1) .LT. y3) THEN
        y2 = y3
        ad_branch15 = 0
      ELSE
        y2 = eps2arra(i, j-1)
        ad_branch15 = 1
      END IF
      IF (eps2arra(i-1, j) .LT. y2) THEN
        y1 = y2
        ad_branch16 = 0
      ELSE
        y1 = eps2arra(i-1, j)
        ad_branch16 = 1
      END IF
      IF (eps2arra(i, j) .LT. y1) THEN
        eps2 = y1
        ad_branch17 = 0
      ELSE
        eps2 = eps2arra(i, j)
        ad_branch17 = 1
      END IF
      IF (zero .LT. k4 - 12.d0*eps2) THEN
        eps4 = k4 - 12.d0*eps2
        ad_branch18 = 0
      ELSE
        ad_branch18 = 1
        eps4 = zero
      END IF
! eps4      = MAX(ZERO,k4 - 3.d0/70.d0 * eps2)
!
      diffro = w(i, j, 1) - w(i, j-1, 1)
      diffrou = w(i, j, 2) - w(i, j-1, 2)
      diffrov = w(i, j, 3) - w(i, j-1, 3)
      diffrow = w(i, j, 4) - w(i, j-1, 4)
      diffroe = w(i, j, 5) - w(i, j-1, 5)
      sc1 = nx(i, j, 1)
      sc2 = ny(i, j, 1)
      sn = SQRT(sc1*sc1 + sc2*sc2)
      invsn = one/sn
      nxloc = sc1*invsn
      nyloc = sc2*invsn
!
!
!
!
      sc1 = nx(i, j, 2)
      sc2 = ny(i, j, 2)
      ad_save12 = sn
      sn = SQRT(sc1*sc1 + sc2*sc2)
      invsn = one/sn
      ad_save13 = nxloc
      nxloc = sc1*invsn
      ad_save14 = nyloc
      nyloc = sc2*invsn
!
!
!
!
      fxroe2b = hnb(i, j, 5, 2)
      dissroe2b = -hnb(i, j, 5, 2)
      fvroe2b = -(nxloc*sn*hnb(i, j, 5, 2))
      gvroe2b = -(nyloc*sn*hnb(i, j, 5, 2))
      hnb(i, j, 5, 2) = 0.0_8
      fxrow2b = hnb(i, j, 4, 2)
      dissrow2b = -hnb(i, j, 4, 2)
      fvrow2b = -(nxloc*sn*hnb(i, j, 4, 2))
      gvrow2b = -(nyloc*sn*hnb(i, j, 4, 2))
      hnb(i, j, 4, 2) = 0.0_8
      fxrov2b = hnb(i, j, 3, 2)
      dissrov2b = -hnb(i, j, 3, 2)
      fvrov2b = -(nxloc*sn*hnb(i, j, 3, 2))
      gvrov2b = -(nyloc*sn*hnb(i, j, 3, 2))
      hnb(i, j, 3, 2) = 0.0_8
      fxrou2b = hnb(i, j, 2, 2)
      dissrou2b = -hnb(i, j, 2, 2)
      fvrou2b = -(nxloc*sn*hnb(i, j, 2, 2))
      gvrou2b = -(nyloc*sn*hnb(i, j, 2, 2))
      hnb(i, j, 2, 2) = 0.0_8
      fxro2b = hnb(i, j, 1, 2)
      dissro2b = -hnb(i, j, 1, 2)
      hnb(i, j, 1, 2) = 0.0_8
      nyloc = ad_save14
      nxloc = ad_save13
      sn = ad_save12
      fxroe1b = hnb(i, j, 5, 1)
      dissroe1b = -hnb(i, j, 5, 1)
      fvroe1b = -(nxloc*sn*hnb(i, j, 5, 1))
      gvroe1b = -(nyloc*sn*hnb(i, j, 5, 1))
      hnb(i, j, 5, 1) = 0.0_8
      fxrow1b = hnb(i, j, 4, 1)
      dissrow1b = -hnb(i, j, 4, 1)
      fvrow1b = -(nxloc*sn*hnb(i, j, 4, 1))
      gvrow1b = -(nyloc*sn*hnb(i, j, 4, 1))
      hnb(i, j, 4, 1) = 0.0_8
      fxrov1b = hnb(i, j, 3, 1)
      dissrov1b = -hnb(i, j, 3, 1)
      fvrov1b = -(nxloc*sn*hnb(i, j, 3, 1))
      gvrov1b = -(nyloc*sn*hnb(i, j, 3, 1))
      hnb(i, j, 3, 1) = 0.0_8
      fxrou1b = hnb(i, j, 2, 1)
      dissrou1b = -hnb(i, j, 2, 1)
      fvrou1b = -(nxloc*sn*hnb(i, j, 2, 1))
      gvrou1b = -(nyloc*sn*hnb(i, j, 2, 1))
      hnb(i, j, 2, 1) = 0.0_8
      fxro1b = hnb(i, j, 1, 1)
      dissro1b = -hnb(i, j, 1, 1)
      hnb(i, j, 1, 1) = 0.0_8
      rspecb = (eps2*diffroe+eps4*predroe2)*dissroe2b + (eps2*diffrow+&
&       eps4*predrow2)*dissrow2b + (eps2*diffrov+eps4*predrov2)*&
&       dissrov2b + (eps2*diffrou+eps4*predrou2)*dissrou2b + (eps2*&
&       diffro+eps4*predro2)*dissro2b
      tempb1 = rspec*dissroe2b
      eps2b = diffroe*tempb1
      diffroeb = eps2*tempb1
      eps4b = predroe2*tempb1
      predroe2b = eps4*tempb1
      tempb1 = rspec*dissrow2b
      eps2b = eps2b + diffrow*tempb1
      diffrowb = eps2*tempb1
      eps4b = eps4b + predrow2*tempb1
      predrow2b = eps4*tempb1
      tempb1 = rspec*dissrov2b
      eps2b = eps2b + diffrov*tempb1
      diffrovb = eps2*tempb1
      eps4b = eps4b + predrov2*tempb1
      predrov2b = eps4*tempb1
      tempb1 = rspec*dissrou2b
      eps2b = eps2b + diffrou*tempb1
      diffroub = eps2*tempb1
      eps4b = eps4b + predrou2*tempb1
      predrou2b = eps4*tempb1
      tempb1 = rspec*dissro2b
      eps2b = eps2b + diffro*tempb1
      diffrob = eps2*tempb1
      eps4b = eps4b + predro2*tempb1
      predro2b = eps4*tempb1
      wb(i, j, 5) = wb(i, j, 5) + diffroeb
      wb(i, j-1, 5) = wb(i, j-1, 5) - diffroeb
      wb(i, j, 4) = wb(i, j, 4) + diffrowb
      wb(i, j-1, 4) = wb(i, j-1, 4) - diffrowb
      wb(i, j, 3) = wb(i, j, 3) + diffrovb
      wb(i, j-1, 3) = wb(i, j-1, 3) - diffrovb
      wb(i, j, 2) = wb(i, j, 2) + diffroub
      wb(i, j-1, 2) = wb(i, j-1, 2) - diffroub
      wb(i, j, 1) = wb(i, j, 1) + diffrob
      wb(i, j-1, 1) = wb(i, j-1, 1) - diffrob
      diffroe = w(i, j, 5) - w(i-1, j, 5)
      tempb1 = rspec*dissroe1b
      eps2b = eps2b + diffroe*tempb1
      diffroeb = eps2*tempb1
      eps4b = eps4b + predroe1*tempb1
      predroe1b = eps4*tempb1
      diffrow = w(i, j, 4) - w(i-1, j, 4)
      tempb1 = rspec*dissrow1b
      eps2b = eps2b + diffrow*tempb1
      diffrowb = eps2*tempb1
      eps4b = eps4b + predrow1*tempb1
      predrow1b = eps4*tempb1
      diffrov = w(i, j, 3) - w(i-1, j, 3)
      tempb1 = rspec*dissrov1b
      eps2b = eps2b + diffrov*tempb1
      diffrovb = eps2*tempb1
      eps4b = eps4b + predrov1*tempb1
      predrov1b = eps4*tempb1
      diffrou = w(i, j, 2) - w(i-1, j, 2)
      tempb1 = rspec*dissrou1b
      eps2b = eps2b + diffrou*tempb1
      diffroub = eps2*tempb1
      eps4b = eps4b + predrou1*tempb1
      predrou1b = eps4*tempb1
      diffro = w(i, j, 1) - w(i-1, j, 1)
      rspecb = rspecb + (eps2*diffroe+eps4*predroe1)*dissroe1b + (eps2*&
&       diffrow+eps4*predrow1)*dissrow1b + (eps2*diffrov+eps4*predrov1)*&
&       dissrov1b + (eps2*diffrou+eps4*predrou1)*dissrou1b + (eps2*&
&       diffro+eps4*predro1)*dissro1b
      tempb1 = rspec*dissro1b
      eps2b = eps2b + diffro*tempb1
      diffrob = eps2*tempb1
      eps4b = eps4b + predro1*tempb1
      predro1b = eps4*tempb1
      wb(i, j, 5) = wb(i, j, 5) + diffroeb
      wb(i-1, j, 5) = wb(i-1, j, 5) - diffroeb
      wb(i, j, 4) = wb(i, j, 4) + diffrowb
      wb(i-1, j, 4) = wb(i-1, j, 4) - diffrowb
      wb(i, j, 3) = wb(i, j, 3) + diffrovb
      wb(i-1, j, 3) = wb(i-1, j, 3) - diffrovb
      wb(i, j, 2) = wb(i, j, 2) + diffroub
      wb(i-1, j, 2) = wb(i-1, j, 2) - diffroub
      wb(i, j, 1) = wb(i, j, 1) + diffrob
      wb(i-1, j, 1) = wb(i-1, j, 1) - diffrob
      IF (ad_branch18 .EQ. 0) eps2b = eps2b - 12.d0*eps4b
      IF (ad_branch17 .EQ. 0) THEN
        y1b = eps2b
      ELSE
        eps2arrab(i, j) = eps2arrab(i, j) + eps2b
        y1b = 0.0_8
      END IF
      IF (ad_branch16 .EQ. 0) THEN
        y2b = y1b
      ELSE
        eps2arrab(i-1, j) = eps2arrab(i-1, j) + y1b
        y2b = 0.0_8
      END IF
      IF (ad_branch15 .EQ. 0) THEN
        y3b = y2b
      ELSE
        eps2arrab(i, j-1) = eps2arrab(i, j-1) + y2b
        y3b = 0.0_8
      END IF
      IF (ad_branch14 .EQ. 0) THEN
        y4b = y3b
      ELSE
        eps2arrab(i+1, j) = eps2arrab(i+1, j) + y3b
        y4b = 0.0_8
      END IF
      IF (ad_branch13 .EQ. 0) THEN
        y5b = y4b
      ELSE
        eps2arrab(i, j+1) = eps2arrab(i, j+1) + y4b
        y5b = 0.0_8
      END IF
      IF (ad_branch12 .EQ. 0) THEN
        y6b = y5b
      ELSE
        eps2arrab(i+1, j+1) = eps2arrab(i+1, j+1) + y5b
        y6b = 0.0_8
      END IF
      IF (ad_branch11 .EQ. 0) THEN
        y7b = y6b
      ELSE
        eps2arrab(i+1, j-1) = eps2arrab(i+1, j-1) + y6b
        y7b = 0.0_8
      END IF
      IF (ad_branch10 .EQ. 0) THEN
        y8b = y7b
      ELSE
        eps2arrab(i-1, j+1) = eps2arrab(i-1, j+1) + y7b
        y8b = 0.0_8
      END IF
      IF (ad_branch9 .EQ. 0) THEN
        y9b = y8b
      ELSE
        eps2arrab(i-1, j-1) = eps2arrab(i-1, j-1) + y8b
        y9b = 0.0_8
      END IF
      IF (ad_branch8 .EQ. 0) THEN
        y10b = y9b
      ELSE
        eps2arrab(i+2, j) = eps2arrab(i+2, j) + y9b
        y10b = 0.0_8
      END IF
      IF (ad_branch7 .EQ. 0) THEN
        y11b = y10b
      ELSE
        eps2arrab(i-2, j) = eps2arrab(i-2, j) + y10b
        y11b = 0.0_8
      END IF
      IF (ad_branch6 .EQ. 0) THEN
        y12b = y11b
      ELSE
        eps2arrab(i-3, j) = eps2arrab(i-3, j) + y11b
        y12b = 0.0_8
      END IF
      IF (ad_branch5 .EQ. 0) THEN
        y13b = y12b
      ELSE
        eps2arrab(i, j+2) = eps2arrab(i, j+2) + y12b
        y13b = 0.0_8
      END IF
      IF (ad_branch4 .EQ. 0) THEN
        eps2arrab(i, j-3) = eps2arrab(i, j-3) + y13b
      ELSE
        eps2arrab(i, j-2) = eps2arrab(i, j-2) + y13b
      END IF
      sqb = 0.0_8
!$BWD-OF II-LOOP 
      DO l=j-gh,j+gh-1
!$BWD-OF II-LOOP 
!DIR$ IVDEP
        DO k=i-gh,i+gh-1
          IF (p(k-1, l) - two*p(k, l) + p(k+1, l) .GE. 0.) THEN
            abs0 = p(k-1, l) - two*p(k, l) + p(k+1, l)
            ad_branch = 1
          ELSE
            abs0 = -(p(k-1, l)-two*p(k, l)+p(k+1, l))
            ad_branch = 0
          END IF
          x3 = p(k-1, l) + two*p(k, l) + p(k+1, l)
          IF (x3 .GE. 0.) THEN
            abs1 = x3
            ad_branch0 = 0
          ELSE
            abs1 = -x3
            ad_branch0 = 1
          END IF
          k_sensor1 = abs0/abs1
! k_sensor2 = ABS(p(k-2,l) - TWO*p(k-1,l) + p(k,l)) / &
!             ABS(p(k-2,l) + TWO*p(k-1,l) + p(k,l))
          divu2 = (gradu(k, l, 1)+gradv(k, l, 2))*(gradu(k, l, 1)+gradv(&
&           k, l, 2))
          vort2 = (gradv(k, l, 1)-gradu(k, l, 2))*(gradv(k, l, 1)-gradu(&
&           k, l, 2))
          ducros1 = divu2/(divu2+vort2+1d-15)
          dxm1 = half*(one-TANH(2.5d0+10.d0*vol(k, l)/(sq+1d-15)*(gradu(&
&           k, l, 1)+gradv(k, l, 2))))
! divu2     = (gradu(k-1,l,1)+gradv(k-1,l,2)) * (gradu(k-1,l,1)+gradv(k-1,l,2))
! vort2     = (gradv(k-1,l,1)-gradu(k-1,l,2)) * (gradv(k-1,l,1)-gradu(k-1,l,2))
! ducros2   = divu2/(divu2+vort2+1d-15)
! dxm2       = HALF*(ONE-tanh(2.5d0+10.d0*vol(k,l)/(sq+1d-15)*(gradu(k-1,l,1)+gradv(k-1,l,2))) )
! coef      = MAX( k_sensor1*ducros1, &
!                  k_sensor2*ducros2)
! coef      = MAX( k_sensor1*ducros1*dxm1, &
!                  k_sensor2*ducros2*dxm2)
          coefb = k2*eps2arrab(k, l)
          eps2arrab(k, l) = 0.0_8
          k_sensor1b = ducros1*dxm1*coefb
          ducros1b = k_sensor1*dxm1*coefb
          dxm1b = k_sensor1*ducros1*coefb
          temp1 = (gradu(k, l, 1)+gradv(k, l, 2))/(sq+1d-15)
          temp0 = 10.d0*vol(k, l)
          tempb1 = -(temp0*(1.0-TANH(temp0*temp1+2.5d0)**2)*half*dxm1b/(&
&           sq+1d-15))
          gradub(k, l, 1) = gradub(k, l, 1) + tempb1
          gradvb(k, l, 2) = gradvb(k, l, 2) + tempb1
          sqb = sqb - temp1*tempb1
          tempb1 = ducros1b/(divu2+vort2+1d-15)
          tempb0 = -(divu2*tempb1/(divu2+vort2+1d-15))
          divu2b = tempb1 + tempb0
          vort2b = tempb0
          tempb1 = 2*(gradv(k, l, 1)-gradu(k, l, 2))*vort2b
          gradvb(k, l, 1) = gradvb(k, l, 1) + tempb1
          gradub(k, l, 2) = gradub(k, l, 2) - tempb1
          tempb1 = 2*(gradu(k, l, 1)+gradv(k, l, 2))*divu2b
          gradub(k, l, 1) = gradub(k, l, 1) + tempb1
          gradvb(k, l, 2) = gradvb(k, l, 2) + tempb1
          abs0b = k_sensor1b/abs1
          abs1b = -(abs0*k_sensor1b/abs1**2)
          IF (ad_branch0 .EQ. 0) THEN
            x3b = abs1b
          ELSE
            x3b = -abs1b
          END IF
          pb(k-1, l) = pb(k-1, l) + x3b
          pb(k, l) = pb(k, l) + two*x3b
          pb(k+1, l) = pb(k+1, l) + x3b
          IF (ad_branch .EQ. 0) THEN
            pb(k, l) = pb(k, l) + two*abs0b
            pb(k-1, l) = pb(k-1, l) - abs0b
            pb(k+1, l) = pb(k+1, l) - abs0b
          ELSE
            pb(k-1, l) = pb(k-1, l) + abs0b
            pb(k, l) = pb(k, l) - two*abs0b
            pb(k+1, l) = pb(k+1, l) + abs0b
          END IF
        END DO
      END DO
      IF (ad_branch3 .EQ. 0) THEN
        sqbisb = sqb
        sqb = 0.0_8
      ELSE
        sqbisb = 0.0_8
      END IF
      sqb = sqb + sqbisb
      IF (ad_branch2 .EQ. 0) THEN
        rspecbisb = rspecb
        rspecb = 0.0_8
      ELSE
        rspecbisb = 0.0_8
      END IF
      rspecb = rspecb + rspecbisb
      abb = rspecb
      sqb = sqb + rspecb
      IF (nx2*c2x .EQ. 0.0) THEN
        c2xb = 0.0_8
      ELSE
        c2xb = nx2*sqb/(2.0*SQRT(nx2*c2x))
      END IF
      IF (ad_branch1 .EQ. 0) THEN
        x2b = abb
      ELSE
        x2b = -abb
      END IF
      ub = nx(i, j, 2)*x2b
      vb = ny(i, j, 2)*x2b
      c2lb = rr*c2xb
      c2rb = omrr*c2xb
      omrrb = c2r*c2xb + vr*vb + ur*ub
      rrb = c2l*c2xb + vl*vb + ul*ub - omrrb
      vlb = rr*vb
      vrb = omrr*vb
      ulb = rr*ub
      urb = omrr*ub
      rb = -(one*rrb/(one+r)**2)
      IF (rhomr/rhoml .EQ. 0.0) THEN
        tempb1 = 0.0_8
      ELSE
        tempb1 = rb/(rhoml*2.0*SQRT(rhomr/rhoml))
      END IF
      rhomrb = tempb1 - w(i, j, 3)*vrb/rhomr**2 - w(i, j, 2)*urb/rhomr**&
&       2
      rhomlb = -(rhomr*tempb1/rhoml) - w(i, j-1, 3)*vlb/rhoml**2 - w(i, &
&       j-1, 2)*ulb/rhoml**2
      tlocb(i, j-1) = tlocb(i, j-1) + gam*rgaz*c2lb
      wb(i, j-1, 3) = wb(i, j-1, 3) + vlb/rhoml
      wb(i, j-1, 2) = wb(i, j-1, 2) + ulb/rhoml
      wb(i, j-1, 1) = wb(i, j-1, 1) + rhomlb
      tlocb(i, j) = tlocb(i, j) + gam*rgaz*c2rb
      wb(i, j, 3) = wb(i, j, 3) + vrb/rhomr
      wb(i, j, 2) = wb(i, j, 2) + urb/rhomr
      wb(i, j, 1) = wb(i, j, 1) + rhomrb
      fvrov2b = fvrov2b + vv*fvroe2b
      lambdab = ty*gvroe2b + tx*fvroe2b
      tyb = lambda*gvroe2b
      uub = gvrou2*gvroe2b + fvrou2*fvroe2b
      gvrou2b = gvrou2b + uu*gvroe2b
      vvb = gvrov2*gvroe2b + fvrov2*fvroe2b
      gvrov2b = gvrov2b + vv*gvroe2b
      wwb = gvrow2*gvroe2b + fvrow2*fvroe2b
      gvrow2b = gvrow2b + ww*gvroe2b
      wyb = mmu*gvrow2b
      tempb1 = twothird*gvrov2b
      mmub = wy*gvrow2b + (two*vy-ux)*tempb1
      vyb = two*mmu*tempb1
      uxb = -(mmu*tempb1)
      uyb = mmu*gvrou2b + mmu*fvrov2b
      vxb = mmu*gvrou2b + mmu*fvrov2b
      txb = lambda*fvroe2b
      fvrou2b = fvrou2b + uu*fvroe2b
      fvrow2b = fvrow2b + ww*fvroe2b
      wxb = mmu*fvrow2b
      tempb1 = twothird*fvrou2b
      mmub = mmub + (uy+vx)*gvrou2b + wx*fvrow2b + (uy+vx)*fvrov2b + (&
&       two*ux-vy)*tempb1 + cpprandtl*lambdab
      uxb = uxb + two*mmu*tempb1
      vyb = vyb - mmu*tempb1
      lambda = ad_save11
      mmu = ad_save10
      tempb1 = 0.0625d0*mmub
      mub(i, j-1) = mub(i, j-1) + 9.d0*tempb1
      mub(i, j-2) = mub(i, j-2) - tempb1
      mub(i, j) = mub(i, j) + 9.d0*tempb1
      mub(i, j+1) = mub(i, j+1) - tempb1
      ww = ad_save9
      tempb1 = 0.0625d0*wwb
      velzb(i, j-1) = velzb(i, j-1) + 9.d0*tempb1
      velzb(i, j-2) = velzb(i, j-2) - tempb1
      velzb(i, j) = velzb(i, j) + 9.d0*tempb1
      velzb(i, j+1) = velzb(i, j+1) - tempb1
      vv = ad_save8
      tempb1 = 0.0625d0*vvb
      velyb(i, j-1) = velyb(i, j-1) + 9.d0*tempb1
      velyb(i, j-2) = velyb(i, j-2) - tempb1
      velyb(i, j) = velyb(i, j) + 9.d0*tempb1
      velyb(i, j+1) = velyb(i, j+1) - tempb1
      uu = ad_save7
      tempb1 = 0.0625d0*uub
      velxb(i, j-1) = velxb(i, j-1) + 9.d0*tempb1
      velxb(i, j-2) = velxb(i, j-2) - tempb1
      velxb(i, j) = velxb(i, j) + 9.d0*tempb1
      velxb(i, j+1) = velxb(i, j+1) - tempb1
      ty = ad_save6
      tempb1 = volm1*tyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      tx = ad_save5
      tempb1 = volm1*txb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = twentyfourth*val_ob
      tlocb(i, j) = tlocb(i, j) + 26.d0*tempb1
      tlocb(i, j+1) = tlocb(i, j+1) - tempb1
      tlocb(i, j-1) = tlocb(i, j-1) - tempb1
      tempb1 = twentyfourth*val_eb
      tlocb(i, j-1) = tlocb(i, j-1) + 26.d0*tempb1
      tlocb(i, j) = tlocb(i, j) - tempb1
      tlocb(i, j-2) = tlocb(i, j-2) - tempb1
      tempb1 = ccross*val_sb
      tlocb(i-2, j-2) = tlocb(i-2, j-2) + tempb1
      tlocb(i-2, j-1) = tlocb(i-2, j-1) - 9.d0*tempb1
      tlocb(i-2, j) = tlocb(i-2, j) - 9.d0*tempb1
      tlocb(i-2, j+1) = tlocb(i-2, j+1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      tlocb(i+1, j-2) = tlocb(i+1, j-2) + tempb1
      tlocb(i+1, j-1) = tlocb(i+1, j-1) - 9.d0*tempb1
      tlocb(i+1, j+1) = tlocb(i+1, j+1) + tempb1
      tlocb(i+1, j) = tlocb(i+1, j) - 9.d0*tempb1
      tempb1 = ccross*val_nb
      tlocb(i-1, j-1) = tlocb(i-1, j-1) + 9.d0*tempb0 - 9.d0*tempb1
      tlocb(i-1, j-2) = tlocb(i-1, j-2) + tempb1 - tempb0
      tlocb(i-1, j) = tlocb(i-1, j) + 9.d0*tempb0 - 9.d0*tempb1
      tlocb(i-1, j+1) = tlocb(i-1, j+1) + tempb1 - tempb0
      tempb0 = 7.d0*tempb1
      tlocb(i, j-1) = tlocb(i, j-1) + 9.d0*tempb + 9.d0*tempb0
      tlocb(i, j-2) = tlocb(i, j-2) - tempb - tempb0
      tlocb(i, j) = tlocb(i, j) + 9.d0*tempb + 9.d0*tempb0
      tlocb(i, j+1) = tlocb(i, j+1) - tempb - tempb0
      tempb = 7.d0*tempb1
      tlocb(i+2, j-2) = tlocb(i+2, j-2) + tempb1
      tlocb(i+2, j-1) = tlocb(i+2, j-1) - 9.d0*tempb1
      tlocb(i+2, j+1) = tlocb(i+2, j+1) + tempb1
      tlocb(i+2, j) = tlocb(i+2, j) - 9.d0*tempb1
      tlocb(i+1, j-1) = tlocb(i+1, j-1) + 9.d0*tempb
      tlocb(i+1, j-2) = tlocb(i+1, j-2) - tempb
      tlocb(i+1, j) = tlocb(i+1, j) + 9.d0*tempb
      tlocb(i+1, j+1) = tlocb(i+1, j+1) - tempb
      wy = ad_save4
      tempb1 = volm1*wyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      wx = ad_save3
      tempb1 = volm1*wxb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = twentyfourth*val_ob
      velzb(i, j) = velzb(i, j) + 26.d0*tempb1
      velzb(i, j+1) = velzb(i, j+1) - tempb1
      velzb(i, j-1) = velzb(i, j-1) - tempb1
      tempb1 = twentyfourth*val_eb
      velzb(i, j-1) = velzb(i, j-1) + 26.d0*tempb1
      velzb(i, j) = velzb(i, j) - tempb1
      velzb(i, j-2) = velzb(i, j-2) - tempb1
      tempb1 = ccross*val_sb
      velzb(i-2, j-2) = velzb(i-2, j-2) + tempb1
      velzb(i-2, j-1) = velzb(i-2, j-1) - 9.d0*tempb1
      velzb(i-2, j) = velzb(i-2, j) - 9.d0*tempb1
      velzb(i-2, j+1) = velzb(i-2, j+1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velzb(i+1, j-2) = velzb(i+1, j-2) + tempb1
      velzb(i+1, j-1) = velzb(i+1, j-1) - 9.d0*tempb1
      velzb(i+1, j+1) = velzb(i+1, j+1) + tempb1
      velzb(i+1, j) = velzb(i+1, j) - 9.d0*tempb1
      tempb1 = ccross*val_nb
      velzb(i-1, j-1) = velzb(i-1, j-1) + 9.d0*tempb0 - 9.d0*tempb1
      velzb(i-1, j-2) = velzb(i-1, j-2) + tempb1 - tempb0
      velzb(i-1, j) = velzb(i-1, j) + 9.d0*tempb0 - 9.d0*tempb1
      velzb(i-1, j+1) = velzb(i-1, j+1) + tempb1 - tempb0
      tempb0 = 7.d0*tempb1
      velzb(i, j-1) = velzb(i, j-1) + 9.d0*tempb + 9.d0*tempb0
      velzb(i, j-2) = velzb(i, j-2) - tempb - tempb0
      velzb(i, j) = velzb(i, j) + 9.d0*tempb + 9.d0*tempb0
      velzb(i, j+1) = velzb(i, j+1) - tempb - tempb0
      tempb = 7.d0*tempb1
      velzb(i+2, j-2) = velzb(i+2, j-2) + tempb1
      velzb(i+2, j-1) = velzb(i+2, j-1) - 9.d0*tempb1
      velzb(i+2, j+1) = velzb(i+2, j+1) + tempb1
      velzb(i+2, j) = velzb(i+2, j) - 9.d0*tempb1
      velzb(i+1, j-1) = velzb(i+1, j-1) + 9.d0*tempb
      velzb(i+1, j-2) = velzb(i+1, j-2) - tempb
      velzb(i+1, j) = velzb(i+1, j) + 9.d0*tempb
      velzb(i+1, j+1) = velzb(i+1, j+1) - tempb
      vy = ad_save2
      tempb1 = volm1*vyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      vx = ad_save1
      tempb1 = volm1*vxb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = twentyfourth*val_ob
      velyb(i, j) = velyb(i, j) + 26.d0*tempb1
      velyb(i, j+1) = velyb(i, j+1) - tempb1
      velyb(i, j-1) = velyb(i, j-1) - tempb1
      tempb1 = twentyfourth*val_eb
      velyb(i, j-1) = velyb(i, j-1) + 26.d0*tempb1
      velyb(i, j) = velyb(i, j) - tempb1
      velyb(i, j-2) = velyb(i, j-2) - tempb1
      tempb1 = ccross*val_sb
      velyb(i-2, j-2) = velyb(i-2, j-2) + tempb1
      velyb(i-2, j-1) = velyb(i-2, j-1) - 9.d0*tempb1
      velyb(i-2, j) = velyb(i-2, j) - 9.d0*tempb1
      velyb(i-2, j+1) = velyb(i-2, j+1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velyb(i+1, j-2) = velyb(i+1, j-2) + tempb1
      velyb(i+1, j-1) = velyb(i+1, j-1) - 9.d0*tempb1
      velyb(i+1, j+1) = velyb(i+1, j+1) + tempb1
      velyb(i+1, j) = velyb(i+1, j) - 9.d0*tempb1
      tempb1 = ccross*val_nb
      velyb(i-1, j-1) = velyb(i-1, j-1) + 9.d0*tempb0 - 9.d0*tempb1
      velyb(i-1, j-2) = velyb(i-1, j-2) + tempb1 - tempb0
      velyb(i-1, j) = velyb(i-1, j) + 9.d0*tempb0 - 9.d0*tempb1
      velyb(i-1, j+1) = velyb(i-1, j+1) + tempb1 - tempb0
      tempb0 = 7.d0*tempb1
      velyb(i, j-1) = velyb(i, j-1) + 9.d0*tempb + 9.d0*tempb0
      velyb(i, j-2) = velyb(i, j-2) - tempb - tempb0
      velyb(i, j) = velyb(i, j) + 9.d0*tempb + 9.d0*tempb0
      velyb(i, j+1) = velyb(i, j+1) - tempb - tempb0
      tempb = 7.d0*tempb1
      velyb(i+2, j-2) = velyb(i+2, j-2) + tempb1
      velyb(i+2, j-1) = velyb(i+2, j-1) - 9.d0*tempb1
      velyb(i+2, j+1) = velyb(i+2, j+1) + tempb1
      velyb(i+2, j) = velyb(i+2, j) - 9.d0*tempb1
      velyb(i+1, j-1) = velyb(i+1, j-1) + 9.d0*tempb
      velyb(i+1, j-2) = velyb(i+1, j-2) - tempb
      velyb(i+1, j) = velyb(i+1, j) + 9.d0*tempb
      velyb(i+1, j+1) = velyb(i+1, j+1) - tempb
      uy = ad_save0
      tempb1 = volm1*uyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      ux = ad_save
      tempb1 = volm1*uxb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = twentyfourth*val_ob
      velxb(i, j) = velxb(i, j) + 26.d0*tempb1
      velxb(i, j+1) = velxb(i, j+1) - tempb1
      velxb(i, j-1) = velxb(i, j-1) - tempb1
      tempb1 = twentyfourth*val_eb
      velxb(i, j-1) = velxb(i, j-1) + 26.d0*tempb1
      velxb(i, j) = velxb(i, j) - tempb1
      velxb(i, j-2) = velxb(i, j-2) - tempb1
      tempb1 = ccross*val_sb
      velxb(i-2, j-2) = velxb(i-2, j-2) + tempb1
      velxb(i-2, j-1) = velxb(i-2, j-1) - 9.d0*tempb1
      velxb(i-2, j) = velxb(i-2, j) - 9.d0*tempb1
      velxb(i-2, j+1) = velxb(i-2, j+1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velxb(i+1, j-2) = velxb(i+1, j-2) + tempb1
      velxb(i+1, j-1) = velxb(i+1, j-1) - 9.d0*tempb1
      velxb(i+1, j+1) = velxb(i+1, j+1) + tempb1
      velxb(i+1, j) = velxb(i+1, j) - 9.d0*tempb1
      velxb(i, j) = velxb(i, j) + 9.d0*tempb
      tempb1 = ccross*val_nb
      velxb(i-1, j-1) = velxb(i-1, j-1) + 9.d0*tempb0 - 9.d0*tempb1
      velxb(i-1, j-2) = velxb(i-1, j-2) + tempb1 - tempb0
      velxb(i-1, j) = velxb(i-1, j) + 9.d0*tempb0 - 9.d0*tempb1
      velxb(i-1, j+1) = velxb(i-1, j+1) + tempb1 - tempb0
      tempb0 = 7.d0*tempb1
      velxb(i, j-1) = velxb(i, j-1) + 9.d0*tempb + 9.d0*tempb0
      velxb(i, j-2) = velxb(i, j-2) - tempb - tempb0
      velxb(i, j+1) = velxb(i, j+1) - tempb - tempb0
      tempb = 7.d0*tempb1
      velxb(i+2, j-2) = velxb(i+2, j-2) + tempb1
      velxb(i+2, j-1) = velxb(i+2, j-1) - 9.d0*tempb1
      velxb(i+2, j+1) = velxb(i+2, j+1) + tempb1
      velxb(i+2, j) = velxb(i+2, j) - 9.d0*tempb1
      velxb(i+1, j-1) = velxb(i+1, j-1) + 9.d0*tempb
      velxb(i+1, j-2) = velxb(i+1, j-2) - tempb
      velxb(i+1, j+1) = velxb(i+1, j+1) - tempb
      lambdab = ty*gvroe1b + tx*fvroe1b
      tyb = lambda*gvroe1b
      uub = gvrou1*gvroe1b + fvrou1*fvroe1b
      gvrou1b = gvrou1b + uu*gvroe1b
      vvb = gvrov1*gvroe1b + fvrov1*fvroe1b
      gvrov1b = gvrov1b + vv*gvroe1b
      wwb = gvrow1*gvroe1b + fvrow1*fvroe1b
      gvrow1b = gvrow1b + ww*gvroe1b
      wyb = mmu*gvrow1b
      tempb1 = twothird*gvrov1b
      mmub = wy*gvrow1b + (two*vy-ux)*tempb1
      vyb = two*mmu*tempb1
      uxb = -(mmu*tempb1)
      txb = lambda*fvroe1b
      fvrou1b = fvrou1b + uu*fvroe1b
      fvrov1b = fvrov1b + vv*fvroe1b
      uyb = mmu*gvrou1b + mmu*fvrov1b
      vxb = mmu*gvrou1b + mmu*fvrov1b
      fvrow1b = fvrow1b + ww*fvroe1b
      wxb = mmu*fvrow1b
      tempb1 = twothird*fvrou1b
      mmub = mmub + (uy+vx)*gvrou1b + wx*fvrow1b + (uy+vx)*fvrov1b + (&
&       two*ux-vy)*tempb1 + cpprandtl*lambdab
      uxb = uxb + two*mmu*tempb1
      vyb = vyb - mmu*tempb1
      tempb1 = 0.0625d0*mmub
      mub(i-1, j) = mub(i-1, j) + 9.d0*tempb1
      mub(i-2, j) = mub(i-2, j) - tempb1
      mub(i, j) = mub(i, j) + 9.d0*tempb1
      mub(i+1, j) = mub(i+1, j) - tempb1
      tempb1 = 0.0625d0*wwb
      velzb(i-1, j) = velzb(i-1, j) + 9.d0*tempb1
      velzb(i-2, j) = velzb(i-2, j) - tempb1
      velzb(i, j) = velzb(i, j) + 9.d0*tempb1
      velzb(i+1, j) = velzb(i+1, j) - tempb1
      tempb1 = 0.0625d0*vvb
      velyb(i-1, j) = velyb(i-1, j) + 9.d0*tempb1
      velyb(i-2, j) = velyb(i-2, j) - tempb1
      velyb(i, j) = velyb(i, j) + 9.d0*tempb1
      velyb(i+1, j) = velyb(i+1, j) - tempb1
      tempb1 = 0.0625d0*uub
      velxb(i+1, j) = velxb(i+1, j) + 9.d0*tempb - tempb1
      velxb(i, j) = velxb(i, j) + 9.d0*tempb0 + 9.d0*tempb1
      velxb(i-1, j) = velxb(i-1, j) + 9.d0*tempb1
      velxb(i-2, j) = velxb(i-2, j) - tempb1
      ny_e = -(half*(ny(i-1, j, 2)+ny(i, j, 2)))
      ny_n = half*(ny(i+1, j, 1)+ny(i, j, 1))
      ny_o = half*(ny(i-1, j+1, 2)+ny(i, j+1, 2))
      ny_s = -(half*(ny(i-1, j, 1)+ny(i, j, 1)))
      volm1 = volf(i, j, 1)
      tempb1 = volm1*tyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      nx_e = -(half*(nx(i-1, j, 2)+nx(i, j, 2)))
      nx_n = half*(nx(i+1, j, 1)+nx(i, j, 1))
      nx_o = half*(nx(i-1, j+1, 2)+nx(i, j+1, 2))
      nx_s = -(half*(nx(i-1, j, 1)+nx(i, j, 1)))
      tempb1 = volm1*txb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = ccross*val_ob
      tlocb(i-2, j-1) = tlocb(i-2, j-1) + tempb1
      tlocb(i-1, j-1) = tlocb(i-1, j-1) - 9.d0*tempb1
      tlocb(i, j-1) = tlocb(i, j-1) - 9.d0*tempb1
      tlocb(i+1, j-1) = tlocb(i+1, j-1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      tlocb(i-2, j+2) = tlocb(i-2, j+2) + tempb1
      tlocb(i-1, j+2) = tlocb(i-1, j+2) - 9.d0*tempb1
      tlocb(i+1, j+2) = tlocb(i+1, j+2) + tempb1
      tlocb(i, j+2) = tlocb(i, j+2) - 9.d0*tempb1
      tlocb(i-1, j) = tlocb(i-1, j) + 9.d0*tempb0
      tlocb(i-2, j) = tlocb(i-2, j) - tempb0
      tlocb(i, j) = tlocb(i, j) + 9.d0*tempb0
      tlocb(i+1, j) = tlocb(i+1, j) - tempb0
      tempb1 = ccross*val_eb
      tlocb(i-1, j+1) = tlocb(i-1, j+1) + 9.d0*tempb - 9.d0*tempb1
      tlocb(i-2, j+1) = tlocb(i-2, j+1) + tempb1 - tempb
      tlocb(i, j+1) = tlocb(i, j+1) + 9.d0*tempb - 9.d0*tempb1
      tlocb(i+1, j+1) = tlocb(i+1, j+1) + tempb1 - tempb
      tlocb(i-2, j-2) = tlocb(i-2, j-2) + tempb1
      tlocb(i-1, j-2) = tlocb(i-1, j-2) - 9.d0*tempb1
      tlocb(i, j-2) = tlocb(i, j-2) - 9.d0*tempb1
      tlocb(i+1, j-2) = tlocb(i+1, j-2) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      tlocb(i-1, j-1) = tlocb(i-1, j-1) + 9.d0*tempb0
      tlocb(i-2, j-1) = tlocb(i-2, j-1) - tempb0
      tlocb(i, j-1) = tlocb(i, j-1) + 9.d0*tempb0
      tlocb(i+1, j-1) = tlocb(i+1, j-1) - tempb0
      tempb1 = twentyfourth*val_sb
      tlocb(i-1, j) = tlocb(i-1, j) + 9.d0*tempb + 26.d0*tempb1
      tlocb(i-2, j) = tlocb(i-2, j) - tempb - tempb1
      tlocb(i, j) = tlocb(i, j) + 9.d0*tempb - tempb1
      tempb1 = twentyfourth*val_nb
      tlocb(i+1, j) = tlocb(i+1, j) - tempb - tempb1
      tlocb(i, j) = tlocb(i, j) + 26.d0*tempb1
      tlocb(i-1, j) = tlocb(i-1, j) - tempb1
      tempb1 = volm1*wyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      tempb1 = volm1*wxb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = ccross*val_ob
      velzb(i-2, j-1) = velzb(i-2, j-1) + tempb1
      velzb(i-1, j-1) = velzb(i-1, j-1) - 9.d0*tempb1
      velzb(i, j-1) = velzb(i, j-1) - 9.d0*tempb1
      velzb(i+1, j-1) = velzb(i+1, j-1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velzb(i-2, j+2) = velzb(i-2, j+2) + tempb1
      velzb(i-1, j+2) = velzb(i-1, j+2) - 9.d0*tempb1
      velzb(i+1, j+2) = velzb(i+1, j+2) + tempb1
      velzb(i, j+2) = velzb(i, j+2) - 9.d0*tempb1
      velzb(i-1, j) = velzb(i-1, j) + 9.d0*tempb0
      velzb(i-2, j) = velzb(i-2, j) - tempb0
      velzb(i, j) = velzb(i, j) + 9.d0*tempb0
      velzb(i+1, j) = velzb(i+1, j) - tempb0
      tempb1 = ccross*val_eb
      velzb(i-1, j+1) = velzb(i-1, j+1) + 9.d0*tempb - 9.d0*tempb1
      velzb(i-2, j+1) = velzb(i-2, j+1) + tempb1 - tempb
      velzb(i, j+1) = velzb(i, j+1) + 9.d0*tempb - 9.d0*tempb1
      velzb(i+1, j+1) = velzb(i+1, j+1) + tempb1 - tempb
      velzb(i-2, j-2) = velzb(i-2, j-2) + tempb1
      velzb(i-1, j-2) = velzb(i-1, j-2) - 9.d0*tempb1
      velzb(i, j-2) = velzb(i, j-2) - 9.d0*tempb1
      velzb(i+1, j-2) = velzb(i+1, j-2) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velzb(i-1, j-1) = velzb(i-1, j-1) + 9.d0*tempb0
      velzb(i-2, j-1) = velzb(i-2, j-1) - tempb0
      velzb(i, j-1) = velzb(i, j-1) + 9.d0*tempb0
      velzb(i+1, j-1) = velzb(i+1, j-1) - tempb0
      tempb1 = twentyfourth*val_sb
      velzb(i-1, j) = velzb(i-1, j) + 9.d0*tempb + 26.d0*tempb1
      velzb(i-2, j) = velzb(i-2, j) - tempb - tempb1
      velzb(i, j) = velzb(i, j) + 9.d0*tempb - tempb1
      tempb1 = twentyfourth*val_nb
      velzb(i+1, j) = velzb(i+1, j) - tempb - tempb1
      velzb(i, j) = velzb(i, j) + 26.d0*tempb1
      velzb(i-1, j) = velzb(i-1, j) - tempb1
      tempb1 = volm1*vyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      tempb1 = volm1*vxb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = ccross*val_ob
      velyb(i-2, j-1) = velyb(i-2, j-1) + tempb1
      velyb(i-1, j-1) = velyb(i-1, j-1) - 9.d0*tempb1
      velyb(i, j-1) = velyb(i, j-1) - 9.d0*tempb1
      velyb(i+1, j-1) = velyb(i+1, j-1) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velyb(i-2, j+2) = velyb(i-2, j+2) + tempb1
      velyb(i-1, j+2) = velyb(i-1, j+2) - 9.d0*tempb1
      velyb(i+1, j+2) = velyb(i+1, j+2) + tempb1
      velyb(i, j+2) = velyb(i, j+2) - 9.d0*tempb1
      velyb(i-1, j) = velyb(i-1, j) + 9.d0*tempb0
      velyb(i-2, j) = velyb(i-2, j) - tempb0
      velyb(i, j) = velyb(i, j) + 9.d0*tempb0
      velyb(i+1, j) = velyb(i+1, j) - tempb0
      tempb1 = ccross*val_eb
      velyb(i-1, j+1) = velyb(i-1, j+1) + 9.d0*tempb - 9.d0*tempb1
      velyb(i-2, j+1) = velyb(i-2, j+1) + tempb1 - tempb
      velyb(i, j+1) = velyb(i, j+1) + 9.d0*tempb - 9.d0*tempb1
      velyb(i+1, j+1) = velyb(i+1, j+1) + tempb1 - tempb
      velyb(i-2, j-2) = velyb(i-2, j-2) + tempb1
      velyb(i-1, j-2) = velyb(i-1, j-2) - 9.d0*tempb1
      velyb(i, j-2) = velyb(i, j-2) - 9.d0*tempb1
      velyb(i+1, j-2) = velyb(i+1, j-2) + tempb1
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velyb(i-1, j-1) = velyb(i-1, j-1) + 9.d0*tempb0
      velyb(i-2, j-1) = velyb(i-2, j-1) - tempb0
      velyb(i, j-1) = velyb(i, j-1) + 9.d0*tempb0
      velyb(i+1, j-1) = velyb(i+1, j-1) - tempb0
      tempb1 = twentyfourth*val_sb
      velyb(i-1, j) = velyb(i-1, j) + 9.d0*tempb + 26.d0*tempb1
      velyb(i-2, j) = velyb(i-2, j) - tempb - tempb1
      velyb(i, j) = velyb(i, j) + 9.d0*tempb - tempb1
      tempb1 = twentyfourth*val_nb
      velyb(i+1, j) = velyb(i+1, j) - tempb - tempb1
      velyb(i, j) = velyb(i, j) + 26.d0*tempb1
      velyb(i-1, j) = velyb(i-1, j) - tempb1
      tempb1 = volm1*uyb
      val_nb = ny_n*tempb1
      val_sb = ny_s*tempb1
      val_ob = ny_o*tempb1
      val_eb = ny_e*tempb1
      tempb1 = volm1*uxb
      val_nb = val_nb + nx_n*tempb1
      val_sb = val_sb + nx_s*tempb1
      val_ob = val_ob + nx_o*tempb1
      val_eb = val_eb + nx_e*tempb1
      tempb1 = ccross*val_ob
      tempb0 = 7.d0*tempb1
      tempb = 7.d0*tempb1
      velxb(i-2, j+2) = velxb(i-2, j+2) + tempb1
      velxb(i-1, j+2) = velxb(i-1, j+2) - 9.d0*tempb1
      velxb(i+1, j+2) = velxb(i+1, j+2) + tempb1
      velxb(i, j+2) = velxb(i, j+2) - 9.d0*tempb1
      velxb(i-1, j) = velxb(i-1, j) + 9.d0*tempb0
      velxb(i-2, j) = velxb(i-2, j) - tempb0
      velxb(i, j) = velxb(i, j) + 9.d0*tempb0
      velxb(i+1, j) = velxb(i+1, j) - tempb0
      tempb0 = ccross*val_eb
      velxb(i-1, j+1) = velxb(i-1, j+1) + 9.d0*tempb - 9.d0*tempb0
      velxb(i-2, j+1) = velxb(i-2, j+1) + tempb0 - tempb
      velxb(i, j+1) = velxb(i, j+1) + 9.d0*tempb - 9.d0*tempb0
      velxb(i+1, j+1) = velxb(i+1, j+1) + tempb0 - tempb
      velxb(i-2, j-2) = velxb(i-2, j-2) + tempb0
      velxb(i-1, j-2) = velxb(i-1, j-2) - 9.d0*tempb0
      velxb(i, j-2) = velxb(i, j-2) - 9.d0*tempb0
      velxb(i+1, j-2) = velxb(i+1, j-2) + tempb0
      tempb = 7.d0*tempb0
      velxb(i-2, j-1) = velxb(i-2, j-1) + tempb1 - tempb
      velxb(i-1, j-1) = velxb(i-1, j-1) + 9.d0*tempb - 9.d0*tempb1
      velxb(i, j-1) = velxb(i, j-1) + 9.d0*tempb - 9.d0*tempb1
      velxb(i+1, j-1) = velxb(i+1, j-1) + tempb1 - tempb
      tempb1 = 7.d0*tempb0
      tempb0 = twentyfourth*val_sb
      velxb(i-1, j) = velxb(i-1, j) + 9.d0*tempb1 + 26.d0*tempb0
      velxb(i-2, j) = velxb(i-2, j) - tempb1 - tempb0
      velxb(i, j) = velxb(i, j) + 9.d0*tempb1 - tempb0
      tempb0 = twentyfourth*val_nb
      velxb(i+1, j) = velxb(i+1, j) - tempb1 - tempb0
      velxb(i, j) = velxb(i, j) + 26.d0*tempb0
      velxb(i-1, j) = velxb(i-1, j) - tempb0
      wb(i, j-2, 5) = wb(i, j-2, 5) + d2*predroe2b
      wb(i, j-3, 5) = wb(i, j-3, 5) - d3*predroe2b
      wb(i, j-1, 5) = wb(i, j-1, 5) - d1*predroe2b
      wb(i, j, 5) = wb(i, j, 5) + d1*predroe2b + d1*predroe1b
      wb(i, j+1, 5) = wb(i, j+1, 5) - d2*predroe2b
      wb(i, j+2, 5) = wb(i, j+2, 5) + d3*predroe2b
      wb(i, j-2, 4) = wb(i, j-2, 4) + d2*predrow2b
      wb(i, j-3, 4) = wb(i, j-3, 4) - d3*predrow2b
      wb(i, j-1, 4) = wb(i, j-1, 4) - d1*predrow2b
      wb(i, j, 4) = wb(i, j, 4) + d1*predrow2b + d1*predrow1b
      wb(i, j+1, 4) = wb(i, j+1, 4) - d2*predrow2b
      wb(i, j+2, 4) = wb(i, j+2, 4) + d3*predrow2b
      wb(i, j-2, 3) = wb(i, j-2, 3) + d2*predrov2b
      wb(i, j-3, 3) = wb(i, j-3, 3) - d3*predrov2b
      wb(i, j-1, 3) = wb(i, j-1, 3) - d1*predrov2b
      wb(i, j, 3) = wb(i, j, 3) + d1*predrov2b + d1*predrov1b
      wb(i, j+1, 3) = wb(i, j+1, 3) - d2*predrov2b
      wb(i, j+2, 3) = wb(i, j+2, 3) + d3*predrov2b
      wb(i, j-2, 2) = wb(i, j-2, 2) + d2*predrou2b
      wb(i, j-3, 2) = wb(i, j-3, 2) - d3*predrou2b
      wb(i, j-1, 2) = wb(i, j-1, 2) - d1*predrou2b
      wb(i, j, 2) = wb(i, j, 2) + d1*predrou2b + d1*predrou1b
      wb(i, j+1, 2) = wb(i, j+1, 2) - d2*predrou2b
      wb(i, j+2, 2) = wb(i, j+2, 2) + d3*predrou2b
      wb(i, j-2, 1) = wb(i, j-2, 1) + d2*predro2b
      wb(i, j-3, 1) = wb(i, j-3, 1) - d3*predro2b
      wb(i, j-1, 1) = wb(i, j-1, 1) - d1*predro2b
      wb(i, j, 1) = wb(i, j, 1) + d1*predro2b + d1*predro1b
      wb(i, j+1, 1) = wb(i, j+1, 1) - d2*predro2b
      wb(i, j+2, 1) = wb(i, j+2, 1) + d3*predro2b
      wb(i-2, j, 5) = wb(i-2, j, 5) + d2*predroe1b
      wb(i-3, j, 5) = wb(i-3, j, 5) - d3*predroe1b
      wb(i-1, j, 5) = wb(i-1, j, 5) - d1*predroe1b
      wb(i+1, j, 5) = wb(i+1, j, 5) - d2*predroe1b
      wb(i+2, j, 5) = wb(i+2, j, 5) + d3*predroe1b
      wb(i-2, j, 4) = wb(i-2, j, 4) + d2*predrow1b
      wb(i-3, j, 4) = wb(i-3, j, 4) - d3*predrow1b
      wb(i-1, j, 4) = wb(i-1, j, 4) - d1*predrow1b
      wb(i+1, j, 4) = wb(i+1, j, 4) - d2*predrow1b
      wb(i+2, j, 4) = wb(i+2, j, 4) + d3*predrow1b
      wb(i-2, j, 3) = wb(i-2, j, 3) + d2*predrov1b
      wb(i-3, j, 3) = wb(i-3, j, 3) - d3*predrov1b
      wb(i-1, j, 3) = wb(i-1, j, 3) - d1*predrov1b
      wb(i+1, j, 3) = wb(i+1, j, 3) - d2*predrov1b
      wb(i+2, j, 3) = wb(i+2, j, 3) + d3*predrov1b
      wb(i-2, j, 2) = wb(i-2, j, 2) + d2*predrou1b
      wb(i-3, j, 2) = wb(i-3, j, 2) - d3*predrou1b
      wb(i-1, j, 2) = wb(i-1, j, 2) - d1*predrou1b
      wb(i+1, j, 2) = wb(i+1, j, 2) - d2*predrou1b
      wb(i+2, j, 2) = wb(i+2, j, 2) + d3*predrou1b
      wb(i-2, j, 1) = wb(i-2, j, 1) + d2*predro1b
      wb(i-3, j, 1) = wb(i-3, j, 1) - d3*predro1b
      wb(i-1, j, 1) = wb(i-1, j, 1) - d1*predro1b
      wb(i+1, j, 1) = wb(i+1, j, 1) - d2*predro1b
      wb(i+2, j, 1) = wb(i+2, j, 1) + d3*predro1b
      tempb0 = nx(i, j, 2)*fxroe2b
      tempb = ny(i, j, 2)*fxroe2b
      gb(i, j, 5) = gb(i, j, 5) + c1*tempb
      gb(i, j-1, 5) = gb(i, j-1, 5) + c1*tempb
      gb(i, j+1, 5) = gb(i, j+1, 5) + c2*tempb
      gb(i, j-2, 5) = gb(i, j-2, 5) + c2*tempb
      gb(i, j+2, 5) = gb(i, j+2, 5) + c3*tempb
      gb(i, j-3, 5) = gb(i, j-3, 5) + c3*tempb
      fb(i, j, 5) = fb(i, j, 5) + c1*tempb0
      fb(i, j-1, 5) = fb(i, j-1, 5) + c1*tempb0
      fb(i, j+1, 5) = fb(i, j+1, 5) + c2*tempb0
      fb(i, j-2, 5) = fb(i, j-2, 5) + c2*tempb0
      fb(i, j+2, 5) = fb(i, j+2, 5) + c3*tempb0
      fb(i, j-3, 5) = fb(i, j-3, 5) + c3*tempb0
      tempb0 = nx(i, j, 2)*fxrow2b
      tempb = ny(i, j, 2)*fxrow2b
      gb(i, j, 4) = gb(i, j, 4) + c1*tempb
      gb(i, j-1, 4) = gb(i, j-1, 4) + c1*tempb
      gb(i, j+1, 4) = gb(i, j+1, 4) + c2*tempb
      gb(i, j-2, 4) = gb(i, j-2, 4) + c2*tempb
      gb(i, j+2, 4) = gb(i, j+2, 4) + c3*tempb
      gb(i, j-3, 4) = gb(i, j-3, 4) + c3*tempb
      fb(i, j, 4) = fb(i, j, 4) + c1*tempb0
      fb(i, j-1, 4) = fb(i, j-1, 4) + c1*tempb0
      fb(i, j+1, 4) = fb(i, j+1, 4) + c2*tempb0
      fb(i, j-2, 4) = fb(i, j-2, 4) + c2*tempb0
      fb(i, j+2, 4) = fb(i, j+2, 4) + c3*tempb0
      fb(i, j-3, 4) = fb(i, j-3, 4) + c3*tempb0
      tempb0 = nx(i, j, 2)*fxrov2b
      tempb = ny(i, j, 2)*fxrov2b
      gb(i, j, 3) = gb(i, j, 3) + c1*tempb
      gb(i, j-1, 3) = gb(i, j-1, 3) + c1*tempb
      gb(i, j+1, 3) = gb(i, j+1, 3) + c2*tempb
      gb(i, j-2, 3) = gb(i, j-2, 3) + c2*tempb
      gb(i, j+2, 3) = gb(i, j+2, 3) + c3*tempb
      gb(i, j-3, 3) = gb(i, j-3, 3) + c3*tempb
      fb(i, j, 3) = fb(i, j, 3) + c1*tempb0
      fb(i, j-1, 3) = fb(i, j-1, 3) + c1*tempb0
      fb(i, j+1, 3) = fb(i, j+1, 3) + c2*tempb0
      fb(i, j-2, 3) = fb(i, j-2, 3) + c2*tempb0
      fb(i, j+2, 3) = fb(i, j+2, 3) + c3*tempb0
      fb(i, j-3, 3) = fb(i, j-3, 3) + c3*tempb0
      tempb0 = nx(i, j, 2)*fxrou2b
      tempb = ny(i, j, 2)*fxrou2b
      gb(i, j, 2) = gb(i, j, 2) + c1*tempb
      gb(i, j-1, 2) = gb(i, j-1, 2) + c1*tempb
      gb(i, j+1, 2) = gb(i, j+1, 2) + c2*tempb
      gb(i, j-2, 2) = gb(i, j-2, 2) + c2*tempb
      gb(i, j+2, 2) = gb(i, j+2, 2) + c3*tempb
      gb(i, j-3, 2) = gb(i, j-3, 2) + c3*tempb
      fb(i, j, 2) = fb(i, j, 2) + c1*tempb0
      fb(i, j-1, 2) = fb(i, j-1, 2) + c1*tempb0
      fb(i, j+1, 2) = fb(i, j+1, 2) + c2*tempb0
      fb(i, j-2, 2) = fb(i, j-2, 2) + c2*tempb0
      fb(i, j+2, 2) = fb(i, j+2, 2) + c3*tempb0
      fb(i, j-3, 2) = fb(i, j-3, 2) + c3*tempb0
      tempb0 = nx(i, j, 2)*fxro2b
      tempb = ny(i, j, 2)*fxro2b
      gb(i, j, 1) = gb(i, j, 1) + c1*tempb
      gb(i, j-1, 1) = gb(i, j-1, 1) + c1*tempb
      gb(i, j+1, 1) = gb(i, j+1, 1) + c2*tempb
      gb(i, j-2, 1) = gb(i, j-2, 1) + c2*tempb
      gb(i, j+2, 1) = gb(i, j+2, 1) + c3*tempb
      gb(i, j-3, 1) = gb(i, j-3, 1) + c3*tempb
      fb(i, j, 1) = fb(i, j, 1) + c1*tempb0
      fb(i, j-1, 1) = fb(i, j-1, 1) + c1*tempb0
      fb(i, j+1, 1) = fb(i, j+1, 1) + c2*tempb0
      fb(i, j-2, 1) = fb(i, j-2, 1) + c2*tempb0
      fb(i, j+2, 1) = fb(i, j+2, 1) + c3*tempb0
      fb(i, j-3, 1) = fb(i, j-3, 1) + c3*tempb0
      tempb0 = nx(i, j, 1)*fxroe1b
      tempb = ny(i, j, 1)*fxroe1b
      gb(i, j, 5) = gb(i, j, 5) + c1*tempb
      gb(i-1, j, 5) = gb(i-1, j, 5) + c1*tempb
      gb(i+1, j, 5) = gb(i+1, j, 5) + c2*tempb
      gb(i-2, j, 5) = gb(i-2, j, 5) + c2*tempb
      gb(i+2, j, 5) = gb(i+2, j, 5) + c3*tempb
      gb(i-3, j, 5) = gb(i-3, j, 5) + c3*tempb
      fb(i, j, 5) = fb(i, j, 5) + c1*tempb0
      fb(i-1, j, 5) = fb(i-1, j, 5) + c1*tempb0
      fb(i+1, j, 5) = fb(i+1, j, 5) + c2*tempb0
      fb(i-2, j, 5) = fb(i-2, j, 5) + c2*tempb0
      fb(i+2, j, 5) = fb(i+2, j, 5) + c3*tempb0
      fb(i-3, j, 5) = fb(i-3, j, 5) + c3*tempb0
      tempb0 = nx(i, j, 1)*fxrow1b
      tempb = ny(i, j, 1)*fxrow1b
      gb(i, j, 4) = gb(i, j, 4) + c1*tempb
      gb(i-1, j, 4) = gb(i-1, j, 4) + c1*tempb
      gb(i+1, j, 4) = gb(i+1, j, 4) + c2*tempb
      gb(i-2, j, 4) = gb(i-2, j, 4) + c2*tempb
      gb(i+2, j, 4) = gb(i+2, j, 4) + c3*tempb
      gb(i-3, j, 4) = gb(i-3, j, 4) + c3*tempb
      fb(i, j, 4) = fb(i, j, 4) + c1*tempb0
      fb(i-1, j, 4) = fb(i-1, j, 4) + c1*tempb0
      fb(i+1, j, 4) = fb(i+1, j, 4) + c2*tempb0
      fb(i-2, j, 4) = fb(i-2, j, 4) + c2*tempb0
      fb(i+2, j, 4) = fb(i+2, j, 4) + c3*tempb0
      fb(i-3, j, 4) = fb(i-3, j, 4) + c3*tempb0
      tempb0 = nx(i, j, 1)*fxrov1b
      tempb = ny(i, j, 1)*fxrov1b
      gb(i, j, 3) = gb(i, j, 3) + c1*tempb
      gb(i-1, j, 3) = gb(i-1, j, 3) + c1*tempb
      gb(i+1, j, 3) = gb(i+1, j, 3) + c2*tempb
      gb(i-2, j, 3) = gb(i-2, j, 3) + c2*tempb
      gb(i+2, j, 3) = gb(i+2, j, 3) + c3*tempb
      gb(i-3, j, 3) = gb(i-3, j, 3) + c3*tempb
      fb(i, j, 3) = fb(i, j, 3) + c1*tempb0
      fb(i-1, j, 3) = fb(i-1, j, 3) + c1*tempb0
      fb(i+1, j, 3) = fb(i+1, j, 3) + c2*tempb0
      fb(i-2, j, 3) = fb(i-2, j, 3) + c2*tempb0
      fb(i+2, j, 3) = fb(i+2, j, 3) + c3*tempb0
      fb(i-3, j, 3) = fb(i-3, j, 3) + c3*tempb0
      tempb0 = nx(i, j, 1)*fxrou1b
      tempb = ny(i, j, 1)*fxrou1b
      gb(i, j, 2) = gb(i, j, 2) + c1*tempb
      gb(i-1, j, 2) = gb(i-1, j, 2) + c1*tempb
      gb(i+1, j, 2) = gb(i+1, j, 2) + c2*tempb
      gb(i-2, j, 2) = gb(i-2, j, 2) + c2*tempb
      gb(i+2, j, 2) = gb(i+2, j, 2) + c3*tempb
      gb(i-3, j, 2) = gb(i-3, j, 2) + c3*tempb
      fb(i, j, 2) = fb(i, j, 2) + c1*tempb0
      fb(i-1, j, 2) = fb(i-1, j, 2) + c1*tempb0
      fb(i+1, j, 2) = fb(i+1, j, 2) + c2*tempb0
      fb(i-2, j, 2) = fb(i-2, j, 2) + c2*tempb0
      fb(i+2, j, 2) = fb(i+2, j, 2) + c3*tempb0
      fb(i-3, j, 2) = fb(i-3, j, 2) + c3*tempb0
      tempb0 = nx(i, j, 1)*fxro1b
      tempb = ny(i, j, 1)*fxro1b
      gb(i, j, 1) = gb(i, j, 1) + c1*tempb
      gb(i-1, j, 1) = gb(i-1, j, 1) + c1*tempb
      gb(i+1, j, 1) = gb(i+1, j, 1) + c2*tempb
      gb(i-2, j, 1) = gb(i-2, j, 1) + c2*tempb
      gb(i+2, j, 1) = gb(i+2, j, 1) + c3*tempb
      gb(i-3, j, 1) = gb(i-3, j, 1) + c3*tempb
      fb(i, j, 1) = fb(i, j, 1) + c1*tempb0
      fb(i-1, j, 1) = fb(i-1, j, 1) + c1*tempb0
      fb(i+1, j, 1) = fb(i+1, j, 1) + c2*tempb0
      fb(i-2, j, 1) = fb(i-2, j, 1) + c2*tempb0
      fb(i+2, j, 1) = fb(i+2, j, 1) + c3*tempb0
      fb(i-3, j, 1) = fb(i-3, j, 1) + c3*tempb0
    END DO
  END DO
  DO i=2,1,-1
    DO h=gh,1,-1
      gradvb(im-1+h, :, :) = gradvb(im-1+h, :, :) + two*gradvb(im+h, :, &
&       :)
      gradvb(im-2+h, :, :) = gradvb(im-2+h, :, :) - gradvb(im+h, :, :)
      gradvb(im+h, :, :) = 0.0_8
      gradub(im-1+h, :, :) = gradub(im-1+h, :, :) + two*gradub(im+h, :, &
&       :)
      gradub(im-2+h, :, :) = gradub(im-2+h, :, :) - gradub(im+h, :, :)
      gradub(im+h, :, :) = 0.0_8
      gradvb(2-h, :, :) = gradvb(2-h, :, :) + two*gradvb(1-h, :, :)
      gradvb(3-h, :, :) = gradvb(3-h, :, :) - gradvb(1-h, :, :)
      gradvb(1-h, :, :) = 0.0_8
      gradub(2-h, :, :) = gradub(2-h, :, :) + two*gradub(1-h, :, :)
      gradub(3-h, :, :) = gradub(3-h, :, :) - gradub(1-h, :, :)
      gradub(1-h, :, :) = 0.0_8
      gradvb(:, jm-1+h, :) = gradvb(:, jm-1+h, :) + two*gradvb(:, jm+h, &
&       :)
      gradvb(:, jm-2+h, :) = gradvb(:, jm-2+h, :) - gradvb(:, jm+h, :)
      gradvb(:, jm+h, :) = 0.0_8
      gradub(:, jm-1+h, :) = gradub(:, jm-1+h, :) + two*gradub(:, jm+h, &
&       :)
      gradub(:, jm-2+h, :) = gradub(:, jm-2+h, :) - gradub(:, jm+h, :)
      gradub(:, jm+h, :) = 0.0_8
      gradvb(:, 2-h, :) = gradvb(:, 2-h, :) + two*gradvb(:, 1-h, :)
      gradvb(:, 3-h, :) = gradvb(:, 3-h, :) - gradvb(:, 1-h, :)
      gradvb(:, 1-h, :) = 0.0_8
      gradub(:, 2-h, :) = gradub(:, 2-h, :) + two*gradub(:, 1-h, :)
      gradub(:, 3-h, :) = gradub(:, 3-h, :) - gradub(:, 1-h, :)
      gradub(:, 1-h, :) = 0.0_8
    END DO
  END DO
!$BWD-OF II-LOOP 
  DO j=1,jm
!$BWD-OF II-LOOP 
!DIR$ IVDEP
    DO i=1,im
! #include "rhs/gradop_7pi.F"
! #include "rhs/gradop_7pj.F"
!idir
!jdir
      volm1 = one/vol(i, j)
      dxm1 = half*(nx(i, j, 1)+nx(i+1, j, 1))*volm1
      dxm2 = half*(nx(i, j, 2)+nx(i, j+1, 2))*volm1
      dym1 = half*(ny(i, j, 1)+ny(i+1, j, 1))*volm1
      dym2 = half*(ny(i, j, 2)+ny(i, j+1, 2))*volm1
      gvib = dym1*gradvb(i, j, 2) + dxm1*gradvb(i, j, 1)
      gvjb = dym2*gradvb(i, j, 2) + dxm2*gradvb(i, j, 1)
      gradvb(i, j, 2) = 0.0_8
      guib = dym1*gradub(i, j, 2) + dxm1*gradub(i, j, 1)
      gujb = dym2*gradub(i, j, 2) + dxm2*gradub(i, j, 1)
      gradub(i, j, 2) = 0.0_8
      gradvb(i, j, 1) = 0.0_8
      gradub(i, j, 1) = 0.0_8
      velyb(i, j+1) = velyb(i, j+1) + b1*gvjb
      velyb(i, j-1) = velyb(i, j-1) - b1*gvjb
      velyb(i, j+2) = velyb(i, j+2) + b2*gvjb
      velyb(i, j-2) = velyb(i, j-2) - b2*gvjb
      velxb(i, j+1) = velxb(i, j+1) + b1*gujb
      velxb(i, j-1) = velxb(i, j-1) - b1*gujb
      velxb(i, j+2) = velxb(i, j+2) + b2*gujb
      velxb(i, j-2) = velxb(i, j-2) - b2*gujb
      velyb(i+1, j) = velyb(i+1, j) + b1*gvib
      velyb(i-1, j) = velyb(i-1, j) - b1*gvib
      velyb(i+2, j) = velyb(i+2, j) + b2*gvib
      velyb(i-2, j) = velyb(i-2, j) - b2*gvib
      velxb(i+1, j) = velxb(i+1, j) + b1*guib
      velxb(i-1, j) = velxb(i-1, j) - b1*guib
      velxb(i+2, j) = velxb(i+2, j) + b2*guib
      velxb(i-2, j) = velxb(i-2, j) - b2*guib
    END DO
  END DO
!$BWD-OF II-LOOP 
  DO j=1-gh,jm+gh
!$BWD-OF II-LOOP 
!DIR$ IVDEP
    DO i=1-gh,im+gh
      ro = w(i, j, 1)
      rom1 = one/ro
      velx(i, j) = w(i, j, 2)*rom1
      vely(i, j) = w(i, j, 3)*rom1
      velz(i, j) = w(i, j, 4)*rom1
!
      ec = half*(velx(i, j)*velx(i, j)+vely(i, j)*vely(i, j)+velz(i, j)*&
&       velz(i, j))
! ec  = HALF*( velx(i,j)*velx(i,j) &
!            + vely(i,j)*vely(i,j))
!
      eloc = (w(i, j, 5)-ec*ro)*rom1
!
      tloc(i, j) = eloc*cvm1
!
      p(i, j) = (gam-one)*ro*eloc
!  p(i,j)  = ro*rgaz*tloc(i,j)
      htot = (w(i, j, 5)+p(i, j))*rom1
!h(i,j,1)  = w(i,j,4)
!h(i,j,2)  = w(i,j,4) * velx(i,j)
!h(i,j,3)  = w(i,j,4) * vely(i,j)
!h(i,j,4)  = w(i,j,4) * velz(i,j) + p(i,j)
!h(i,j,5)  = w(i,j,4) * htot
      temp = tloc(i, j)/(s_suth+tloc(i, j))
      temp0 = SQRT(tloc(i, j))
      tempb = temp0*betas*mub(i, j)/(s_suth+tloc(i, j))
      IF (tloc(i, j) .EQ. 0.0) THEN
        tlocb(i, j) = tlocb(i, j) + (1.0-temp)*tempb
      ELSE
        tlocb(i, j) = tlocb(i, j) + temp*betas*mub(i, j)/(2.0*temp0) + (&
&         1.0-temp)*tempb
      END IF
      mub(i, j) = 0.0_8
      htotb = w(i, j, 3)*gb(i, j, 5) + w(i, j, 2)*fb(i, j, 5)
      pb(i, j) = pb(i, j) + gb(i, j, 3) + fb(i, j, 2) + rom1*htotb
      elocb = ro*(gam-one)*pb(i, j) + cvm1*tlocb(i, j)
      tlocb(i, j) = 0.0_8
      tempb = rom1*elocb
      wb(i, j, 5) = wb(i, j, 5) + rom1*htotb + tempb
      rob = eloc*(gam-one)*pb(i, j) - ec*tempb
      pb(i, j) = 0.0_8
      ecb = -(ro*tempb)
      tempb = half*ecb
      velzb(i, j) = velzb(i, j) + w(i, j, 3)*gb(i, j, 4) + w(i, j, 2)*fb&
&       (i, j, 4) + 2*velz(i, j)*tempb
      velyb(i, j) = velyb(i, j) + w(i, j, 3)*gb(i, j, 3) + w(i, j, 2)*fb&
&       (i, j, 3) + 2*vely(i, j)*tempb
      wb(i, j, 3) = wb(i, j, 3) + htot*gb(i, j, 5) + velz(i, j)*gb(i, j&
&       , 4) + vely(i, j)*gb(i, j, 3) + velx(i, j)*gb(i, j, 2) + gb(i, j&
&       , 1) + rom1*velyb(i, j)
      gb(i, j, 5) = 0.0_8
      gb(i, j, 4) = 0.0_8
      gb(i, j, 3) = 0.0_8
      velxb(i, j) = velxb(i, j) + w(i, j, 3)*gb(i, j, 2) + w(i, j, 2)*fb&
&       (i, j, 2) + 2*velx(i, j)*tempb
      gb(i, j, 2) = 0.0_8
      gb(i, j, 1) = 0.0_8
      wb(i, j, 2) = wb(i, j, 2) + htot*fb(i, j, 5) + velz(i, j)*fb(i, j&
&       , 4) + vely(i, j)*fb(i, j, 3) + velx(i, j)*fb(i, j, 2) + fb(i, j&
&       , 1) + rom1*velxb(i, j)
      fb(i, j, 5) = 0.0_8
      fb(i, j, 4) = 0.0_8
      fb(i, j, 3) = 0.0_8
      fb(i, j, 2) = 0.0_8
      fb(i, j, 1) = 0.0_8
      rom1b = (w(i, j, 5)+p(i, j))*htotb + (w(i, j, 5)-ec*ro)*elocb + w(&
&       i, j, 4)*velzb(i, j) + w(i, j, 3)*velyb(i, j) + w(i, j, 2)*velxb&
&       (i, j)
      wb(i, j, 4) = wb(i, j, 4) + rom1*velzb(i, j)
      velzb(i, j) = 0.0_8
      velyb(i, j) = 0.0_8
      velxb(i, j) = 0.0_8
      rob = rob - one*rom1b/ro**2
      wb(i, j, 1) = wb(i, j, 1) + rob
    END DO
  END DO
END SUBROUTINE FLUX_NUM_DNC5_MAXSC_2D_B
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

